### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by sasojadrovski** [SwiftKickMobile/SwiftMessages#100]
Hey guys,

Thank you for this awesome library!

While running an iOS app through Instruments I have noticed that a potential memory leak was reported in the `SwiftMessages.swift` file, precisely in the method `show(config:view:)`.

The leak was reported on line 319 of the latest stable version of this library, i.e. v.3.3.4.

For your reference, here is the entire function:

```swift
open func show(config: Config, view: UIView) {
        DispatchQueue.main.async { [weak self] in
            guard let strongSelf = self else { return }
            let presenter = Presenter(config: config, view: view, delegate: strongSelf)
            strongSelf.syncQueue.async { [weak self] in // 1 Byte
                guard let strongSelf = self else { return }
                strongSelf.enqueue(presenter: presenter)
            }
        }
    }
```

Could you please investigate? 

Thanks in advance and keep up the great work! 👍

**Comment by wtmoose** [comment]
This seems like a Swift bug. I was able to eliminate the leak by making change the order of two property definitions, from

````swift
class Presenter: NSObject {
    ...
    let config: SwiftMessages.Config
    let view: UIView
    ...
}
````

to

````swift
class Presenter: NSObject {
    ...
    let view: UIView
    let config: SwiftMessages.Config
    ...
}
````

You can easily make this change in your codebase and check. I've promoted the change to the head of master.

**Comment by sasojadrovski** [comment]
Hey @wtmoose,

Thanks for looking into this so fast, I appreciate it!

Yes, this definitely seems like a Swift bug since the minor change that you have made fixes the "memory leak". I run the app through Instruments again, and the leak was not reported.

Thanks!
