### ISSUE TITLE
Is there good possible to remove eventListener from array?

### ISSUE THREAD

**Issue by csiAndreyMitskevich** [SwiftKickMobile/SwiftMessages#101]
We can add `eventListener` but how we can remove it from array of event listeners `[EventListener]`?
```
config.eventListeners.append() { event in
    if case .didHide = event { print("yep") }
}
```
We can use `SwiftMessages.defaultConfig.eventListeners.removeAll()` but it is not better possible.

**Comment by wtmoose** [comment]
You can eliminate the need to clean up event listeners by making single-use copies of `SwiftMessages.Config`. For example:

````
let view = ...
var config = SwiftMessages.defaultConfig
config.eventListeners = [{...}]
SwiftMessages.show(config: config, view: view)
````

Does that help?

**Comment by wtmoose** [comment]
Reopen if you get back to this and have further questions.

**Comment by csiAndreyMitskevich** [comment]
It should works. Thanks!
