### ISSUE TITLE
Control animation

### ISSUE THREAD

**Issue by fotiDim** [SwiftKickMobile/SwiftMessages#103]
Is there any way to either:

- Control the animation speed?
- Disable the animation?
- Replace the text of the messageView on the fly, without going through the hide/show animation?

**Comment by wtmoose** [comment]
You can supply a custom animation using the `.custom` presentation style. And you supply the message view, you can do anything you want with it while it's being shown.

If you need more detailed help, I suggest posting your question on StackOverflow where there's a larger pool of people eager to help.
