### ISSUE TITLE
iOS8 message like iOS9 - Help

### ISSUE THREAD

**Issue by prsolucoes** [SwiftKickMobile/SwiftMessages#106]
Hi,

To be perfect, im trying use it on iOS8 and have the same behavior on message with nib "CenteredView" but using "MessageViewIOS8". With "MessageViewIOS8" all buttons are hidden and the message is getting full-width.

Can you do it? Will be perfect, today im only using status bar message.

Thanks.

**Comment by wtmoose** [comment]
Message views always span the full width. So here's what you need to do:

1. Copy the nib into your project
2. Add a sub view and assign it to the `backgroundView` outlet
3. Set the message view's background color to clear
4. Adjust the layout of sub views to suit your needs

**Comment by prsolucoes** [comment]
Hi,

Can i make it without nib files? Only sub-classing MessageView?

Thanks.

**Comment by wtmoose** [comment]
Yes. You can display any arbitrary view. But it will always be full width, so you must provide a sub view for the background and make the top-level view clear.

**Comment by prsolucoes** [comment]
The gray/blur effect depend of the nib? Or it is independent?

**Comment by prsolucoes** [comment]
Another question is about the events. I want make messages with yes/no button and receive the event of what use click.

**Comment by wtmoose** [comment]
See #107
