### ISSUE TITLE
TopBottom and Center animations are not subclassable 

### ISSUE THREAD

**Issue by Austinate** [SwiftKickMobile/SwiftMessages#108]
Hi, first of all — thanks for such an awesome library.

Issue is that release changelog says:
```
 The TopBottomAnimation and CenterAnimation animations both implement Animator and may be subclassed (configuration options will be added in a future release). You may use the PhysicsPanHandler class to incorporate a physics-based dismissal gesture into any custom animator.
```

But TopBottom and Center animations are not marked as 'open' so there is no ability to subclass them (plus we should mark exact functions with 'open' too). 

If there will be an agreement on what should be open inside them (same that is public now?) i can create a PR.

**Comment by Austinate** [comment]
Probably there is a need to verify that everything which is subclassable is open from now too

**Comment by wtmoose** [comment]
Hi. Glad you like the library. The access levels are as intended until I get a chance to clean up the API. The release notes are a mistake. My suggestion for now is to copy-paste whatever code you want to use in a new class.

**Comment by Austinate** [comment]
Thanks for reply. Should we close an issue then?

**Comment by wtmoose** [comment]
Yeah. Would you mind elaborating on what customizations you want to make so I can take it into consideration as I make these classes customizable?
