### ISSUE TITLE
long text is cut, can i have a variable height alert

### ISSUE THREAD

**Issue by BasantAshraf** [SwiftKickMobile/SwiftMessages#109]
Can alert adapt its height to text it contains?

**Comment by StanDimitroff** [comment]
@BasantAshraf did you find a solution on this?

**Comment by wtmoose** [comment]
@StanDimitroff The built-in alerts are variable height where it makes sense. If a particular layout doesn't work for you, you can easily customize it by copying the nib file into your project. Or you can supply your own view.

What specifically is the problem (e.g. screenshot)?

**Comment by StanDimitroff** [comment]
@wtmoose thanks for the response. I supplied my own view for the case. Cheers!
