### ISSUE TITLE
Subclassable default animators

### ISSUE THREAD

**Issue by Austinate** [SwiftKickMobile/SwiftMessages#110]
As for starting point i'd suggest to make all main functions open for both `TopBottomAnimation` & `CenterAnimation`.
In details:

### TopBottomAnimation:
- `hide(context:completion:)`
- `showAnimation(completion: @escaping AnimationCompletion)`

### CenterAnimation:
- `hide(context:completion:)`
- `showAnimation(completion: @escaping AnimationCompletion)`

In my exact use-case i banner to appear with spring animation, but instead of just having empty space at the top during it i would like banner height to become a bit bigger than needed and get back to normal at animation end. Not sure if i need to subclass in this case or it will be better to create custom animator, so would be nice if will be any advice :)

**Comment by wtmoose** [comment]
>In my exact use-case i banner to appear with spring animation, but instead of just having empty space at the top during it i would like banner height to become a bit bigger than needed and get back to normal at animation end. Not sure if i need to subclass in this case or it will be better to create custom animator, so would be nice if will be any advice :)

Sorry, I dropped the ball on responding to this.

I think a solution for your use case is already build into SwiftMessages. Take a look at the `bounceAnimationOffset` property on the `MarginAdjustable` protocol. The animator uses the value of this property to adjust the top or bottom layout margin of the view and it's position within the clipping container view such that there's no empty space displayed during the spring animation.

`bounceAnimationOffset` is an `@IBInspectable` property on `MessageView`, so you can check the values used on the various nib files included with SwiftMessages.

**Comment by Austinate** [comment]
Thanks for detailed answer! i ended up with replicating TopBottomAnimation functionality (with some changes) in my custom class conforming to Animator protocol.
