### ISSUE TITLE
how to check message is showing right now or not?

### ISSUE THREAD

**Issue by BhavinBhadani** [SwiftKickMobile/SwiftMessages#115]
how to check message is showing right now or not?

**Comment by wtmoose** [comment]
Right now, you can track it yourself using event listeners. But I'll add APIs for it.

**Comment by wtmoose** [comment]
@BhavinBhadani I've added the following, available on the head of `master` if you want to take a look and let me know if this does what you need.

### Retrieving Messages

There are several APIs available for retrieving messages that are currently being shown, hidden, or queued to be shown. These APIs are useful for updating messages
when some event happens without needing to keep temporary references around.
See also `eventListeners`.

````swift
// Get a message view with the given ID if it is currently 
// being shown or hidden.
if let view = SwiftMessages.current(id: "some id") { ... }

// Get a message view with the given ID if is it currently 
// queued to be shown. 
if let view = SwiftMessages.queued(id: "some id") { ... }

// Get a message view with the given ID if it is currently being
// shown, hidden or in the queue to be shown.
if let view = SwiftMessages.currentOrQueued(id: "some id") { ... }
