### ISSUE TITLE
Cannot get current view by id

### ISSUE THREAD

**Issue by chengsam** [SwiftKickMobile/SwiftMessages#117]
I tried to use the following method to get the current view to update the message:

`if let view = SwiftMessages.current(id: "some id") { ... }`

However, I found that I cannot get the current view even I have set the `id`. After some troubleshooting, I found that the `id` of the current view is not the `id` I set by `view.id = "some id"`. Finally, I have to add my extension to make it worked:

```
extension MessageView: Identifiable {
}
```

Is it a bug or something else? Thanks.

**Comment by wtmoose** [comment]
SwiftMessages wouldn't know about your view's `id` property unless you adopt the `Identifiable` protocol. See the API documentation for the function you're calling.

**Comment by chengsam** [comment]
I thought `MessageView` adopts the `Identifiable` protocol already, so it is a normal behaviour to adopt myself?

**Comment by wtmoose** [comment]
Ah, I see whats going on. I accidentally removed `Identifiable` from `MessageView`. Thanks for reporting.

Try the latest.
