### ISSUE TITLE
here is some conflict with Firebase 

### ISSUE THREAD

**Issue by bizibizi** [SwiftKickMobile/SwiftMessages#118]
https://stackoverflow.com/questions/45356479/firebase-root-view-controller-not-found-warning

**Comment by wtmoose** [comment]
Got it, thanks

**Comment by bizibizi** [comment]
can you fix that?

**Comment by wtmoose** [comment]
I don’t plan to work on reproducing this on my own because it isn’t clear there is a real problem. I asked the poster for a sample project, but haven’t heard back.

Did you file a ticket with Firebase? I would think they’re in a better position to say if the warning is a false positive.
