### ISSUE TITLE
Support for pushing other content down when displaying a window (or view controller) message?

### ISSUE THREAD

**Issue by cody1024d** [SwiftKickMobile/SwiftMessages#119]
Was just curious if the above could be done?

Essentially, I have a use case, where, when a custom-view-message is displayed (at the top), I would like to push the rest of the content down, as opposed to overlaying it.

I have a *feeling* this could/would be done with a custom animator; but was just wondering if this was already a solved use-case or not?

**Comment by wtmoose** [comment]
No that isn’t supported. SM creates a clipping container view and puts the message view inside of it.

**Comment by cody1024d** [comment]
Ok, thanks!  It's probably more effort than it'd be worth to fit a square-peg into a round hole by messing with the view hierarchy within the animator.  Closing this out!
