### ISSUE TITLE
Xcode9 (Latest) Cannot Import Module

### ISSUE THREAD

**Issue by sarjilhasan** [SwiftKickMobile/SwiftMessages#121]

**Comment by wtmoose** [comment]
Are you using the 4.0.0 beta?

**Comment by sarjilhasan** [comment]
Hello,

I am using the one that was published on Sept 12, 9A235.

**Comment by wtmoose** [comment]
I'm asking about SwiftMessages 4.0.0 beta. That is the version that work with Xcode 9.

**Comment by sarjilhasan** [comment]
Oh, I am not. Apologies. I am using 3.5.1. How may I access 4.0.0?

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/releases

**Comment by sarjilhasan** [comment]
Thank you.
