### ISSUE TITLE
How do I install version 4.0 with cocoapods?

### ISSUE THREAD

**Issue by ndduong97** [SwiftKickMobile/SwiftMessages#122]
I am trying to update my SwiftMessages to 4.0, but I keep getting 3.5.1. 

How can I update it to 4.0?

**Comment by wtmoose** [comment]
https://guides.cocoapods.org/syntax/podfile.html

**Comment by wtmoose** [comment]
4.0.0 isn’t released

**Comment by ripventura** [comment]
Is there any ETA on the release of the 4.0.0 on cocoa pods? 
I use this pod as dependency on another personal pod, and since .podspec files can't use ":git"/":tag", there's no way I can pod trunk push my pod because of the 3.5.1 version...

**Comment by wtmoose** [comment]
@ripventura Ran into some merge issues yesterday and had to punt on it. Should release today.

**Comment by ripventura** [comment]
Is there any way to get notified when 4.0.0 is available on cocoa pods?

**Comment by wtmoose** [comment]
@ripventura it's out now.

**Comment by ripventura** [comment]
@wtmoose thanks man, you rock!
