### ISSUE TITLE
iPhone X support?

### ISSUE THREAD

**Issue by markst** [SwiftKickMobile/SwiftMessages#123]
Particularly when using window level presentation context.

**Comment by markst** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/blob/master/SwiftMessages/BaseView.swift#L128

**Comment by mgarbage** [comment]
Yes and not only iPhone X but iOS 11 SDK in general...

**Comment by wtmoose** [comment]
See the latest beta release. Should go out of beta today.
