### ISSUE TITLE
UIView has no member safeAreaInsets

### ISSUE THREAD

**Issue by akmalshukri** [SwiftKickMobile/SwiftMessages#126]
After i update the pod .. i got this error ..
![screen shot 2017-09-29 at 11 29 33 am](https://user-images.githubusercontent.com/8844498/30999752-81020800-a509-11e7-88dc-5533906eb5f8.png)

**Comment by wtmoose** [comment]
Are you on Xcode 9?

**Comment by akmalshukri** [comment]
yaa .. i on xcode 9 ...

**Comment by wtmoose** [comment]
I don’t know. It isn’t normal and you haven’t given me much info. None of those errors should be errors on Xcode 9 iOS 11 SDK.

**Comment by akmalshukri** [comment]
Sorry sir .. my mistake .. actually i on Xcode 8 .. now i update to Xcode 9 and it worked .. Thank you Sir ..

**Comment by wtmoose** [comment]
Glad you fixed it.
