### ISSUE TITLE
Presentation of message fails if application is in background state

### ISSUE THREAD

**Issue by letko-dmitry** [SwiftKickMobile/SwiftMessages#131]
I present message from the bottom, so `TopBottomAnimation` animator and the method `func showAnimation(completion: @escaping AnimationCompletion)` are used. And as expected the completion closure is called with `completed` value of `false`, because `UIView.animate` does the same thing.
So, does anyone have any thoughts about how we can improve that and do not break anything else? )

**Comment by wtmoose** [comment]
Fixed in 4.1.0 release. I added a check for application not active.
