### ISSUE TITLE
Support build static library

### ISSUE THREAD

**Issue by crossle** [SwiftKickMobile/SwiftMessages#133]
Swift 4 support  build static library, CoacoaPods 1.4 also support, plz support import SwiftMessages as static library

**Comment by wtmoose** [comment]
SwiftMessages includes resources. Do you mean static framework?

**Comment by crossle** [comment]
Idk static framework, it's just include static library and resources bundle?

**Comment by wtmoose** [comment]
http://www.knowstack.com/framework-vs-library-cocoa-ios/

**Comment by crossle** [comment]
Before swift4, it only support framework build for swift, now it can use like OC use static library
e.g. Cocoapods !use_framework, but if the library include resources, need manual copy the resource?

**Comment by wtmoose** [comment]
If you're using `!use_framework`, then CocoaPods 1.4.0 should support static Swift frameworks:

https://github.com/CocoaPods/Core/pull/386

If you're not using `!use_framework`, then CocoaPods is targeting 1.5.0 for static Swift libraries:

https://github.com/CocoaPods/CocoaPods/issues/6899

Which are you looking for?

I'm not sure static library makes sense for SwiftMessages if it requires manually copying resources (I have no idea if CocoaPods copy the resources). At that point, why not just do a full manual install?

I should point out that neither of these are possible with the current CocoaPods release 1.3.1 and it isn't likely that I'll work on features for unreleased versions of CocoaPods.

**Comment by wtmoose** [comment]
Closing. If you can clarify what you want precisely, I will reopen.
