### ISSUE TITLE
Displaying multiple messages seems broken

### ISSUE THREAD

**Issue by allaire** [SwiftKickMobile/SwiftMessages#135]
Following the README paragraph about displaying multiple messages:

> Multiple instances of SwiftMessages can be used to show more than one message at a time. Note that the static SwiftMessages.show() and other static APIs on SwiftMessage are just convenience wrappers around the shared instance SwiftMessages.sharedInstance):

```
let otherMessages = SwiftMessages()
SwiftMessages.show(...)
otherMessages.show(...)
```
I wasn't able to show the message that is declared by a new instance of `SwiftMessages()`, see:

![screen shot 2017-11-03 at 11 44 49 am](https://user-images.githubusercontent.com/304461/32382736-6c72da9c-c08c-11e7-8b5b-23d5e6b6dd14.png)

It's my understanding that the status bar should show up while the other alerts are queueing in the sharedInstance instance, but the status bar message is simply not showing up.

**Comment by wtmoose** [comment]
Are you sure it isn't being obscured by the other message? And does it show if you put it first?

**Comment by allaire** [comment]
@wtmoose Hi! Thanks for the fast reply, I made a quick GIF, available here:

https://cl.ly/2d1l2I202A1u/Screen%20Recording%202017-11-03%20at%2011.51%20AM.gif

Let me know if you need anything else 👍

**Comment by wtmoose** [comment]
I think you need to retain `otherMessages`

**Comment by allaire** [comment]
@wtmoose I'm unsure of what I should do to retain `otherMessages`

**Comment by wtmoose** [comment]
Make it a property of some instance (e.g. your view controller)

**Comment by allaire** [comment]
@wtmoose That's what I thought, I declared: `var otherMessages = SwiftMessages()` at the top of my VC and I get the following error:

`Instance member 'otherMessages' cannot be used on type 'ViewController'`

**Comment by wtmoose** [comment]
Sounds like you're referencing `otherMessages` from a static context, in which case you'd want to make `otherMessages` a static variable.

**Comment by allaire** [comment]
@wtmoose Duh, stupid me, it worked using static! I'm going to update the README to clarify this 👍
