### ISSUE TITLE
Do you support RTL?

### ISSUE THREAD

**Issue by H-Ghadirian** [SwiftKickMobile/SwiftMessages#137]
How can I change message direction?

**Comment by wtmoose** [comment]
Yep.

**Comment by H-Ghadirian** [comment]
So, tell me how?

**Comment by wtmoose** [comment]
https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html

**Comment by pranavpari** [comment]
Its not working, if its working for anyone please tell  me

**Comment by fadizant** [comment]
> Its not working, if its working for anyone please tell me

I have same issue, but you can handle it using `transform` to content elements

```
view.backgroundView.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)
view.titleLabel?.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)
view.iconImageView?.transform = CGAffineTransform(scaleX: -1.0, y: 1.0)

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/issues/181
