### ISSUE TITLE
Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "org.cocoapods.SwiftMessages"

### ISSUE THREAD

**Issue by Eric0625** [SwiftKickMobile/SwiftMessages#139]
I installed Swiftmessages through Cocoapods, and run the sample code, then this error pops out in the log window, the code stops at : `view.configureTheme(.warning)`

**Comment by Eric0625** [comment]
screenshots:

![screen shot 2017-11-16 at 10 02 21 am](https://user-images.githubusercontent.com/18132007/32901441-6d8a6a8e-cab5-11e7-916e-ac416ffcf077.png)
![screen shot 2017-11-16 at 10 02 44 am](https://user-images.githubusercontent.com/18132007/32901416-60a8f33a-cab5-11e7-849d-e0017150c10d.png)

**Comment by wtmoose** [comment]
Are you on 4.1.0?

**Comment by Eric0625** [comment]
I didn't remember it, but I'm quite sure I used `pod 'SwiftMessages'` and my platform is `platform :ios, '10.3'`

**Comment by wtmoose** [comment]
Look in Podfile.lock. I can't address this issue without knowing precisely what version you're using.

**Comment by Eric0625** [comment]
It's OK now when I used `pod update`, thanks for your notice, maybe the pod's database is out of date before
