### ISSUE TITLE
Cant set the width of the view that form custom nib

### ISSUE THREAD

**Issue by rainedAllNight** [SwiftKickMobile/SwiftMessages#141]
![c334317a-9091-407b-be12-233b57884df6](https://user-images.githubusercontent.com/16357931/33124393-be4cdbc6-cfb7-11e7-8357-06e9a2ee5bf5.png)

**Comment by wtmoose** [comment]
For reference see `CenteredView.nib`.

Message views are always full width. So in your screenshot, the white area needs to be a subview of the message view and connected to the `backgroundView` outlet. You can then make the `backgroundView` any width you want.

**Comment by rainedAllNight** [comment]
I follow your method，But it still doesn't work。。
![f47be272-6235-40ef-9cfa-27c0af14a192](https://user-images.githubusercontent.com/16357931/33156552-be224202-d035-11e7-9551-aca8955a7d66.png)

**Comment by wtmoose** [comment]
Set the top-level view's background to clear? If you can't figure it out, attach your nib file.

**Comment by rainedAllNight** [comment]
set the top-level view's background to clear is working, thank you very much
