### ISSUE TITLE
Hi guys! 

### ISSUE THREAD

**Issue by mikhn0** [SwiftKickMobile/SwiftMessages#143]
I use your library in my project. Everything is awesome!!!! But can you add ability to customize alignment of bodylabel? Currently it has left alignment by default. And if you add leading and trailing constraints in the stackview, other developers will be able to choose where to place the text. Please could you add this point to your framework?)

**Comment by wtmoose** [comment]
Hi. The layouts are designed to be customized. Just copy the nib fie into your project and adjust the layout however you like.

**Comment by mikhn0** [comment]
Would you mind if I do pull request in your repository? I think it would be
better to manage  ui.

пн, 27 нояб. 2017 г. в 18:13, Timothy Moose <notifications@github.com>:

**Comment by wtmoose** [comment]
You can submit a pull request and I'll take a look. But if your changes involve adding constraint outlets to the `MessageView` class, it is unlikely that I'll include them. `MessageView` is intended to be as light-weight as possible and agnostic to any specific layout.
