### ISSUE TITLE
Attach SwiftMessages to Top View Controller view and above navigation bar

### ISSUE THREAD

**Issue by TaoufikBouabid** [SwiftKickMobile/SwiftMessages#144]
Hi, I'm using your awesome library in my app,  I would like to Attach SwiftMessages to Top View Controller view and above navigation bar , my configuration is 

```swift
if let top = UIApplication.topViewController() {
     config.presentationContext = .view(top.view)
 }
```

P.s : I cant use config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar) because I would like to present other view controllers when tapping

**Comment by wtmoose** [comment]
Your problem description is a little bit vague, but it sounds you may want the message to be in the navigation controller's view? Try this:

````swift
if let top = UIApplication.topViewController()?.navigationController {
     config.presentationContext = .view(top.view)
}
````

**Comment by wtmoose** [comment]
No reply from poster. Closing
