### ISSUE TITLE
Crash while displaying message randomly

### ISSUE THREAD

**Issue by mansishah278** [SwiftKickMobile/SwiftMessages#146]
![screen shot 2017-12-11 at 6 14 54 pm](https://user-images.githubusercontent.com/22022743/33831773-6d26c0ee-de9f-11e7-82c5-36f65283ca95.png)
Randomly Crashing on

 /// Returns the associated image.
    public var image: UIImage {        
        return UIImage(named: rawValue, in: Bundle.sm_frameworkBundle(), compatibleWith: nil)!
    }

Due to the force unwrap _I guess_

**Pod Version is 3.4.0**
**Xcode 9, Swift 3.2**

**Comment by wtmoose** [comment]
Update to the latest version

**Comment by mansishah278** [comment]
@wtmoose 3.4.0 is the latest version
Why have you closed the issue? I still face it 🙂

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/releases/tag/4.1.0

**Comment by mansishah278** [comment]
I am not able to update it with cocoapods

**Comment by wtmoose** [comment]
Sounds like you've got a CocoaPods problem: https://cocoapods.org/?q=swiftmessages

**Comment by mansishah278** [comment]
Ok thank you very much @wtmoose 😄

**Comment by mansishah278** [comment]
I will check cocoapods problem
