### ISSUE TITLE
.bottom seems is not working

### ISSUE THREAD

**Issue by ivl** [SwiftKickMobile/SwiftMessages#149]
.bottom context seems is not working in view

**Comment by wtmoose** [comment]
It works in the demo app. Could you elaborate?

**Comment by ivl** [comment]
I am trying to show notification from xib in another container in view. Buts its not showing. If to use .top or .center it placing correctly nut if to use .bottom - I just see blinking

**Comment by wtmoose** [comment]
Hmm. Haven't seen or heard of this before. I'll need to reproduce it in order to help, so if you could attach a demo project that reproduces it or provide all of your SwiftMessages code here, I'll see what I can do.

**Comment by ivl** [comment]
Found issue. It was my fault. xib file bottom constraint was not installed and during installation to view container it just collapsed. Sorry for false alarm
