### ISSUE TITLE
Snackbar show ontop of keyboard

### ISSUE THREAD

**Issue by kuanthye** [SwiftKickMobile/SwiftMessages#150]
snackbar block by keybord

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/issues/43

**Comment by kuanthye** [comment]
Any sample on assign the view to inputAccessoryView ?
sorry im fresh on ios swift

**Comment by kuanthye** [comment]
i able to figure out. close case, Thanks
