### ISSUE TITLE
Swift 4 update

### ISSUE THREAD

**Issue by ethanparker** [SwiftKickMobile/SwiftMessages#154]
My team is looking into messaging options for Swift and we'd love to use this one. When is Swift 4 update coming?

**Comment by wtmoose** [comment]
Swift 4 has been supported since Sep 20, 2017. What gave you the impression that it wasn't?

**Comment by wtmoose** [comment]
@akhatmullin the current CocoaPods version is 4.1.0. If you're seeing an older version, try `pod repo update`.

https://cocoapods.org/?q=swiftmess
