### ISSUE TITLE
unable to load a custom nib

### ISSUE THREAD

**Issue by iadxworld** [SwiftKickMobile/SwiftMessages#158]
I am trying to load a custom nib, which looks as follows

![screen shot 2018-01-23 at 4 51 04 pm](https://user-images.githubusercontent.com/11725530/35273181-a3d45892-005d-11e8-91c7-7f9810687220.png)

Following is the code. All it shows is a small status bar message. Its not fully showing the view. Following is the code: 

````swift
let mview : MessageView = try! SwiftMessages.viewFromNib(named: "WelcomeMsg")
mview.configureDropShadow()
var config = SwiftMessages.defaultConfig
config.duration = .forever
config.presentationStyle = .top
config.dimMode = .gray(interactive: true)
SwiftMessages.show(config: config, view: mview)
````

Am I doing something wrong?

**Comment by wtmoose** [comment]
The height of the view is determined by it's internal Auto Layout constraints. So it sounds like you've not fully constrained the view's height. If you can't figure it out, attach the nib file and I'll take a look.

**Comment by iadxworld** [comment]
I have them constraints already put. I am really not sure why is it not working. So, as you said I am attaching the nib file. 

Following is the class for the same :

`import UIKit
import SwiftMessages

class WelcomeMsg: MessageView {

    @IBOutlet weak var profimage: UIImageView!
    @IBOutlet weak var name: UILabel!

}`


[WelcomeMsg.xib](https://github.com/SwiftKickMobile/SwiftMessages/files/1657221/WelcomeMsg.xib.zip)


Thanks for the prompt response. highly appreciate it.

**Comment by wtmoose** [comment]
I took a look at your nib file and your AutoLayout constraints do not constrain the height. The image and label have no bottom constraints, so there is nothing to prevent their superview from collapsing vertically.

**Comment by iadxworld** [comment]
Alright! I was just testing the layout before putting it in the actual view, Hence I casually just put in elements without any constraints. But as you suggested, Adding the constraints worked.

This is awesome Library By The Way.

Cheers!

**Comment by wtmoose** [comment]
Thanks! Good to know you got it working.

**Comment by iadxworld** [comment]
Hey there,

Just have an issue here. I want to put offset of about 10px from the status bar. I am tried playing my way around. I was unable to achieve this. 

I implemented the `mview.safeAreaTopOffset = 20` but it doesnt work. I even tried implementing the `MarginAdjustable` delegate, but I am quite unsure how to use it. 

Can you please guide me here!

**Comment by wtmoose** [comment]
See CardView.xib
