### ISSUE TITLE
is there any way to right align the MessageView ?

### ISSUE THREAD

**Issue by nadia-am** [SwiftKickMobile/SwiftMessages#159]
i want the configure Theme be at right of screen or  when using custom view i can set message and title in the main view, how can i do it?

**Comment by wtmoose** [comment]
Have you tried `messageView.titleLabel?.textAlignment = .right`?

Otherwise, you can copy the nib file into your project and modify it. Or you can supply your own nib file. Or you can display an arbitrary view.
