### ISSUE TITLE
Status bar shown in view controllers with a hidden status bar

### ISSUE THREAD

**Issue by whitepaperclip** [SwiftKickMobile/SwiftMessages#16]
```swift
SwiftMessages.defaultConfig.preferredStatusBarStyle = .None
let message = MessageView.viewFromNib(layout: .CardView)
message.configureTheme(theme)
message.configureContent(title: title, body: body)
message.button?.hidden = true
SwiftMessages.show(view: message)
```

In the view controller (obviously):

```swift
override func prefersStatusBarHidden() -> Bool {
    return true
}
```

When the `MessageView` is displayed, the view controller shows its status bar up until the moment the `MessageView` hides automatically.

**Comment by wtmoose** [comment]
Are you setting any other configuration options, such as `presentationContext`?

**Comment by whitepaperclip** [comment]
No, I didn't. If I pass in the relevant current view controller, will it honor that particular controller's status bar visibility?

**Comment by whitepaperclip** [comment]
Actually, I don't think that should matter. It *should* check `UIApplication.sharedApplication().statusBarHidden` before forcing the status bar to be visible.

**Comment by wtmoose** [comment]
Agree 100%.

**Comment by whitepaperclip** [comment]
Actually... it does. Strange.

https://github.com/SwiftKickMobile/SwiftMessages/blob/master/SwiftMessages/Presenter.swift#L134

This line is evaluating to false in my application. Could be an iOS bug? I'll dig a bit further and post in a bit.

**Comment by whitepaperclip** [comment]
It was before of WindowViewController. Added this to the bottom of WindowViewController.swift:

```swift
override func prefersStatusBarHidden() -> Bool {
    return UIApplication.sharedApplication().statusBarHidden
}
```

Should I submit a pull request?

**Comment by wtmoose** [comment]
No. I already released 1.1.4 with the same change. Thanks, though!

**Comment by wtmoose** [comment]
Well, pod trunk push failed. Should be up in a moment.

**Comment by whitepaperclip** [comment]
Oh wow, you were on top of that! Didn't see the commit.

Thank you!!

**Comment by wtmoose** [comment]
👍

**Comment by yunustek** [comment]
Hi Everybody, I solved the problem 👍 
When you add the extension you can solve the problem:
The extension function solved when you open in any view controller. The code will open with the view controller prefersStatusBarHidden.
```
import SwiftMessages

extension WindowViewController {
	open override var prefersStatusBarHidden: Bool {
		return UIApplication.shared.topMostViewController()?.prefersStatusBarHidden ?? false
	}
}
```
