### ISSUE TITLE
Possible to dynamically changing the bottom space of a MessageView?

### ISSUE THREAD

**Issue by micke-b** [SwiftKickMobile/SwiftMessages#160]
Hi,

Really nice work with this framework!

In my app I'm presenting a MessageView above a tabbar with presentationStyle set to .bottom. This MessageView will stay for a longer period of time in the app. But there are events in the app that will present a view above the tabbar that will also stay there for a while. When this happens I like to reposition my MessageView at a greater distance from the tabbar so it won't cover this other view.

So my issue is. After presenting a MessageView, how can I reposition it?

Thanks
Micke.

**Comment by wtmoose** [comment]
SwiftMessages doesn't provide explicit controls for adjusting the position.

In your case, I would probably display the message view in my own container view using `config.presentationContext = .view(:)` and manipulate the position of the container view as needed.

**Comment by micke-b** [comment]
Ahh, thank you for your reply. 

I ended up with such solution and then I override the point(inside.. func to pass along the touch events under the container. It works nicely.
