### ISSUE TITLE
[Feature Idea] Quarantine statusLine and other message

### ISSUE THREAD

**Issue by boboxiaodd** [SwiftKickMobile/SwiftMessages#161]
i love this respository
i use this show network status (statusLine with duration.forever)  but  in this time , i can't show other message.
i hope to quarantine statusLine and other message , After all, statusline have nothing to do with them

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages#message-queueing

**Comment by boboxiaodd** [comment]
thank you!
