### ISSUE TITLE
Tie message orientation to a view controller

### ISSUE THREAD

**Issue by johnqh** [SwiftKickMobile/SwiftMessages#164]
There is only one shouldAutoRotate in Config, which is used by WindowViewController. That is not enough control. I want the message to rotate with the top ViewController. Some of the VC supports portrait only but some supports all orientations.

Please add a parentViewController (weak) to the Config and pass all the orientation related functions to it.

**Comment by wtmoose** [comment]
Could you elaborate a bit on your use case. What does your full `config` look like?

**Comment by wtmoose** [comment]
What does your full `config` look like?

**Comment by johnqh** [comment]
self.configration = SwiftMessages.defaultConfig
                self.configration!.presentationStyle = .top
                self.configration!.duration = .forever
                self.configration!.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)

**Comment by wtmoose** [comment]
I added an optional `windowViewController` property to `SwiftMessages.Config`, which you can use to supply a custom subclass of `WindowViewController`. You'll need to pull down the head of master. Does this work for you?

**Comment by johnqh** [comment]
Yes. Tested and it works.

**Comment by wtmoose** [comment]
This was released in 4.1.2.
