### ISSUE TITLE
Unable to find a specification for `SwiftMessage`

### ISSUE THREAD

**Issue by waner11** [SwiftKickMobile/SwiftMessages#165]
The library previously worked correctly, I had a few days that I was not working on a project that I am developing, when I open it today to work it tells me that the SwiftMessage module is not found, when I try to install the library again or update it gives me that error.

**Comment by wtmoose** [comment]
There’s a problem with your environment. It doesn’t have anything to do with SwiftMessages, specifically. You might find someone to troubleshoot it for you on StackOverflow.
