### ISSUE TITLE
Close on tap not working?

### ISSUE THREAD

**Issue by ThreadPitt** [SwiftKickMobile/SwiftMessages#166]
Hi,

thanks for your control - works great!

I was wondering if it should or can close on tap?
I have interactiveHide = true  so the pan gesture works, but I'd like it to close when the user just taps on it. Is there a way to do it or did I do something wrong in my config:

```
        config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)
        config.duration = SwiftMessages.Duration.seconds(seconds: duration)
        
        config.interactiveHide = true 
```

Cheers!

**Comment by wtmoose** [comment]
If you're using `MessageView` class (or it's parent `BaseView`) have you tried the `tapHandler` property?
