### ISSUE TITLE
Calling SwiftMessages.show() from nested async completion blocks

### ISSUE THREAD

**Issue by annjawn** [SwiftKickMobile/SwiftMessages#169]
I am facing an issue where I need to show an alert when the user submits a task and the VC is dismissed and then eventually show a completion alert or error alert depending on whether the API call succeeded or failed.

I have the code something like this - 

```
self.dismiss(animated: true, completion: {
     SwiftMessages.show(config: self.topAlertConfig, view: self.progressAlert)
     self.someFunc(someData, completion: {
            //API call etc.
            //On Success
            SwiftMessages.show(config: self.topAlertConfig, view: self.completeAlert)
     })
}
```

In the case above, only the `self.progressAlert` shows and the completion alert `self.completeAlert` never shows up. I have also tried this below 

```
self.dismiss(animated: true, completion: {
     SwiftMessages.show(config: self.topAlertConfig, view: self.progressAlert)
     self.someFunc(someData, completion: {
            //API call etc.
            //On Success
            DispatchQueue.main.async {
                 SwiftMessages.hide()
                 SwiftMessages.show(config: self.topAlertConfig, view: self.completeAlert)
           }
     })
}
```
in this case, the progress alert hides rather quickly, which is fine and means that the `SwiftMessages.hide()` works but the completeAlert never shows up.

My config is this -

```
let topAlertConfig : SwiftMessages.Config = {
        var config = SwiftMessages.defaultConfig
        config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)
        config.interactiveHide = true
        config.presentationStyle = .top
        config.duration = .seconds(seconds: 2)
        return config
    }()
```

if i remove the first progressAlert and do this then the `completeAlert` shows up just fine, but I really also want to be able to show the `progressAlert`-

```
self.dismiss(animated: true, completion: {
     self.someFunc(someData, completion: {
            //API call etc.
            //On Success
            DispatchQueue.main.async {
                 SwiftMessages.show(config: self.topAlertConfig, view: self.completeAlert)
           }
     })
}
```
i've also tried `SwiftMessages.pauseBetweenMessages = 2` but it didn't work either. What am I missing here?

**Comment by wtmoose** [comment]
Guessing your messages have the same ID and the second one is being ignored as a dupe.

**Comment by annjawn** [comment]
Hmmm... i didn’t pay attention to message ids yet but I saw something about it in your documentation. Let me try to set the ids and test again. Thanks.

**Comment by annjawn** [comment]
Yes, message id was the issue. It's working perfectly. 👍

**Comment by wtmoose** [comment]
You should consider using the `indefinite` option for your progress alert. This will allow you to avoid displaying the alert for cases where the process completes quickly while ensuring that if the message is displayed, it is shown for a minimum amount of time.

````swift
case indefinite(delay: TimeInterval, minimum: TimeInterval)
````
