### ISSUE TITLE
xcode 8: value of type 'T'? has no member 'first'

### ISSUE THREAD

**Issue by myousufq** [SwiftKickMobile/SwiftMessages#17]
Hi,

I just upgraded xcode 7.3 to xcode 8.0. All sudden I am getting 

> value of type 'T'? has no member 'first' error in SwiftMessages.swift file (**internalViewFromNib** method). 

Can you please help me to fix this issue.

thanks

**Comment by wtmoose** [comment]
You'll need to use the swift3 branch until it's merged into master. See #1.
