### ISSUE TITLE
Message state

### ISSUE THREAD

**Issue by GiuCom** [SwiftKickMobile/SwiftMessages#171]
Hi,
I'm using SwiftMessage when developing an application but I can not intercept if a message is active or not.
With the command:

`SwiftMessage.show (config: config, view: view)`

in the configuration or entered the option
```
view.button? .isHidden = false
config.duration = .forever

```
the mesasage is displayed, how do I know if it is still active or if the user has already pressed the "Hide" button?
thanks and congratulations for the work done

**Comment by wtmoose** [comment]
Supply an event listener as outlined in the __Basics__ section of the [README](https://github.com/SwiftKickMobile/SwiftMessages/blob/master/README.md) and/or explicitly check current message as outlined in the __Retrieving Messages__ section.
