### ISSUE TITLE
Get custom element of custom view programmatically

### ISSUE THREAD

**Issue by simonhessner** [SwiftKickMobile/SwiftMessages#172]
Hi,

I copied a pre-defined xib file of SwiftMessages (messageView) and added a ProgressBar to it. I can successfully load the modified file and it is shown correctly, but I need a way to get access to the progress bar in order to change its progress value.

As I did only change the xib file and no ViewController, I don't know how to access the ProgressBar object. Is there an example how to do this? Do I also have to copy the corresponding ViewController and add an outlet to the ProgressBar to it?

**Comment by wtmoose** [comment]
Use a subclass of `MessageView` with your customized nib file and add outlets as needed.

**Comment by simonhessner** [comment]
Okay, that was easier than I was afraid it would be. It works, thanks!
