### ISSUE TITLE
StatusBar style

### ISSUE THREAD

**Issue by annjawn** [SwiftKickMobile/SwiftMessages#175]
I have a Service class which does service/API calls in the background queue which can be invoked/used from several view controllers. This service class uses SwiftMessages to show the API response alerts to the user.The `presentationContext` i used is `UIWindowLevelStatusBar` (this is one of the major reasons I am using this library, i.e. being able to alert users at window level from backGround threads and a queuing mechanism). 

Some of the `ViewControllers` in the app has `preferedStatusBarStyle` set to `.lightContent` (i.e. the navigation bar is darker in color or has image in the background). When a SwiftMessage shows up on such a VC with `.lightContent`, it temporarily overrides the statusbar style back to `.default` (black). In a normal scenario while presenting a VC modally I would use the code below to inherit the statusbar appearance-

```
VC.modalPresentationStyle = .custom
VC.modalPresentationCapturesStatusBarAppearance = true
```

The SwiftMessage configuration declaration is kind of global in my app and I don't want to be creating separate configs for each and every view controller and so on. And I don't want to hard code `config.preferredStatusBarStyle` for SwiftMessages to be `.lightContent` globally either, but instead want the alerts to inherit the `preferredStatusBarStyle` from over whatever VC it shows up. Is there a way to achieve it? I can't seem to find one.

**Comment by wtmoose** [comment]
https://stackoverflow.com/questions/19487818/getting-current-ios-7-statusbar-style

**Comment by annjawn** [comment]
Thanks. I already know that information, based on which i tried to set the config.preferedStatusBarStyle before `show()`, but it didn't work.

**Comment by wtmoose** [comment]
Are you saying the `config.preferredStatusBarStyle` setting doesn't work?

**Comment by annjawn** [comment]
Well it works. But here is what I am facing. Below is roughly the program flow-

```
class MyBackGroundService{
     var config = SwiftMessages Config Declaration()
     var statusBarStyleCurrent: UIStatusBarStyle? 

     func doSomething(){
         statusBarStyleCurrent = UIApplication.shared.keyWindow?.rootViewController?
     .childViewControllerForStatusBarStyle.preferredStatusBarStyle
         if someCondition {
            config. preferredStatusBarStyle = statusBarStyleCurrent //<-- This doesn't seem to change anything
             show message with config
         }
     }
}
```

As you can see that I assign the `config.preferredStatusBarStyle` to the `UIApplication.shared.keyWindow?.rootViewController?.childViewControllerForStatusBarStyle.preferredStatusBarStyle` just before the `show()` method, but that doesn't change the status bar style. Also, the methods from `MyBackGroundService` class are almost always invoked in the `background` queue since it makes service calls and maintains the app's Cache system. I use SwiftMessages to show when a backGround operation is complete/error/pending no matter which view controller the user is currently. Everything is working as expected, except for the statusbarstyle issue.

**Comment by wtmoose** [comment]
Could you try subclassing `WindowViewController` and overriding the `preferedStatusBarStyle` with your custom logic? See `SwiftMessages.Config.windowViewController` property.

**Comment by annjawn** [comment]
Ah! gotcha... let me give that a try...

**Comment by annjawn** [comment]
unfortunately, I am struggling to understand the usage of `WindowViewController`. I looked at your demo but couldn't find any either. 🙁

**Comment by ashish-naik** [comment]
> Are you saying the `config.preferredStatusBarStyle` setting doesn't work?

worked for me. Thanks.
