### ISSUE TITLE
[Feature Request] add support for prefersStatusBarHidden

### ISSUE THREAD

**Issue by TSCombine** [SwiftKickMobile/SwiftMessages#176]
In WindowViewController it would be nice if you would add support for prefersStatusBarHidden, something like

override var prefersStatusBarHidden: Bool {
        return config. prefersStatusBarHidden ?? super. prefersStatusBarHidden
    }

**Comment by wtmoose** [comment]
You can supply your own custom subclass of `WindowViewController` that does whatever you like: #164

**Comment by wtmoose** [comment]
Assuming you're good now. Closing.

**Comment by TSCombine** [comment]
Hi yes, it worked, thank you and sorry for not responding, I was in a hurry trying out the solution :)

**Comment by wtmoose** [comment]
No problem. Good to hear it worked.
