### ISSUE TITLE
Can't adjust top banner to be below toolbar in custom ViewController

### ISSUE THREAD

**Issue by wildthink** [SwiftKickMobile/SwiftMessages#177]
How can I configure the banner to appear below my toolbar in my Custom View Controller?
There is not configuration nor API/protocol to effect this.

It appears that `sm_selectPresentationContextTopDown` would be the place to inject some check.
How might I go about this?

**Comment by wtmoose** [comment]
You can modify the layout of the banner by supplying a custom view and/or nib file or by displaying the banner in a container view using the `presentationContext = .view(...)` configuration option.

**Comment by wildthink** [comment]
Ah, so did you think of everything. :-)
I'm a bit confused why `presentationContext = .viewController(myController)` didn't find the right view but `presentationContext = .view(myController.view)` did the trick.

Thanks for the rapid response. Where do I send the beer?

**Comment by wtmoose** [comment]
From the code:

````swift
/**
 Displays the message view under navigation bars and tab bars if an
 appropriate one is found using the given view controller as a starting
 point and searching up the parent view controller chain. Otherwise, it
 is displayed in the given view controller's view. This option can be used
 for targeted placement in a view controller heirarchy.
*/
case viewController(_: UIViewController)
````
