### ISSUE TITLE
Center PresentationStyle

### ISSUE THREAD

**Issue by shukaka** [SwiftKickMobile/SwiftMessages#18]
i found there is no Center PresentationStyle, based on what is considered?

**Comment by wtmoose** [comment]
No plan to add this at the moment, but something I'm considering.

**Comment by bartleby** [comment]
+ need center!

**Comment by wtmoose** [comment]
Anyone interested in centered messages, please check out `3.4.0-beta` and post your feedback here. Here are the release notes:

* Added `.center` presentation style with a physics-based dismissal gesture.
* Added `.custom(animator:)` presentation style, where you provide an instance of the `Animator` protocol. The `TopBottomAnimation` and `CenterAnimation` animations both implement `Animator` and may be subclassed (configuration options will be added in a future release). `PhysicsPanHandler` class to provide a physics-based dismissal gesture.
* Added `.centered` message view layout with elements centered and arranged vertically.
* Added `configureBackgroundView(width:)` and `configureBackgroundView(sideMargin:)` convenience methods to `MessageView`.

**Comment by bartleby** [comment]
wow! Thank you so much! I'll try it later

**Comment by wtmoose** [comment]
See 3.4.0
