### ISSUE TITLE
To change the `SwiftMessages` class name to another

### ISSUE THREAD

**Issue by Desgard** [SwiftKickMobile/SwiftMessages#180]
I wanted to write a factory function to config the config of `SwiftMessagesView`, and I wanted to set the `SwiftMessages.Theme` is one of the params for the function:

```Swift
// my function
private class func creatStatusLine(title: String, iconStyle: SwiftMessages.Theme)

// In SwiftMessages - Theme.swift
public enum Theme {
    case info
    case success
    case warning
    case error
}
```

But in the **SwiftMessages**, there is a open class which is named `SwiftMessages`. So the param `iconStyle: SwiftMessages.Theme` this syntax, the Xcode will find the `SwiftMessages` class in default, but not means the **SwiftMessages namespace**. 

😭

**Comment by wtmoose** [comment]
Its a known issue. I'll rename the `SwiftMessages` class at some point when I'm ready to introduce breaking changes. Why do you need to qualify `Theme` with `SwiftMessages` though? You should be able to write:

````swift
private class func creatStatusLine(title: String, iconStyle: Theme)
````

unless there's a conflict with another `Theme` type in your namespace.

**Comment by Desgard** [comment]
Yes, there is another `Theme` class in my app namespace. 
And now, I use many `if else` to pass parameters. Wait for updating...
Thanks! 😄

**Comment by wtmoose** [comment]
No plan to make this breaking change in the near future. One way you can work around the issue is to wrap it like this:

````swift
enum SMTheme {
    case info
    case success
    case warning
    case error
}

extension MessageView {
    func configureTheme(_ theme: SMTheme) {
        switch theme {
        case .info: configureTheme(.info)
        case .success: configureTheme(.success)
        case .warning: configureTheme(.warning)
        case .error: configureTheme(.error)
        }
    }
}

class MyClass {
    private class func creatStatusLine(title: String, iconStyle: SMTheme) {
        let view = MessageView.viewFromNib(layout: .statusLine)
        view.configureTheme(.info)
    }
}
````

**Comment by annca** [comment]
This issue can be solved by doing an import statement like this:

`import enum SwiftMessages.Theme`
