### ISSUE TITLE
How to make Swift Message appear globally in all screens

### ISSUE THREAD

**Issue by Karthiccc** [SwiftKickMobile/SwiftMessages#187]
I want to display Swift message with same content at bottom of all screens and handle tap of that Swift message. how do I make the presentation context global.

**Comment by wtmoose** [comment]
Sorry, but I don't understand the question. Can you show the code that you've done and describe the specific problem that you ran into?

**Comment by Karthiccc** [comment]
`
import UIKit
import SwiftMessages

class CustomView: BaseView {
    
    //MARK: Outlets
    @IBOutlet weak var message: UILabel!
    @IBOutlet weak var icon: UIImageView!
    
    
    
    override func awakeFromNib() {
    }

}
`
<img width="466" alt="screen shot 2018-05-18 at 11 29 30 am" src="https://user-images.githubusercontent.com/24898935/40243847-4852d408-5a8f-11e8-9349-c5a8d4bb9e18.png">

` var successConfig = SwiftMessages.defaultConfig
   let customView: CustomView = try! SwiftMessages.viewFromNib()
  successConfig.presentationStyle = .bottom
  successConfig.duration = .forever
  successConfig.presentationContext = .window(windowLevel: UIWindowLevelNormal)    
  SwiftMessages.show(config: successConfig, view: customView)
`


I can able to show the Swift Message CustomView in all screens .But How do I handle message tap for that?

**Comment by wtmoose** [comment]
Well, it's your custom view, so you can do anything you want with it. But given that it's a subclass of `BaseView`, there is already a `tapHandler` property there for you.

**Comment by Karthiccc** [comment]
yeah I tried using taphandler but I couldn't write multiple lines of code inside that. Sorry am new to swift here.
       snackbarView.tapHandler = {
            _ in SwiftMessages.hide()
        }
I can just hide. am trying to write my own functionality other than hide.
