### ISSUE TITLE
Multiline label for layout .statusLine

### ISSUE THREAD

**Issue by arturdev** [SwiftKickMobile/SwiftMessages#193]
Is it possible to have a multiline message (with dynamic height)? 
Currently, when the body is too long, it truncates with ellipses.

Thanks

**Comment by wtmoose** [comment]
All of the bundled layouts except `statusLine` are configured for dynamic height, multi-line body labels. If you're not getting the layout you need, all of the UI elements are exposed via public properties, e.g. `bodyLabel` and you are free to modify in whatever way suits your needs. You can also copy the nib files into your project and modify them. Or supply your own nib files and/or view.

**Comment by arturdev** [comment]
Ok, I copied "StatusLine.xib" to my bundle and modified to my needs.

**Comment by wtmoose** [comment]
Cool. The `statusLine` label has a hard-coded 20pt height because the point is to match the height of the status bar.

**Comment by muhammedgul** [comment]
You can do

let view = MessageView.viewFromNib(layout: .statusLine)
view.bodyLabel?.numberOfLines = 0
view.bodyLabel?.widthConstraint?.isActive = false
