### ISSUE TITLE
Scrollview not working

### ISSUE THREAD

**Issue by vdiamantGR** [SwiftKickMobile/SwiftMessages#196]
I have inside the view that I present with the SwiftMessages.show a scroll view
Tap isn't recognised neither on didselect something neither on scroll, how can I fix this?

**Comment by wtmoose** [comment]
Did you figure this out? I was on vacation and didn't have a chance to look at it.

**Comment by vdiamantGR** [comment]
No I didn't .. I tried  interactiveHide = false didn't work, if you know how to make it work with just a scrollview or a collection view it's the same for me.. the issue is that I can't Scroll..

**Comment by wtmoose** [comment]
Try running the Demo app in the branch `work/viewControllers` and select the "View Controllers" row. You'll see that SwiftMessages is presenting a navigation controller with a child table view. Scrolling and interactions work just fine.

Can you attach a test app where it doesn't work? This will help me get to it quicker.
