### ISSUE TITLE
Haptic Feedback

### ISSUE THREAD

**Issue by AbelToy** [SwiftKickMobile/SwiftMessages#207]
Maybe it would be a good idea to add some optional haptic feedback to certain alerts.

According to the [human guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/feedback/), there's three levels of feedback for notifications: success, warning and error.

At the moment it can be added using event listeners, but adding default support for it on specific configurations would be helpful

**Comment by AlbertoSamele** [comment]
Will take care of this 👌👌

**Comment by mikestalker** [comment]
Hello. Any chance to get this PR merged?

**Comment by AlbertoSamele** [comment]
@mikestalker it's been a long time since I made the PR so the branch eventually diverged, I will fix the conflicts this weekend so if it doesn't get merged and you really need my changes, you can just use my fork instead

**Comment by mikestalker** [comment]
Thx @AlbertoSamele. Just switched from NotificationBannerSwift to SwiftMessages and wanted get this haptic effect as it was in old library here as well. Not critical but nice to have for consistency.

**Comment by AlbertoSamele** [comment]
Conflicts solved, my branch is now up to stream if you still want to use it @mikestalker

**Comment by mikestalker** [comment]
Thank you @AlbertoSamele . Hopefully your PR will be merged and released soon. Any chanse for that @wtmoose ?

**Comment by mikestalker** [comment]
@wtmoose can you please merge imrovements from @AlbertoSamele please?

**Comment by mikestalker** [comment]
@wtmoose any chanse to get haptic feedback PR merged?

**Comment by wtmoose** [comment]
Yeah. There were some problematic areas of the PR that prevented me from merging it. I went ahead and made the required updates. You can try it on the head of `master`

**Comment by mikestalker** [comment]
Thanks @AlbertoSamele , thanks @wtmoose 
Works like a charm. Waiting for release.
