### ISSUE TITLE
Statusbar height wrong on iOS 10.x after rotation

### ISSUE THREAD

**Issue by leetal** [SwiftKickMobile/SwiftMessages#208]
It seems that on iOS 10.3 the height of the statusbar is wrong after rotate (or dragging CC and releasing it), when presented in a window context on normal level,

I'll supply a PR that fixes the issue as well.

![img_0106](https://user-images.githubusercontent.com/1221839/44084716-c24eead6-9fb7-11e8-987a-b4265b89c31d.png)

**Comment by wtmoose** [comment]
Hi. Thanks for bringing this up. There's a rather large update coming on the `work/viewControllers` branch and I've made changes to how those adjustments work. Can you reproduce on that branch (I couldn't)?

**Comment by leetal** [comment]
I'll check tomorrow!

**Comment by leetal** [comment]
I'll double-checked the work branch and you are 100% correct! The error is not present on that branch anymore 👍 

Should i close the PR or do you plan on making a last release for compatibility?

**Comment by wtmoose** [comment]
I'm about ready to release the work branch, so we can close the PR.
