### ISSUE TITLE
NSInternalInconsistencyException Crash

### ISSUE THREAD

**Issue by hummer330** [SwiftKickMobile/SwiftMessages#210]
Hi there,

We have seeing multiple crashes in our app, Could you help us debug the issue?
Thanks a lot!

The stack track listed below: 
> Fatal Exception: NSInternalInconsistencyException
> 0  CoreFoundation                 0x1830f6d8c __exceptionPreprocess
> 1  libobjc.A.dylib                0x1822b05ec objc_exception_throw
> 2  CoreFoundation                 0x1830f6bf8 +[NSException raise:format:]
> 3  Foundation                     0x183ae6fa0 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
> 4  UIKit                          0x18d825f78 __120-[UIView(UIConstraintBasedLayout) _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:]_block_invoke_2
> 5  UIKit                          0x18cd169ec -[UIView(UIConstraintBasedLayout) _layoutEngine_didAddLayoutConstraint:roundingAdjustment:mutuallyExclusiveConstraints:]
> 6  UIKit                          0x18cd16804 -[UIView(UIConstraintBasedLayout) _tryToAddConstraintWithoutUpdatingConstraintsArray:roundingAdjustment:mutuallyExclusiveConstraints:]
> 7  UIKit                          0x18d005254 __50-[UIView(UIConstraintBasedLayout) addConstraints:]_block_invoke
> 8  Foundation                     0x183a45500 -[NSISEngine withBehaviors:performModifications:]
> 9  UIKit                          0x18cdbb0cc -[UIView(UIConstraintBasedLayout) addConstraints:]
> 10 SwiftMessages                  0x1013f0d8c specialized Presenter.(install() -> ()).(installMaskingView #1)(containerView : UIView) -> () (Presenter.swift:344)
> 11 SwiftMessages                  0x1013ee5b0 Presenter.install() -> () (Presenter.swift:39)
> 12 SwiftMessages                  0x1013f17c4 specialized Presenter.show(completion : (Bool) -> ()) throws -> () (Presenter.swift:116)
> 13 SwiftMessages                  0x1013f4398 SwiftMessages.(dequeueNext() -> ()).(closure #1) (SwiftMessages.swift:539)
> 14 SwiftMessages                  0x101401068 _T0Ieg_IeyB_TR (TopBottomAnimation.swift)
> 15 libdispatch.dylib              0x1829e8aa0 _dispatch_call_block_and_release
> 16 libdispatch.dylib              0x1829e8a60 _dispatch_client_callout
> 17 libdispatch.dylib              0x182a29d80 _dispatch_main_queue_callback_4CF$VARIANT$armv81
> 18 CoreFoundation                 0x18309f070 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> 19 CoreFoundation                 0x18309cbc8 __CFRunLoopRun
> 20 CoreFoundation                 0x182fbcda8 CFRunLoopRunSpecific
> 21 GraphicsServices               0x184fa2020 GSEventRunModal
> 22 UIKit                          0x18cfdc758 UIApplicationMain
> 23 SomeApp                         0x1005e8eb8 main (main.m:20)
> 24 libdyld.dylib                  0x182a4dfc0 start

Pod Version is 4.1.4
Xcode 9.4.1, Swift 4.1

**Comment by wtmoose** [comment]
Not much I can do with this if you don't share the code.

**Comment by wtmoose** [comment]
No reply. Closing.
