### ISSUE TITLE
App crash during swipe gesture with a subclass of MessageView

### ISSUE THREAD

**Issue by adrgrondin** [SwiftKickMobile/SwiftMessages#215]
I am subclassing MessageView and loading my custom view from a nib file. The view is displayed correctly however when swiping inside the view the app crash.
The custom view simply have a background view and a button, both are outlets. 
I have also overrided point(inside point: CGPoint, with event: UIEvent?) so I can tap the button inside my background view.

This is my SwiftMessages configuration:

```swift
var config = SwiftMessages.defaultConfig
config.presentationStyle = .center
config.duration = .forever
config.dimMode = .blur(style: .dark, alpha: 1, interactive: true)
config.presentationContext  = .window(windowLevel: UIWindowLevelStatusBar)
```

Am I doing something wrong maybe?

Here are the console logs:

```2018-08-31 11:29:02.898320+0300 App[10310:468607] *** Assertion failure in -[UIDynamicAnimator _registerBodyForItem:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.54.4/UIDynamicAnimator.m:873
2018-08-31 11:29:02.913121+0300 App[10310:468607] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid size {375, 0} for item <App.CustomView: 0x7f948344e110; frame = (0 406; 375 0); autoresize = RM+BM; gestureRecognizers = <NSArray: 0x6000004566e0>; layer = <CALayer: 0x60000023bba0>> in Dynamics'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001114251e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x0000000110990031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011142a472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010ecdb652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x00000001128fd2f9 -[UIDynamicAnimator _registerBodyForItem:] + 1787
	5   UIKit                               0x0000000111e78eda -[UIDynamicItemBehavior _reevaluate:] + 365
	6   UIKit                               0x0000000111e78fc8 -[UIDynamicItemBehavior _associate] + 59
	7   UIKit                               0x00000001128f9cac -[UIDynamicAnimator _registerBehavior:] + 315
	8   UIKit                               0x00000001128f9a5f -[UIDynamicAnimator addBehavior:] + 118
	9   SwiftMessages                       0x000000010e800245 _T013SwiftMessages17PhysicsPanHandlerC5StateCAESo6UIViewC11messageView_AG09containerI0tcfc + 1077
	10  SwiftMessages                       0x000000010e7ffdfd _T013SwiftMessages17PhysicsPanHandlerC5StateCAESo6UIViewC11messageView_AG09containerI0tcfC + 61
	11  SwiftMessages                       0x000000010e8028bb _T013SwiftMessages17PhysicsPanHandlerC3panySo22UIPanGestureRecognizerCF + 987
	12  SwiftMessages                       0x000000010e804def _T013SwiftMessages17PhysicsPanHandlerC3panySo22UIPanGestureRecognizerCFTo + 63
	13  UIKit                               0x000000011212154f -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	14  UIKit                               0x000000011212a324 _UIGestureRecognizerSendTargetActions + 109
	15  UIKit                               0x0000000112127b6c _UIGestureRecognizerSendActions + 307
	16  UIKit                               0x0000000112126dc0 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 859
	17  UIKit                               0x000000011210be24 _UIGestureEnvironmentUpdate + 1329
	18  UIKit                               0x000000011210b8a7 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
	19  UIKit                               0x000000011210a9a9 -[UIGestureEnvironment _updateGesturesForEvent:window:] + 281
	20  UIKit                               0x0000000111ba07ab -[UIWindow sendEvent:] + 4064
	21  UIKit                               0x0000000111b44310 -[UIApplication sendEvent:] + 352
	22  UIKit                               0x00000001124856af __dispatchPreprocessedEventFromEventQueue + 2796
	23  UIKit                               0x00000001124882c4 __handleEventQueueInternal + 5949
	24  CoreFoundation                      0x00000001113c7bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x00000001113ac4af __CFRunLoopDoSources0 + 271
	26  CoreFoundation                      0x00000001113aba6f __CFRunLoopRun + 1263
	27  CoreFoundation                      0x00000001113ab30b CFRunLoopRunSpecific + 635
	28  GraphicsServices                    0x0000000115dcca73 GSEventRunModal + 62
	29  UIKit                               0x0000000111b29057 UIApplicationMain + 159
	30  App                                 0x000000010b24a627 main + 55
	31  libdyld.dylib                       0x00000001169eb955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException```

**Comment by wtmoose** [comment]
Can you attach your custom view and nib file so I can test it?

**Comment by wtmoose** [comment]
`MessageView` already has a `backgroundView` property and a `button` property. The `point(inside:, with:)` is already scoped down to the background view's frame. So I'm not clear what you're trying to accomplish in your subclass.

**Comment by wtmoose** [comment]
The error message is saying that your `CustomView` has zero height. So I'd guess that you haven't properly constrained your view's content vertically.

>Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid size {375, 0} for item <App.CustomView: 0x7f948344e110; frame = (0 406; 375 0); autoresize = RM+BM; gestureRecognizers = <NSArray: 0x6000004566e0>; layer = <CALayer: 0x60000023bba0>> in Dynamics'

**Comment by wtmoose** [comment]
This is a good question to post on StackOverflow because it seem that you could use some help with Auto Layout. It isn't so much a SwiftMessages question.

Have you taken a look at the `MessageView.Layout.centeredView`? It seems you could use that as a starting point and go in one of two directions:

1. Use `MessageView`. No need to subclass. Set `title`, `iconImageView`, and `iconLabel` to hidden.
2. Use `InAppPurchaseView`. Copy `CenteredView.nib` and remove the title and icon. Set `InAppPurchaseView` as the top-level view's class.

**Comment by adrgrondin** [comment]
Thank you. I thought it was related with SwiftMessages because I followed the "Extending" part and get this error with a very basic setup. I need a custom look for the button hence the subclass. I fixed the crash by looking at how `CenteredView.nib` is made.

**Comment by wtmoose** [comment]
Glad you fixed it. The error is because your view was zero height because you didn't set up proper Auto Layout constraints. How to use Auto Layout is beyond the scope of what I can document in the readme, but I'll look into adding some comments about properly constraining views in the vertical direction.

**Comment by wtmoose** [comment]
Also, why do you need a subclass to customize the look of your button? You can modify the button's layout in the nib file and you already have access to the button's outlet if you need to customize its properties.

**Comment by adrgrondin** [comment]
I don't want to override the files of SwiftMessages because I am using CocoaPods and I prefer to use IB. Thank you for the help!

**Comment by wtmoose** [comment]
SwiftMessages looks in your project for nib files first before looking in the SwiftMessages framework itself, specifically so you can copy the nib files into your project and modify them.

**Comment by adrgrondin** [comment]
Thank you for your help, I will do this!
