### ISSUE TITLE
Allow orientation to be passed in as a config parameter

### ISSUE THREAD

**Issue by dsowsy** [SwiftKickMobile/SwiftMessages#217]
Apple has made a proper mess of handling device orientation and there's a lot of evidence of many difference approaches people have come up with over the years in an attempt to work around dealing with fixed and rotatable VC's, and your implementation depends on the app.statusBarOrientation which is deprecated (Apple giveth, Apple taketh away), viewWillTransition which sorta works on size classes, and the KVO and properties approaches.

The particular scenarios I'm trying to use your control is on an AVCaptureSession and on a SceneView scene, where autorotation of their parent views and resize is glitchy relying on the built in mechanism. I have considered just taking the view and manually doing this by myself, but that seems even more hackish, and wouldn't benefit anyone else -- it would make more sense in the config and using SwiftMessages.show method.

I'd like to suggest adding a config parameter of .orientation. If I'm locked in .landscapeLeft, and I turn the device to one of the two portrait modes, it would make sense to be able to set .orientation value on the SwiftMessages config, which I as a callee could derive from viewWillTransition, CoreMotion, or some other future-looking mechanism.

**Comment by wtmoose** [comment]
SwiftMessages only looks at the orientation on iOS 10 and below to make adjustments when displayed below the status bar. Given that this has never come up before, I'm leaning toward a workaround on your end rather than adding an API in support of old platforms.

If you detect a scenario where the message view is going to appear below the status bar, can you just add 20pt?

````swift
messageView.topLayoutMarginAddition += 20
````

**Comment by dsowsy** [comment]
Ah, I'm on iOS 11 and 12 betas. I see what you're getting at but the problem isn't the status bar itself, but the orientation in which the messageView shows up is just wrong for a locked orientation. I have a workaround but its a bit hacky, I'l see if I can come up with a clear example. Thanks!

**Comment by wtmoose** [comment]
Did you delete a message? I thought I got your issue is after reading the message, but not sure now.

**Comment by dsowsy** [comment]
I've found a workaround for the orientation with autolayout, however the statusbar is in fact a problem, I looked after you made mention of it. Would it be a good idea to add a config option that sets the value of the prefersStatusBarHidden in SwiftMessages.WindowViewController?

**Comment by wtmoose** [comment]
See #164
