### ISSUE TITLE
Several Safe Area related warnings in MarginAdjustable+Animation.swift

### ISSUE THREAD

**Issue by edwardmp** [SwiftKickMobile/SwiftMessages#218]
Hi,

Thanks for creating this!

The latest release triggers a few Xcode warnings in my project in the file `MarginAdjustable+Animation.swift`:
```
SwiftMessages/MarginAdjustable+Animation.swift:16:17: 'safeAreaTopOffset' is deprecated on iOS: Use the `topLayoutMarginAddition` instead.
SwiftMessages/MarginAdjustable+Animation.swift:16:43: 'safeAreaBottomOffset' is deprecated on iOS: Use the `bottomLayoutMarginAddition` instead.
SwiftMessages/MarginAdjustable+Animation.swift:16:72: 'statusBarOffset' is deprecated on iOS: Now handled by `collapseLayoutMarginAdditions`
SwiftMessages/MarginAdjustable+Animation.swift:74:24: 'safeAreaTopOffset' is deprecated on iOS: Use the `topLayoutMarginAddition` instead.
SwiftMessages/MarginAdjustable+Animation.swift:78:28: 'statusBarOffset' is deprecated on iOS: Now handled by `collapseLayoutMarginAdditions`
SwiftMessages/MarginAdjustable+Animation.swift:99:27: 'safeAreaBottomOffset' is deprecated on iOS: Use the `bottomLayoutMarginAddition` instead.
```
The deprecation warnings are coming from elsewhere in SwiftMessages. Is this intentional or..?

**Comment by wtmoose** [comment]
SwiftMessages needs to maintain backward compatibility with deprecated APIs for a period of time. Unfortunately, Swift doesn't provide a mechanism to mute warnings, so I don't think anything can be done about it.

**Comment by edwardmp** [comment]
@wtmoose 

Okay that makes sense. But why can't the use of `safeAreaTopOffset/safeAreaTopOffset` just be replaced by `topLayoutMarginAddition/bottomLayoutMarginAddition` in this case?

**Comment by wtmoose** [comment]
They're public APIs, so the normal thing to do is to deprecate them for a period of time before removing them in order to give people time to migrate.

**Comment by edwardmp** [comment]
@wtmoose 
I understand that generally, but not in this case. Here it's an implementation detail that can easily be changed? Or am I missing something? It's not like a method name or something that's really part of the public API.

**Comment by edwardmp** [comment]
@wtmoose 
Yes, but that does only apply if one uses `safeAreaTopOffset` in their own project directly, right? I'm now referring solely to the use in `MarginAdjustable+Animation`, which seems avoidable.

**Comment by wtmoose** [comment]
I see how to maintain backward compatibility without reading the values.

**Comment by ThreadPitt** [comment]
When  using Cocoapods, you can suppress the warning in the pod file for this pod

**Comment by giofid** [comment]
@wtmoose maybe you can use 
```
#if swift(>=4.2)
    // use topLayoutMarginAddition/bottomLayoutMarginAddition/etc.
#else
    // use safeAreaTopOffset/safeAreaTopOffset/etc.
 #endif
```
to maintain backward compatibility with swift version less than 4.2.

**Comment by pahnev** [comment]
@wtmoose, I understand wanting to keep it backwards compatible, but isn't that what the versions are for? E.g. the 6.0 release is already not compatible with 5.0 code, which is also supported with the [Cocopods version syntax](https://guides.cocoapods.org/using/the-podfile.html) and users of your library will not get updated to 6.0, unless they explicitly want to. 
```
'~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
'~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
'~> 0' Version 0 and higher, this is basically the same as not having it.
```

So why not just remove this deprecated code and release a new major version?

**Comment by kajensen** [comment]
Would it be possible to fix these warnings along with a Swift 5.0 release? :)

**Comment by kajensen** [comment]
I just updated the swift5 branch to remove the deprecated method _usage_/silence Xcode 10.2 warnings. I won't submit a pull request as the author is opposed to breaking deprecations, per this thread.

https://github.com/kajensen/SwiftMessages/tree/work/swift5

**Comment by stanmots** [comment]
Very strange issue. 

The author added deprecation messages [here](https://github.com/SwiftKickMobile/SwiftMessages/blob/6b348edcc4b1a167f2961f3f921d274792272c77/SwiftMessages/MarginAdjustable.swift#L43-L50). Yes, this is public protocol which means Xcode should display warnings only if **we** (consumers of this library) are calling the deprecated functions or incorporating the deprecated types in our apps. 

But why on earth the author is [using](https://github.com/SwiftKickMobile/SwiftMessages/blob/6b348edcc4b1a167f2961f3f921d274792272c77/SwiftMessages/MarginAdjustable%2BAnimation.swift#L15) the code that he marked _himself_ as deprecated inside this library? Can somebody explain me how is this related to backwards compatibility? Because it's really confusing for me.

**Comment by wtmoose** [comment]
@stanmots the library can’t maintain backward compatibility without reading the deprecated property. Deprecated functionality is still supposed to work, right?

**Comment by wtmoose** [comment]
I’ve assumed that anyone coming on here to complain about the deprecation warnings has looked at the comments in `MarginAdjustable` enough to be aware that the properties in question are settings that affect how SwiftMessages manages a view’s layout margins. Settings have to be read, of course, to achieve the promised result.

But sleep well tonight, folks. The deprecated properties are going to be removed in the next release!

**Comment by stanmots** [comment]
> But sleep well tonight, folks. The deprecated properties are going to be removed in the next release!
Thanks, these are fantastic news. Can't believe Gods heard my prayers 😇

**Comment by wtmoose** [comment]
Deprecated APIs removed in 7.0.0
