### ISSUE TITLE
Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "(null)"

### ISSUE THREAD

**Issue by MVakas** [SwiftKickMobile/SwiftMessages#22]
I’m getting this error on Xcode 8 and Swift 2.3
In my pod file I have 
pod 'SwiftMessages', '~> 2.0.0'
<img width="907" alt="screen shot 2016-09-28 at 9 38 37 am" src="https://cloud.githubusercontent.com/assets/7447077/18900888/64c5f02c-855f-11e6-85e0-b2d20448c7f5.png">

**Comment by wtmoose** [comment]
Are you on a jail broken device? If so, see #9. Otherwise, can you provide some context (e.g.  Show some code, etc.)? This isn't normally an issue, so I need more to go on.

**Comment by MVakas** [comment]
No jailbroken. 

Trying the following code taken from your demo project.

`        let warning = MessageView.viewFromNib(layout: .CardView)
        warning.configureTheme(.Warning)
        warning.configureDropShadow()
        
        let iconText = ["🤔", "😳", "🙄", "😶"].sm_random()!
        warning.configureContent(title: "Warning", body: "Consider yourself warned.", iconText: iconText)
        warning.button?.hidden = true
        var warningConfig = SwiftMessages.Config()
        warningConfig.presentationContext = .Window(windowLevel: UIWindowLevelStatusBar)
        
        SwiftMessages.show(config: warningConfig, view: warning)`

**Comment by MVakas** [comment]
Tried with Swift 3.0 and getting the same error when I try to show a message on Xcode 8.

**Comment by ralphm18** [comment]
I'm having the same problem... what can we do to fix it?

**Comment by wtmoose** [comment]
Make sure you're using CocoaPods 1.1.0.

Can you try the attached project? I dropped your code into a fresh Swift 2.3 project and it worked. If you're still having trouble, can you send me a test project?

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/498629/SwiftMessagesTest.zip)

**Comment by MVakas** [comment]
Hey thanks for the help.  **I wasn’t on CocoaPods 1.1.0**
You can close the issue.

**Comment by wtmoose** [comment]
No problem. Glad you got it working.
