### ISSUE TITLE
Present SwiftMessages above navigationBar without using UIWindow 

### ISSUE THREAD

**Issue by 0xacdc** [SwiftKickMobile/SwiftMessages#220]
Is it possible to use config.presentationContext as UIView or UIViewController and present message above the navigationBar ?

**Comment by wtmoose** [comment]
I think `.view()` should work using the navigation view controller's view. But I haven't tried it.

**Comment by 0xacdc** [comment]
config.presentationContext = .view(vc.navigationController!.navigationBar)
 config.presentationContext = .view(vc.navigationController!.view)

both cases doesn't work, other ideas ?

**Comment by wtmoose** [comment]
Hmm. That's not nice. Thanks for investigating.
