### ISSUE TITLE
MarginAdjustable+Animation.swift:16:17: 'safeAreaTopOffset' is deprecated on iOS: Use the `topLayoutMarginAddition` instead.

### ISSUE THREAD

**Issue by Michele404** [SwiftKickMobile/SwiftMessages#222]
MarginAdjustable+Animation.swift:16:17: 'safeAreaTopOffset' is deprecated on iOS: Use the `topLayoutMarginAddition` instead.

**Comment by wtmoose** [comment]
Do you have a question?

**Comment by Michele404** [comment]
The question is the tite

**Comment by wtmoose** [comment]
#218

**Comment by wtmoose** [comment]
Closing this as a dupe. Feel free to comment on the original.
