### ISSUE TITLE
Message order

### ISSUE THREAD

**Issue by barisatamer** [SwiftKickMobile/SwiftMessages#224]
Hi,

Thank you for creating this amazing library!

In the current implementation, the one is waiting for another.

For our needs, we need to reverse the order. That way, a **new** message will always be shown, without waiting for the queue.

Do you have any plans for that kind of feature?
If we implement our custom solution, would you think merging it?

**Comment by wtmoose** [comment]
Can you just call `SwiftMessages.hideAll()` before showing the next message?

**Comment by wtmoose** [comment]
OK gotcha. I'm pretty swamped, so if you want to do a PR, I'll take a look. My first inclination is to add an enum on `SwiftMessages`:

````swift
enum Queuing {
    case firstInFirstOut
    case lastInFirstOut
}

open var queuing = firstInFirstOut
````

But open to other ideas.

**Comment by wtmoose** [comment]
A few weeks ago, you mentioned a possible PR for this feature request. Should I keep this one open?
