### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by Michele404** [SwiftKickMobile/SwiftMessages#225]
Update to 4.2 please

**Comment by wtmoose** [comment]
You can use the `work/swift4.2` branch

**Comment by rafsouzap** [comment]
@wtmoose do you have any plans to release this fix?

**Comment by wtmoose** [comment]
Of course!

**Comment by wtmoose** [comment]
@rafsouzap My intention was to release after wrapping up some other changes. But I can potentially release sooner. Is it causing a problem?

**Comment by wtmoose** [comment]
I have a Swift 4.2 test project that happily runs SwiftMessages 5.0.1 via CocoaPods. So I didn't anticipate compatibility issues. Can you elaborate on what you mean by incompatible?

**Comment by Michele404** [comment]
Yes, make an update to Swift 4.2 in the main branch please

**Comment by wtmoose** [comment]
What is the actual issue?

**Comment by rafsouzap** [comment]
@wtmoose I'm gonna configure Podfile to use SwiftMessages in Swift 4.0. Don't worry! Yesterday was crazy and I didn't remember it! 👍

**Comment by wtmoose** [comment]
OK guys, I went ahead and released 5.0.2 with Swift 4.2.

**Comment by wtmoose** [comment]
Please note this change broke builds for projects still using Swift 4.1 (see #229). So I reconfigured the versioning and you'll need to update to 6.0.0.
