### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by iruleonu** [SwiftKickMobile/SwiftMessages#228]
Can you mark the schema as shared?

To avoid this error:

```
Dependency "SwiftMessages" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/SwiftKickMobile/SwiftMessages/issues/new
```

**Comment by wtmoose** [comment]
Not sure what happened there. Try 5.0.3.

**Comment by wtmoose** [comment]
Please note that release 5.0.2 broke builds for projects still using Swift 4.1 (see #229). So I reconfigured the versioning and you'll need to update to 6.0.0.
