### ISSUE TITLE
Problems with StatusBarStyle? Take a look on this

### ISSUE THREAD

**Issue by cpvbruno** [SwiftKickMobile/SwiftMessages#230]
I have experienced problems with the statusBarStyle while using view controller base statusBarStyle.
In this case I had to define the preferred statusBarStyle every time I call the notification (SwiftMessage), but how can I know the current preferredStatusBarStyle if I call the notification outside a view controller for example?

This solved my problem:
```
var config = SwiftMessages.defaultConfig
    config.presentationContext = .window(windowLevel: UIWindowLevelAlert)
    config.preferredStatusBarStyle = UIApplication.shared.keyWindow?.rootViewController?.preferredStatusBarStyle
```

**Comment by wtmoose** [comment]
This seems like a general question better asked on StackOverflow.

**Comment by cpvbruno** [comment]
> This seems like a general question better asked on StackOverflow.

You're right, I just thought it would be interesting here because people usually search on the issues. But you're right
