### ISSUE TITLE
SafeArea not working on XR or Xs Max

### ISSUE THREAD

**Issue by adxworld** [SwiftKickMobile/SwiftMessages#231]
Firstly, thank you for such a fantastic library.
I have been using swift Messages for a long time now. Recently I updated to Xcode 10. Somewhere the safeArea constraints doesn't work on iphone Xr and Xs Max whereas it works seamlessly on iphone X. It just tends to cut of the notch on the former mentioned phones

This is my sample code.:
`      
        let mview : MessageView = MessageView.viewFromNib(layout: .cardView)

        mview.safeAreaTopOffset = 100.0

        mview.configureDropShadow()

        var config = SwiftMessages.defaultConfig

        config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)

        config.duration = .seconds(seconds: 2)

        SwiftMessages.show(config: config, view: mview)
`

Is there something I can do about this?

**Comment by adxworld** [comment]
Tried as you directed, yet the same results. This cuts of the notch half the way. 

I have implemented the same exact copy of the card view provided in your example.

**Comment by wtmoose** [comment]
Your code works for me in Simulator (I don't have either of the referenced devices). Here's the XS Max:

![screen shot 2018-09-26 at 12 33 08 pm](https://user-images.githubusercontent.com/2529176/46097793-68a29a80-c188-11e8-80c5-e62eae95fd7a.png)

And here's the code. Does this work for you?

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/2420873/SwiftMessagesTest.zip)

**Comment by adxworld** [comment]
I downloaded the test. I am having the perfect results from your project. 
Well I have went ahead and created manual custom constraints on the cardView I designed. 
(Does custom card view design affect the presentation of cardview in safeArea?)

**Comment by wtmoose** [comment]
For a card-style view, the background view's edges should be pinned to the superview's layout margins. Refer to CardView.xib.

**Comment by adxworld** [comment]
Yes! I am actully using the same exact `nib` for showing the card. But no matter what I have to define manual constraints for iPhone X series.

<img width="790" alt="screen shot 2018-09-26 at 4 00 24 pm" src="https://user-images.githubusercontent.com/24389003/46113987-68fd5e80-c1a5-11e8-9d82-76f43d411ed8.png">

**Comment by wtmoose** [comment]
OK, I misunderstood your comment. So, in summary, the same view works correctly in the sample project I sent you but does not work in your project? I'm not sure there's much I can do unless you help me reproduce it or give me some useful debug info.

Do you use Reveal? You can use it to examine exactly what's happening.

**Comment by wtmoose** [comment]
No reply, so I’m assuming this is no longer an issue.

**Comment by Wahab-Khan** [comment]
That thing also happens on iPhone 12 mini when shown and dismiss more than one time ... buts it's random... 
i think there is nothing wrong in following code... 

` let messageView = BaseView(frame: CGRect(x: 100, y: 100, width: 100, height: 100))
        messageView.installContentView(loginErrorView)
        messageView.backgroundHeight = 50
        messageView.clipsToBounds = true
        messageView.layoutMarginAdditions.top = 100.0
        messageView.collapseLayoutMarginAdditions = false
        var config = SwiftMessages.defaultConfig`
