### ISSUE TITLE
Labels with scrolling marquee effect

### ISSUE THREAD

**Issue by pmusolino** [SwiftKickMobile/SwiftMessages#232]
It would be really useful to add this feature to the labels within the alerts.
It would be especially useful for small alerts, such as those that show warnings under the navigation bar.

Currently, this is the result with a long text:
![cut](https://user-images.githubusercontent.com/495617/46071516-7ce29980-c180-11e8-8132-481d49d2125e.png)

This will be the result with a scrolling marquee effect:
![marqueelabeldemo](https://user-images.githubusercontent.com/495617/46071571-9a176800-c180-11e8-9562-7b8d2215a819.gif)

What do you think?

**Comment by wtmoose** [comment]
Hi. Sorry, I forgot to reply to this. Marquee labels seem like a terribly idea from a UX perspective 😜.

However, SwiftMessages will happily display any view. So it should be quite easy to set up your own message view containing a marquee label.
