### ISSUE TITLE
SwiftMessages.show(config: config, view: view) raising EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ifanchu** [SwiftKickMobile/SwiftMessages#234]
When I simply to 

    let view = MessageView.viewFromNib(layout: .messageView)
    view.configureTheme(.info)
    view.configureDropShadow()
    view.button?.isHidden = true
    view.configureContent(title: "title", body: "body")
    view.backgroundView.backgroundColor = UIColor.greenblue
    (view.backgroundView as? CornerRoundingView)?.cornerRadius = 10
    SwiftMessages.show(view: view)

it was working perfectly. 

However, if I tried to pass config like this

    let view = MessageView.viewFromNib(layout: .messageView)
    view.configureTheme(.info)
    view.configureDropShadow()
    view.button?.isHidden = true
    view.configureContent(title: "title", body:"body")
    view.backgroundView.backgroundColor = UIColor.greenblue
    (view.backgroundView as? CornerRoundingView)?.cornerRadius = 10
    var config = SwiftMessages.defaultConfig
    config.duration = .seconds(seconds: 5)
    SwiftMessages.show(config:config, view: view)

It failed at 

    open func show(config: Config, view: UIView) {
        let presenter = Presenter(config: config, view: view, delegate: self) . <--

with EXC_BAD_ACCESS

Also a weird thing is that I noticed

xcode complains config.presentationContext is not found. 

I am using xcode 10 swift 4.2.
Is this a known issue or maybe I have some configuration error? Please help.

**Comment by wtmoose** [comment]
#229

**Comment by ifanchu** [comment]
thank you very much
