### ISSUE TITLE
CUIThemeStore: No theme registered with id=0

### ISSUE THREAD

**Issue by AntoGeekz** [SwiftKickMobile/SwiftMessages#235]
Hey,

Since this morning I have  the error "CUIThemeStore: No theme registered with id=0" when I try to display a SwiftMessage. 

I'm using almost the same code than is the example. 

Only logs I have are :
- EXC_BAD_ACCESS on  let presenter = Presenter(config: config, view: view, delegate: self) (in SwiftMessages class, in the "show" method)

Any idea plz?

**Comment by wtmoose** [comment]
What did you change?

**Comment by AntoGeekz** [comment]
It's the problem... I changed nothing, It worked very well the last week and it doesn't work anymore since this morning :( Or maybe a automatic update I didn't see?

**Comment by wtmoose** [comment]
Something must have changed. What version of the following are you on?

1. SwiftMessages
2. Swift
3. Xcode

**Comment by AntoGeekz** [comment]
Ok, my bad.... The project was not configured to Swift 4.2.... 

Thx @wtmoose and sorry ^^"

**Comment by NagaSyam** [comment]
@wtmoose 
Hey, I am also encountering the same issue and configuring my project to Swift 4.2 may fix this but I don't want to upgrade my project to 4.2 at the moment, So is there any other way to fix.
Thanks

**Comment by wtmoose** [comment]
@NagaSyam Use SwiftMessages 5

**Comment by spnkr** [comment]
> This error can be resolved by moving all the image files to Assets.xcassets folder in Xcode. I had my image files in a different folder and moved them to Assets folder.

From [StackOverflow](https://stackoverflow.com/questions/52860566/error-when-running-xcode-simulator-framework-cuithemestore-no-theme-regist)

**Comment by natalia-osa** [comment]
I am facing the same issue. I have the framework installed via Cocoapods. The warning is appearing exactly when I execute the 2nd line of the following code. If I comment it out, the error in the console disappears.

    let status2 = MessageView.viewFromNib(layout: .statusLine)
    status2.configureTheme(.info) // this line causes the error to appear in the console
    status2.configureContent(body: "Blah blah...")

    var status2Config = SwiftMessages.defaultConfig
    status2Config.presentationStyle = .top
    status2Config.duration = .forever

    SwiftMessages.show(config: status2Config, view: status2)

Maybe the resources in the `podspec` are linked in the wrong way and don't copy properly to the client application..?

Environment:
1) `SwiftMessages` version 7.0.0
2) Xcode 10.2.1
3) Swift 5
4) Cocoapods version 1.8.4
