### ISSUE TITLE
Crash if I set duration on config

### ISSUE THREAD

**Issue by harishchopra86** [SwiftKickMobile/SwiftMessages#236]
Swift Messages crash if I set a duration on default config object. It works fine without setting duration.

**Comment by wtmoose** [comment]
Please make sure you're using compatible versions of Swift and SwiftMessages:

1. Swift 4.1 works with SwiftMessages 5
2. Swift 4.2 works with SwiftMessages 6

If al that checks out, I'll need to see your code and a crash log in order to have any chance of helping you.

**Comment by tadasstra** [comment]
Same goes for me on 6.0.0. with Swift 4.2. Had to migrate to 5.0.1 to defeat the Crash. 

Crash does not give any useful information just EXC_BAD_ACCESS on this line in SwiftMessages.swift:

public static func show(config: Config, view: UIView) {
        --> globalInstance.show(config: config, view: view)
}

**Comment by sunnypurewal** [comment]
I can reproduce this issue with a crash on the same line as @tadasstra posted. I am installing using Carthage v6.0.0. Reverting back to 5.0.1 worked for me.
The crash happens whether I set the duration or not.

**Comment by wtmoose** [comment]
@tadasstra @sunnypurewal please verify your app target's "Swift Language Version" build setting is 4.2. Others have reported crashes and incorrectly thought their app was 4.2.

**Comment by sunnypurewal** [comment]
@wtmoose oops! That was indeed my problem. Thanks.
