### ISSUE TITLE
How to hide existing message and show again ?

### ISSUE THREAD

**Issue by khoozhiyan1997** [SwiftKickMobile/SwiftMessages#239]
This does not seems to be working.

`  view.configureDropShadow()
  
view.backgroundHeight = 120
            var config = SwiftMessages.defaultConfig
            config.presentationContext = .automatic
            config.duration = .forever
            config.presentationStyle = .bottom
            config.interactiveHide = true
            SwiftMessages.hideAll()
            SwiftMessages.show(config: config, view: view)`

**Comment by wtmoose** [comment]
You want to show an existing message while it's in the process of being hidden?

**Comment by wtmoose** [comment]
No reply. Closing.
