### ISSUE TITLE
Crash when trying to load a custom NIB

### ISSUE THREAD

**Issue by iamsanketray123** [SwiftKickMobile/SwiftMessages#240]
```
      let myView : MessageView = try! SwiftMessages.viewFromNib(named: "MandateCell") // crash
      var config = SwiftMessages.defaultConfig
      config.duration = .forever
      config.presentationStyle = .bottom
      config.dimMode = .gray(interactive: true)
      SwiftMessages.show(config: config, view: myView)
```

this leads to a fatal error. Am I doing something wrong?

**Comment by gcharita** [comment]
You should probably change the `MessageView` type with your custom type like this:

```swift
let myView: MandateCell = try! SwiftMessages.viewFromNib(named: "MandateCell")
```

If this doesn't fix your issue try catching and printing the error like this:

```swift
do {
    let myView: MessageView = try SwiftMessages.viewFromNib(named: "MandateCell")
} catch {
    print("Error: \(error.localizedDescription)")
}
```

That way you can investigate the crash further.

**Comment by iamsanketray123** [comment]
> You should probably change the `MessageView` type with your custom type like this:
> 
> ```swift
> let myView: MandateCell = try! SwiftMessages.viewFromNib(named: "MandateCell")
> ```
> 
> If this doesn't fix your issue try catching and printing the error like this:
> 
> ```swift
> do {
>     let myView: MessageView = try SwiftMessages.viewFromNib(named: "MandateCell")
> } catch {
>     print("Error: \(error.localizedDescription)")
> }
> ```
> 
> That way you can investigate the crash further.

I tried putting everything in the do try block and i get this for `error.localizedDescription`  : **The operation could not be completed (SwiftMessages.SwiftMessagesError error 0)**

**Comment by iamsanketray123** [comment]
I created a new class `class AddAlternateBank: MessageView {

}`
Created AddAlternateBank.xib file. selected the File's owner and added the class. Is that the right approach?

**Comment by wtmoose** [comment]
My guess is you haven't included your nib file in your app's target. However, it is hard for me to guess are you issue since you didn't post the crash's call stack.

**Comment by gcharita** [comment]
@iamsanketray123 the wrong step is probably this one: "selected the File's owner and added the class"
You shouldn't set your class in the "File's owner" but in the View
![screen shot 2018-10-08 at 19 09 41](https://user-images.githubusercontent.com/16266885/46620732-31d86700-cb2e-11e8-8605-bbc62bb1bc54.png)

**Comment by iamsanketray123** [comment]
That worked @gcharita .Thanks!
