### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by Idomo** [SwiftKickMobile/SwiftMessages#241]
HI, first thing thanks for this library!
I'v just downloaded it and I noticed that there are few problems:
1) When showing message it will stay 'till the duration will pass, so if I'm moving to another `ViewController` the message will still be shown and will disappear only when the duration will pass.
I want it to disappear when moving to another `ViewController`, and not by using the `hide()/hideAll()` method every time in `prepare for segue` or something like that.

2) I'm using `navigationItem.hidesSearchBarWhenScrolling = false` in my controller so the `searchBar` is always shown, also when loading the controller, so the message is coming behind it instead of being at the bottom of it.
![img_081953b09178-1](https://user-images.githubusercontent.com/26777129/46609799-a51fb000-cb11-11e8-8429-08dae6f31aa9.jpeg)

3) There are few warnings of deprecated code from the Swift compiler, please be noticed to those.
![image](https://user-images.githubusercontent.com/26777129/46609994-26774280-cb12-11e8-827b-72991281d5ec.png)

4) I really missed the `view.button?.isHidden = true` and it took me some time to find your comment on issue about it, can you please add it to the `README`?

5) I couldn't find a way to use `Theme` and only change it's `backgroundColor`, there is only option to use the default themes or make my own (including the images and etc.), but I want to use the default themes, only change one setting in it.
I'd like you to add option for these if there is no one right now.

My code:
```
SwiftMessages.show {
  let view = MessageView.viewFromNib(layout: .cardView)
  view.configureContent(title: "", body: "Documents have been loaded successfully!", iconText: "✔︎")
  view.configureTheme(.success)
  view.button?.isHidden = true
  return view
}
```

Thanks,
Ido.

**Comment by wtmoose** [comment]
Hi,

For future reference, please try to limit one issue per ticket to streamline discussion.

1. See #73
1. I need to look into this. As a workaround, you can set `messageView.layoutMarginAdditions.top = XX` to shift the content down by the amount needed.
1. See #218 
1. This is already documented in the readme in the "MessageView Class" section.
1. The `configure` methods are intended to be convenience functions. If they don't do what you need, you should write your own. In this case, you can call `view.configureTheme(.success)` and then change the background color. Or perhaps use the existing API:
````swift
public func configureTheme(backgroundColor: UIColor, foregroundColor: UIColor, iconImage: UIImage? = nil, iconText: String? = nil)
````

**Comment by wtmoose** [comment]
I'm surprised about (2) because I would expect the safe area to include the search bar. Is that not the case?

**Comment by Idomo** [comment]
> I'm surprised about (2) because I would expect the safe area to include the search bar. Is that not the case?

It is the case, really wired...

**Comment by wtmoose** [comment]
I've been unusually busy and haven't had time to investigate (2). If you still need help with this and can send me a sample project, I will look into it much sooner.
