### ISSUE TITLE
ViewController goes out of screen

### ISSUE THREAD

**Issue by jduranc** [SwiftKickMobile/SwiftMessages#243]
Hi,

I found a bug, when presenting one view controller using segues, if some controller opens camera or gallery the content of view controller goes out of screen (up/left) and shadow still on place.

![screen shot 2018-10-08 at 8 15 03 am](https://user-images.githubusercontent.com/9992020/46617909-e04ebe80-cad2-11e8-8e5c-c7fd6a238110.png)

**Comment by jduranc** [comment]
Hi @wtmoose 

I just add one button to open the gallery using UIImagePickerController in the child controller, so, open any kind message (center/top/etc) show details, then click button to open camera, when UIImagePickerController its closed, the content its gone, if I set the viewcontroller size bigger, the contents appears up/left corner.

regards,

**Comment by wtmoose** [comment]
Could you attach your modified project for me?

**Comment by jduranc** [comment]
Sure,
Here it is.
[Sample.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/2457009/Sample.zip)

**Comment by wtmoose** [comment]
The view controller's view is being temporarily removed from the view hierarchy by iOS. I need to handle this case by re-establishing the Auto Layout constraints when the view is reinstalled. As a workaround, you can specify `modalPresentationStyle = .overFullScreen`:

````swift
@IBAction func onClick(_ sender: Any) {
    let control = UIImagePickerController()
    control.delegate = self
    
    control.sourceType 	= .photoLibrary
    control.modalPresentationStyle = .overFullScreen
    self.present(control, animated: true, completion: nil)
}
````

**Comment by jduranc** [comment]
Hi @wtmoose,

Thats fix the issue, thanks for your help ^_^.

**Comment by wtmoose** [comment]
I wasn't able to find a solution that was better than the above workaround, so I'm closing this one.
