### ISSUE TITLE
UITransitionView not removed after dismissing message (presented using the "swift messages" segue in Interface Builder) in case the segue source doesn't exist any more

### ISSUE THREAD

**Issue by vitalii-tym** [SwiftKickMobile/SwiftMessages#247]
My "message" was created using the "swift messages" segue in Interface Builder as described in [this doc](https://github.com/SwiftKickMobile/SwiftMessages/blob/master/ViewControllers.md).

It is then configured in `prepare(for segue: sender:)` with minimum settings:

```
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    if let segue = segue as? SwiftMessagesSegue {
        segue.configure(layout: .centered)
        segue.dimMode = .blur(style: .dark, alpha: 0.9, interactive: true)
        segue.messageView.configureNoDropShadow()
    }
}
```

Most of the time it works fine, but ~sometimes~ after you remove the underlying view controller it leaves UITransitionView after being dismissed and as a result the app remains unresponsive and needs to be force quit by user. Same thing on device and on simulator, and happens with both ways of dismissing - by sliding out or by tapping on the dark area behind the "message".

<img width="809" alt="screenshot 2018-10-17 17 05 35" src="https://user-images.githubusercontent.com/5410835/47093350-aba8d880-d231-11e8-960c-978c9542ee34.png">

~I couldn't find reliable steps to reproduce this, will update if I find them. But maybe you have ideas where to look.~

Everything is fine when "message" is presented in normal way, via `SwiftMessages.show(config: config, view: view)` (I'm using this heavily in other parts of the app).

**Comment by wtmoose** [comment]
Yikes. Can you reproduce it in the demo app?

The first thing I'd look at is check if line 52 of `SwiftMessagesSegue.swift` is being called.

**Comment by vitalii-tym** [comment]
Found it. It was not "sometimes".  I had an array of view controllers, one of them had a UITableView and a UITableViewCell had a UIButton calling the segue. At some moment I was flushing the array and initing new view controllers (not sure if the old controllers were garbage collected or were still hanging somewhere in memory). This is the moment when dismissing the message was leaving UITransitionView sticking on top. Updated the bug summary.

In my particular case it was a terrible bug in my code, already fixed it.

In general I'm not sure if this can be considered a bug in SwiftMessages, because killing the view controller, from which the segue comes, is not something people would want to do often enough. @wtmoose, what do you think? Probably can close as NAB?

**Comment by wtmoose** [comment]
Interesting. I think in this case, SwiftMessages is using the presentation APIs correctly and there's nothing it can do to prevent this behavior. So I'm going to close this one. Good to hear you fixed it.
