### ISSUE TITLE
When set `dimMode = .none` and use `SwiftMessagesSegue`, can't interact with the background.

### ISSUE THREAD

**Issue by ShaneQi** [SwiftKickMobile/SwiftMessages#248]
I'm trying to achieve a UI that the alert (.topCard layout) stays at the top, and user is able to interact with background without closing the alert.

I prefer using `SwiftMessagesSegue` because I've already had the alert view written as a view controller. But when I set `dimMode = .none`, the background **isn't** enabled to be interacted with. Looks like something is blocking the touches.

I also tried out the demo project, what's interesting to me is that if I use the old way to show an alert (`SwiftMessages.show`) and set `dimMode = .none`, the background **is** interact-able.

So I'm thinking it might be a technical constraint of segue that makes background interaction impossible. I'd like ask if that is the case or it's just a bug (or missing feature) of `SwiftMessagesSegue ` implementation.

**Comment by wtmoose** [comment]
As far as I understand, modal presentation, by definition, doesn't allow touches through to the underlying view controller. The presented  view controller's view is contained in a `UITransitionView`, which is provided by iOS. `UITransitionView` doesn't allow touches outside of your content to pass through to the underlying view.

View controller containment might be a workable alternative with a little extra work. Suppose you have view controller `A` and you want to show view controller `B` on top of it:

1. Instantiate view controller `B` programmatically.
2. Add view controller `B` as a child of `A`.
3. Use SwiftMessages to show `B.view`, where `config.presentationContext = .view(view: A.view)`.

**Comment by ShaneQi** [comment]
> As far as I understand, modal presentation, by definition, doesn't allow touches through to the underlying view controller.

I agree with you on this point.

I tried converting my view controller to a view (xib), and by using `SwiftMessages.show` it worked.

Thanks for the response.
