### ISSUE TITLE
Dismissal problem when presented from UISearchController

### ISSUE THREAD

**Issue by abuharsky** [SwiftKickMobile/SwiftMessages#251]
I have collectionviewconntroller, tap on cell will open modal view controller using SwiftMessagesSegue(bottom tab) with interactive dismissal by swiping down enabled.

This scenario works great except next case:

using search controller and additional search results view controller with the same modal view presenting logic breaks uiview hierarchy after been dismissed by swipe down.

After debugging I recognized what happens:

first, search results view controller was presented, then (by tapping on cell) modal view controller was presented by segue. Swiping it down calls

SwiftMessagesSegue lines 250-258

`            case .didHide:
                if let completeTransition = self.hider.completeTransition {
                    completeTransition(true)
                } else {
                    // Case where message is interinally hidden by SwiftMessages, such as with a
                    // dismiss gesture, rather than by view controller dismissal.
                    source.dismiss(animated: false, completion: nil)
                }
                self.selfRetainer = nil
`

look at this line

`                    source.dismiss(animated: false, completion: nil)
`

but **source** is search results view controller.

changing it to 

`                    self.destination.dismiss(animated: false, completion: nil)
`

solves the issue.

**Comment by wtmoose** [comment]
I don't really understand your problem description. What does "breaks uiview hierarchy" mean? Maybe I would understand better if you attach code, screen recording, screenshot, etc.

Are you seeing something like #243?

**Comment by abuharsky** [comment]
> I don't really understand your problem description. What does "breaks uiview hierarchy" mean? 


Look at this view hierarchy.
CollectionViewController -> Search Controller -> Search Results Controller -> ModalView(swiftMessages)
all Ok



![](https://pp.userapi.com/c845122/v845122465/117abc/DVYSIQmdeNY.jpg)



Then I swiped down Modal view, swiftMessages called 
`source.dismiss(animated: false, completion: nil)`
where is **source** is **SearchResultsViewController** and view hierarchy broken - system UITransitionView still on top of screen



![](https://pp.userapi.com/c845122/v845122465/117ab2/yR3HS_-yHq4.jpg)

**Comment by wtmoose** [comment]
I never followed up on this because you didn't respond to my comment in #252. However, I recently exposed event listeners in `SwiftMessagesSegue` in 6.0.2 and I think you could solve your problem by adding an `eventListener` that dismisses the search controller on `didHide`. Reopen if you need further help.

**Comment by LiuYimin** [comment]
> I never followed up on this because you didn't respond to my comment in #252. However, I recently exposed event listeners in `SwiftMessagesSegue` in 6.0.2 and I think you could solve your problem by adding an `eventListener` that dismisses the search controller on `didHide`. Reopen if you need further help.

add a eventListener cant solve my problem, I don't want my native model view controller to be dismissed.but the  code `source.dismiss(animated: false, completion: nil)` do that

**Comment by wtmoose** [comment]
@LiuYimin I have no idea why you're replying to this 5 year old closed ticket
