### ISSUE TITLE
presentationContext error?

### ISSUE THREAD

**Issue by perlguy99** [SwiftKickMobile/SwiftMessages#255]
I have deleted my DerivedData folder, cleaned my project, and I am still getting the following error...

`Value of type 'SwiftMessages.Config' has no member 'presentationContext'; did you mean 'presentationStyle'?`

If I command-click and go to SwiftMessages.Config, I definitely see `presentationContext` and it is marked as `public`

Has anyone else encountered this?  I'm not sure a) why it isn't being found and b) how to fix it.

Thanks.

**Comment by wtmoose** [comment]
#229
