### ISSUE TITLE
Cant install via Pod

### ISSUE THREAD

**Issue by xtripDucBM** [SwiftKickMobile/SwiftMessages#256]
I just re-clone my project and then start install Pod but I got this message while installing SwiftMessages.

[!] Error installing SwiftMessages
[!] /usr/local/bin/git clone https://github.com/SwiftKickMobile/SwiftMessages.git /var/folders/gl/6q8xnd4539j2n1qkgkh6brrr0000gn/T/d20181102-31643-73c6jk --template= --single-branch --depth 1 --branch 5.0.3

Cloning into '/var/folders/gl/6q8xnd4539j2n1qkgkh6brrr0000gn/T/d20181102-31643-73c6jk'...
warning: Could not find remote branch 5.0.3 to clone.
fatal: Remote branch 5.0.3 not found in upstream origin

Anyone has solution for this? Thanks very much

**Comment by wtmoose** [comment]
I deleted 5.0.2 and 5.0.3 after realizing that I hadn't followed semantic versioning rules. So you'll need to install one of the following:

* 5.0.1 if you're on < Swift 4.2
* 6.0.0 if you're on >= Swift 4.2
