### ISSUE TITLE
segue perform programmatically got empty view

### ISSUE THREAD

**Issue by LawrenceHan** [SwiftKickMobile/SwiftMessages#258]
```swift
let vc = UIViewController()
let segue = SwiftMessagesSegue(identifier: nil, source: self, destination: vc)
segue.configure(layout: .topMessage)
segue.perform()
```

you can only see the dimming view.

**Comment by wtmoose** [comment]
Your view controller has no Auto Layout constraints or intrinsic height, so you get zero.

**Comment by LawrenceHan** [comment]
@wtmoose Thank you for your reply.
Could you give me some suggestion?

**Comment by wtmoose** [comment]
If you want to set an explicit height, you can do:

````
viewController.view.heightAnchor.constraint(equalToConstant: 100).isActive = true
````

Otherwise, you let Auto Layout determine the height of your view controller's content in the same way that you'd configure a dynamic height table view cell.

**Comment by LawrenceHan** [comment]
@wtmoose Thank you.
I'm using manual layout.
I want to read this particular code, would you mind to point out where should I take a look? So I could change it a little in my fork repo.

**Comment by wtmoose** [comment]
Why are you trying to modify the repo?

**Comment by LawrenceHan** [comment]
@wtmoose I want it support manual layout viewcontroller.

**Comment by wtmoose** [comment]
I'm pretty confused by this discussion. What do you mean by "doesn't support manual layout"?

**Comment by LawrenceHan** [comment]
@wtmoose Sorry for misunderstand.
```swift

let vc = UIViewController()
vc.backgroundColor = .green
let segue = SwiftMessagesSegue(identifier: nil, source: self, destination: vc)
segue.configure(layout: .topMessage)
segue.perform()

```

Above code should give me a green background view controller with SwiftMessage beautiful animation. Instead I got a dimming background.

As mentioned in above post: `Your view controller has no Auto Layout height constraints or intrinsic height, so you get zero.`

Sometime I prefer manually set explicit frame for view controller (or not). I think maybe I can do something about it.

**Comment by wtmoose** [comment]
If you're opposed to specifying Auto Layout constraints, SwiftMessages will add one to `segue.messageView.backgroundView` for you:

````swift
segue.messageView.backgroundHeight = 100
````

**Comment by Tawfikk** [comment]
@LawrenceHan you're solved the problem ? I have same error.

**Comment by LawrenceHan** [comment]
@Tawfikk 
try below code
```
segue.messageView.backgroundHeight = 100
```
or use auto layout
