### ISSUE TITLE
Add event listeners to SwiftMessagesSegue

### ISSUE THREAD

**Issue by nilehmann** [SwiftKickMobile/SwiftMessages#262]
I would like to be able to know when a view controller presented with a `SwiftMessagesSegue` has been dismissed with a gesture. I believe that's not possible now. Would be there any issues by exposing the `eventListeners` of the internal config?

**Comment by wtmoose** [comment]
Yep. Good idea.

**Comment by wtmoose** [comment]
Try 6.0.2
