### ISSUE TITLE
Compile error in Xcode 10.0

### ISSUE THREAD

**Issue by Birju-Bhatt** [SwiftKickMobile/SwiftMessages#263]
I got following compile error in Xcode 10 (swift 4.2).

Could not build Objective-C module 'SwiftMessages'

Also got compatibility error.

UIViewNoIntrinsicMetric' has been renamed to 'UIView.noIntrinsicMetric'
'UIDeviceOrientationDidChange' has been renamed to 'UIDevice.orientationDidChangeNotification'
'UIWindowLevel' has been renamed to 'UIWindow.Level'

And many more error.

Please help me out for above issues.

**Comment by wtmoose** [comment]
Update to SM 6

**Comment by Birju-Bhatt** [comment]
Thanks for your immediate reply. But whenever i tried to install SwiftMessages through pod , it always take old version rather than new version which you mentioned

**Comment by wtmoose** [comment]
I suggest that you either read through the CocoaPods documentation or ask how to update a pod on StackOverflow.

**Comment by Birju-Bhatt** [comment]
Hi wemoose , 
I know how to update pod but what i am saying is if i write pod 'SwiftyJSON' then generally it takes latest version. But instead of that it takes **Installing SwiftMessages (4.1.4)**. So my question is how can i update to latest version i.e. 6.0.1 through the pod because whenever i am trying to update for the same then it will give me error like below. I wrote like this **pod 'SwiftMessages', '~> 6.0.1'**

[!] CocoaPods could not find compatible versions for pod "SwiftMessages":
  In Podfile:
    SwiftMessages (~> 6.0.1)

**Comment by wtmoose** [comment]
Wow

**Comment by Birju-Bhatt** [comment]
@NSMyself I got the solution. I just change below line in my pod file
**platform :ios, '9.0' - Before
platform :ios, '10.0' - After**

I changed it from 9.0 to 10.0 and it works fine.
