### ISSUE TITLE
Not visible property presentationContext in swift 4.0

### ISSUE THREAD

**Issue by pkalinowski** [SwiftKickMobile/SwiftMessages#265]
In Swift 4.0 the property `presentationContext` from `SwiftMessage.Config` is not visible for the app. During compiling get an error:  
`Value of type 'SwiftMessages.Config' has no member 'presentationContext'; did you mean 'presentationStyle'?`
This library has been attached as module by cocoapods. 
Version of the library is 6.0.1. 
After changing swift version to 4.2 everything works correctly.

**Comment by wtmoose** [comment]
@pkalinowski Swift 4 requires SwiftMessages 5.
