### ISSUE TITLE
Tab outside to not dismiss

### ISSUE THREAD

**Issue by Sopheak0** [SwiftKickMobile/SwiftMessages#270]
I'm using this code to open dialog from xib file using segue: 

```    let vc = Wallet(nibName: "Wallet", bundle: nil)
        vc.view.heightAnchor.constraint(equalToConstant: self.view.frame.height / 2.5).isActive = true
        let segue = SwiftMessagesSegue(identifier: nil, source: self, destination: vc)
        segue.configure(layout: .bottomMessage)
        segue.interactiveHide = false // i assume that this code can prevent the click outside 
        segue.perform()
```

but i still can dismiss the dialog when user click outside the view. so how to prevent user to click outside view to dismiss the dialog?

**Comment by wtmoose** [comment]
````swift
/// Specifies whether or not the interactive pan-to-hide gesture is enabled
/// on the message view. The default value is `true`, but may not be appropriate
/// for view controllers that use swipe or pan gestures.
public var interactiveHide: Bool {
    get { return messenger.defaultConfig.interactiveHide }
    set { messenger.defaultConfig.interactiveHide = newValue }
}
````

Use

````swift
segue.dimMode = .gray(interactive: false)
````

**Comment by salvadorvilla** [comment]
Is it possible to have the presented view controller toggle between dismissible and not dismissible? I want it to initially be dismissible but then not so when there's a network call being performed. I tried updating the segue and updating the properties from:
`segue?.interactiveHide = false`
`segue?.dimMode = .gray(interactive: false)`
To:
`segue?.interactiveHide = true`
`segue?.dimMode = .gray(interactive: true)`

But once the segue is performed then it no longer cares what these properties are. Any way around this?
