### ISSUE TITLE
SwiftMessagesSegue does not work

### ISSUE THREAD

**Issue by r3econ** [SwiftKickMobile/SwiftMessages#271]
I'm following the steps described in [View Controllers wiki](https://github.com/SwiftKickMobile/SwiftMessages/blob/master/ViewControllers.md). I'm trying to show my view controller programatically.

```
@objc
    private func searchButtonTapped() {
        let vc = LocationSearchViewController()
        let nc = UINavigationController(rootViewController: vc)

        let segue = VeryNiceSegue(identifier: nil,
                                  source: self,
                                  destination: nc)
        segue.perform()
    }

    class VeryNiceSegue: SwiftMessagesSegue {
        override public init(identifier: String?, source: UIViewController, destination: UIViewController) {
            super.init(identifier: identifier, source: source, destination: destination)
            configure(layout: .centered)
        }
    }
```

View controller does not appear. I only see dimmed background. Can someone point me what I'm doing wrong? I pretty much copied the code from the wiki.

<img width="435" alt="screenshot 2019-01-02 at 14 16 15" src="https://user-images.githubusercontent.com/505054/50593672-88d5aa00-0e99-11e9-939e-96b6b4f08d36.png">

**Comment by wtmoose** [comment]
The height of your `LocationSearchViewController`'s view is probably zero because you don't have sufficient Auto Layout constraints. I don't know your view hierarchy, so I can only give you a couple of ways to specify a fixed height:

````swift
vc.view.heightAnchor.constraint(equalToConstant: 100).isActive = true
````

or

````swift
vc.preferredContentSize = CGSize(width: 0, height: 100) // SwiftMessages ignores the preferred width
````

**Comment by wtmoose** [comment]
Height considerations are addressed in the comments in `SwiftMessagesSegue.swift`. However, I've added the following to the readme file as well:

### Height

SwiftMessages relies on Auto Layout to determine the height the view controller's view.
    However, some view controllers, such as `UINavigationController` have zero Auto Layout height.
    There are a few ways to specify the height of these view controllers:
1. Add an explicit height constraint to the view controller's view.
2. Set the view controller's `preferredContentSize` ("Use Preferred Explicit Size" in Interface Builder's
   attribute inspector). Note that `preferredContentSize.width` is ignored and can be set to zero.
3. Set `SwiftMessagesSegue.messageView.backgroundHeight`.

**Comment by wtmoose** [comment]
You good?

**Comment by r3econ** [comment]
It worked, thanks a lot! :)
