### ISSUE TITLE
Retain cycle when using SwiftMessages.PresentationContext

### ISSUE THREAD

**Issue by gregoripolak** [SwiftKickMobile/SwiftMessages#274]
Hi guy's,
So I've been using SwiftMessages, which is pretty awesome.
But I notice a retain cycle in my app caused by SwiftMessages.PresentationContext,
The reason is because both:
```
case viewController(_: UIViewController)
case view(_: UIView)
```
Hold a strong reference to the View Controller\View.
I suggest turning the cases to:
```
case viewController(_: Weak<UIViewController>)
case view(_: Weak<UIView>)
```
I tried opening a Pull request, but I don't have push permissions to this repo,
Let me know what you think.

**Comment by wtmoose** [comment]
Hi. I'm aware of the strong references in `presentationContext`. I haven't changed them to weak references because it is a breaking API change and doesn't generally cause retain cycles. What are you doing to get into a retain cycle?

**Comment by gregoripolak** [comment]
Nothing special, I have a View Model that creates the Config with a presentationContext.viewController(Strong reference), I present the message via the view controller, so the view controller holds the message, and the message holds the view controller.
I'll probably Fork this project

**Comment by wtmoose** [comment]
Good luck
