### ISSUE TITLE
Ability to hide message without an animation

### ISSUE THREAD

**Issue by foxware00** [SwiftKickMobile/SwiftMessages#276]
I want the hide animation to be present, but in a particular case I want the custom view to disappear like `isHidden = true` instead of playing the animation. I see no easy way of achieving this. Am I missing something obvious?

**Comment by wtmoose** [comment]
No, nothing like that. You're the first to ask. I labelled this one as an enhancement request.

**Comment by foxware00** [comment]
I'm happy to open a PR, i'm just not quite sure how you'd achieve this. I was thinking `hide(animated: Bool = true)` or similar functionality

**Comment by wtmoose** [comment]
Try `hide(animated: false)` on the head of master branch.

**Comment by foxware00** [comment]
@wtmoose Are you saying you've added it? I can't seem to see any updates on master

**Comment by wtmoose** [comment]
Oops. Try now

**Comment by foxware00** [comment]
@wtmoose Worked perfectly, thank you!

**Comment by sundaleek** [comment]
Hello @wtmoose . I hope you are stay safe during these time.
Is there a way to present without animation?

**Comment by wtmoose** [comment]
@sundaleek would animating with zero duration work? If so, then yes you can do that. All of the animators have customizable duration. You'd instantiate the animator of your choice, configure the duration, and use `config.presentationStyle = .custom(animator: animator)`.
