### ISSUE TITLE
presenting inside child view controller

### ISSUE THREAD

**Issue by danipralea** [SwiftKickMobile/SwiftMessages#282]
Hello I have a child navigation view controller being added in the second half of the screen. Is there any way I can present an alert under the navigation bar of the root view controller of that navigation controller with SwiftMessages? 
I have tried pretty hard looking for one, but with no success.

Thanks,
Dan.

**Comment by wtmoose** [comment]
Did you look into `presentationContext = .viewController(<your view controller>)` where `<your view controller>` would be a view controller within the navigation stack?

**Comment by danipralea** [comment]
sweet. thanks. I totally missed that one.
an actual better solution was to use `.view`, cause my navigation bar is not actually a navigation bar, but just a custom one.

Again, thank you for the suggestion. cheers!
