### ISSUE TITLE
Adjust View Controller's width in Popup

### ISSUE THREAD

**Issue by AlirezaSN** [SwiftKickMobile/SwiftMessages#285]
Hi there, Can we adjust VC's width when using it as a popup ... just like setting backgroundHeight property to change its height 😅
Best Regards

**Comment by VinothKrishnan** [comment]
@AlirezaSN Hi,
I Need to extend the view controller popup width.is there any solution for this. kindly update me.

**Comment by wtmoose** [comment]
@AlirezaSN `preferredContentSize`

**Comment by VinothKrishnan** [comment]
Thank you so much @AlirezaSN ...It's working...
