### ISSUE TITLE
The dialog hides StatusBarStyle and statusbar becomes black

### ISSUE THREAD

**Issue by alouanemed** [SwiftKickMobile/SwiftMessages#288]
I present the controller B from A, which contains a collection view and a tabbar. When I show a dialog in B and hit back to A the status bar becomes dark and tabbar disappears completely.

 ```
static func configs() -> SwiftMessages.Config   {
        var config = SwiftMessages.Config()
        config.dimMode = .gray(interactive: true)
        config.preferredStatusBarStyle = .lightContent
        config.presentationStyle = .bottom
        return config
    }
    
    static func showSuccessMessage(with body: String){
        let view = MessageView.viewFromNib(layout: .cardView)
        view.configureTheme(.success)
        view.configureDropShadow()
        view.configureContent(title: R.string.localizable.commonSuccess.key.localized(), body: body)
        view.button?.isHidden = true
        show(config: configs(), view: view)
    }
```

I am using https://github.com/Ramotion/animated-tab-bar

**Comment by wtmoose** [comment]
In general, I don't have time to diagnose compatibility issues with other 3rd party libraries. However, if you can send me a zipped up project that reproduces the problem, I will take a look.

**Comment by alouanemed** [comment]
Thank your reply, I created a simple project which has the same flow, but it works well as expected. I used another library to show custom Alert View and it seems that it broke something related to Window, as the screen itself become unresponsive, it's like the app has frozen but actually, it's not.

Where do you think the issue that causes this behavior? Thanks.

**Comment by wtmoose** [comment]
Please refer to my previous message

**Comment by alouanemed** [comment]
https://github.com/huri000/SwiftEntryKit/issues/164#issuecomment-473236156
