### ISSUE TITLE
Weird crash.

### ISSUE THREAD

**Issue by MaeseppTarvo** [SwiftKickMobile/SwiftMessages#29]
Hey. I did some easy things with your library. After user post I popped the message which worked for a while. However, now it leads me to nil and crash. And while debugging, it shows me [this](https://www.upload.ee/image/6258728/Screen_Shot_2016-10-17_at_16.32.40.png). What is causing this?

**Comment by wtmoose** [comment]
Maybe #9?

**Comment by MaeseppTarvo** [comment]
Sadly mine is not Jailbroken but the error is same I guess.

**Comment by wtmoose** [comment]
If you're using CocoaPods, make sure you're using the 1.1.0 beta per the readme. If that isn't the cause, I'll need more information to go on. It doesn't normally crash, so you'll need to help me discover what's different about your setup. Attaching a sample project that crashes is ideal.

**Comment by MaeseppTarvo** [comment]
Yea sorry.. I am running the beta like in ReadMe. I have to say, it is unusable. It worked perfectly before. I think I am gonna put my push my project to Github and let u know.
