### ISSUE TITLE
Swift 5 support?

### ISSUE THREAD

**Issue by OkiRules** [SwiftKickMobile/SwiftMessages#296]
Could you please add Swift 5 support?

Thanks in advance!

**Comment by wtmoose** [comment]
Is the 4.2 version not working with Swift 5?

**Comment by OkiRules** [comment]
It is, but it would be great if it was compiling with Swift 5

**Comment by noxostudio** [comment]
Yep there are just some warnings but the app still work correctly for me ;)

**Comment by IceFloe** [comment]
It would be nice to convert it to Swift 5

**Comment by wtmoose** [comment]
See `work/swift5`. It will be released soon.

**Comment by OkiRules** [comment]
Great!

**Comment by Coeur** [comment]
@OkiRules 

At this in your Podfile:
```ruby
pre_install do |installer|
    installer.analysis_result.specifications.each do |s|
        s.swift_version = '5.0'
    end
end
```
And all your swift pods will build for Swift 5.

**Comment by OkiRules** [comment]
Thanks this is really useful!

Thanks,
Oscar

**Comment by vorb** [comment]
And what should carthage-users do?

**Comment by Coeur** [comment]
@vorb the same; living in [Carthage](https://en.wikipedia.org/wiki/Carthage_(municipality)) shouldn't be a problem.

Or you could check [the doc](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile) and add this in your Cartfile:
```ruby
github "SwiftKickMobile/SwiftMessages" "work/swift5"
```

**Comment by CedricSoubrie** [comment]
Do you plan to merge `work/swift5` branch into `master` soon ?
And by the way : this library is AMAZINGLY good !!!

**Comment by wtmoose** [comment]
Yep, I do. Thanks!
