### ISSUE TITLE
Memory Leak Tied To Presenter.swift

### ISSUE THREAD

**Issue by abrpatel** [SwiftKickMobile/SwiftMessages#298]
<img width="1280" alt="Screen Shot 2019-04-09 at 6 48 03 PM" src="https://user-images.githubusercontent.com/947100/55842229-2de6cb00-5af8-11e9-997e-cb898bbba0a0.png">

Shows up when the view is presented using a segue 

```
class SwiftMessagesTopSegue: SwiftMessagesSegue {
    override public  init(identifier: String?, source: UIViewController, destination: UIViewController) {
        super.init(identifier: identifier, source: source, destination: destination)
        configure(layout: .topCard)
        
        super.interactiveHide = false
        super.dimMode = .gray(interactive: false)
    }
}

```

Would appreciate any suggestions on how to fix it.

**Comment by wtmoose** [comment]
The segue intentionally retains itself until you dismiss the view controller in order remain the transitioning delegate for dismissal.

**Comment by abrpatel** [comment]
Got it. Thanks!
