### ISSUE TITLE
SwiftMessagesSegue won't present view controller

### ISSUE THREAD

**Issue by gabrielvincent** [SwiftKickMobile/SwiftMessages#302]
I'm trying to present a view controller on a SwiftMessage using `SwiftMessagesSegue`, but all I get is the black translucent overlay over the source view controller.

![Screenshot 2019-04-16 at 13 50 58](https://user-images.githubusercontent.com/469519/56228998-75c1a100-6068-11e9-89f0-fb2509673b84.png)

If I tap anywhere in the screen, the overlay disappears.

This is the code I'm using to show the view controller.

```swift
guard let creditsTableViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: Storyboard.Identifier.CreditsTableViewController) as? CreditsTableViewController else {
    
    print("This block does not run")
    return
}

print("This prints (it really does)")

let destination = UINavigationController(rootViewController: creditsTableViewController)
let segue = SwiftMessagesSegue(identifier: nil, source: parent, destination: destination)
segue.configure(layout: .topCard)
```

**Comment by wtmoose** [comment]
You need to specify a height for your destination view controller. Any of the following will work:

1. Add sufficient Auto Layout constraints such that it has an intrinsic height.
2. Set `preferredContentSize.height` (you can do this in code or in the storyboard).
3. Set `SwiftMessagesSegue.messageView.backgroundHeight`

**Comment by gabrielvincent** [comment]
@wtmoose Thanks for the quick and assertive response! That did the trick.
