### ISSUE TITLE
swiftmessagessegue

### ISSUE THREAD

**Issue by Harryjeffs** [SwiftKickMobile/SwiftMessages#303]
Is there a way to implement SwiftMessageSegue from appDelgate.swift? 

The method I have tried does not show any popup, then again, shows no errors. Cheers.

**Comment by wtmoose** [comment]
You can implement `SwiftMessageSegue` from anywhere provided that you have a view controller to segue from. This might help https://github.com/SwiftKickMobile/SwiftMessages/issues/302.
