### ISSUE TITLE
SwiftMessages.Config has no member presentationContext!

### ISSUE THREAD

**Issue by MrShafiee** [SwiftKickMobile/SwiftMessages#304]
Dear @Coeur,
Thanks for your useful Library, I used SwiftMessages on Xcode 10.1 and Swift 4.2 everything was okey, but now when I run the same code on Xcode 10.2 and swift 5, app crash every time that SwiftMessage was shown!

The only difference is that when I update Xcode and use swift 5, This error appear:
"_Value of type 'SwiftMessages.Config' has no member 'presentationContext'; did you mean 'presentationStyle'?_"

My Code is:
```
static func showNotifyMessage(_ Mode:Theme,_ Title:String,_ body:String )  {
        let view = MessageView.viewFromNib(layout: .messageView)

        view.titleLabel?.font = UIFont.mainContent
        view.bodyLabel?.font = UIFont.mainContent
        view.button?.isHidden = true
        
        view.configureTheme(Mode)
        var config = SwiftMessages.Config()
        config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)
        /** ==> I HAVE ERROR IN ABOVE LINE **/

        let iconText :String!
        switch Mode {
        case .info:
            iconText = showNotifyMessageIcon.infoIcon.rawValue
        case .success:
            iconText = showNotifyMessageIcon.successIcon.rawValue
        case .warning:
            iconText = showNotifyMessageIcon.warningIcon.rawValue
        default:
            iconText = showNotifyMessageIcon.errorIcon.rawValue
        }

        view.configureContent(title: Title, body: body, iconText: iconText)
        SwiftMessages.show(config: config, view: view)
    }
```

But when I use SwiftMessage without Config property it works fine!
What should I do for this issue?

Thanks

**Comment by Coeur** [comment]
Dear MrShafiee , it is not my library at all. It's @wtmoose 's.
I use this lib under Swift 5 on App Store without issues.
My actual production code is:
```swift
SwiftMessages.defaultConfig.presentationContext = .window(windowLevel: .statusBar)
```

Now, seeing as you're still using UIWindowLevelStatusBar, it seems to me that you did not fully upgrade to the latest version.

Please double check:
- your installed version written in Podfile.lock
- your Application target Swift version
- your Pods -> SwiftMessage target Swift version

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/issues/229
