### ISSUE TITLE
Attach SwiftMessages to the bottom of navigation controller but above the tab bar

### ISSUE THREAD

**Issue by HebaAtallah** [SwiftKickMobile/SwiftMessages#305]
I need to display a message at the bottom of the Navigation Controller but above the tab bar.

**Comment by wtmoose** [comment]
Have you checked the demo app?

**Comment by HebaAtallah** [comment]
Yes, I did.

**Comment by wtmoose** [comment]
Could you elaborate? As far as I can tell, the demo app does what you’re asking for.

**Comment by HebaAtallah** [comment]
I wasn't adding the stack view to the nib file, so it causes many issues
