### ISSUE TITLE
I can't tap inside the message 

### ISSUE THREAD

**Issue by HebaAtallah** [SwiftKickMobile/SwiftMessages#306]
The message appears but when I click on it, it clicks the behind view

**Comment by wtmoose** [comment]
Could you elaborate? Tips for asking questions: https://stackoverflow.com/help/how-to-ask

**Comment by HebaAtallah** [comment]
I've displayed the message above table view, but when I click on the message to invoke the tap handler the view that behind the message gets clicked

**Comment by wtmoose** [comment]
This isn't a common problem, so I need you to provide enough information to understand the unusual thing that you're doing.

You can run the sample app and see that taps on messages don't go to the underlying table view.

Can you attach a sample project?
