### ISSUE TITLE
please swift5.0

### ISSUE THREAD

**Issue by lixiang1994** [SwiftKickMobile/SwiftMessages#307]

**Comment by lixiang1994** [comment]
spec.swift_version    = '5.0'

**Comment by Coeur** [comment]
There is a branch for it: https://github.com/SwiftKickMobile/SwiftMessages/tree/work/swift5.
So simply have this in your Podfile:
```ruby
pod 'SwiftMessages', :git => 'https://github.com/SwiftKickMobile/SwiftMessages.git', :branch => 'work/swift5'
```

**Comment by lixiang1994** [comment]
@Coeur Thank you

**Comment by wtmoose** [comment]
@lixiang1994 sorry, I thought I commented about the Swift 5 branch when I closed this.

**Comment by Coeur** [comment]
@wtmoose I believe it's fine to merge it to master already, independently from your decision of when to make next release. Or if your concern is compatibility with Xcode 10.1, then please merge everything else except the podspec change (keeping it at Swift 4.2).

**Comment by wtmoose** [comment]
Yep. Done.
