### ISSUE TITLE
Scrollable Message 

### ISSUE THREAD

**Issue by Kurt57** [SwiftKickMobile/SwiftMessages#309]
Hi first of all cool module.

I'm showing and SwiftMessage which is greater than the device height.

Therefore the message ist > the device height. But it isn't scrollable. Is that right behavior how it is implemented now? Is there no scroll option vor the whole message ?

**Comment by wtmoose** [comment]
None of the views that come with SwiftMessages contain scroll views. However, you can display any arbitrary view, so feel free to roll your own. IMO, the easiest approach is to copy one of the nib files that most closely matches the layout you want and add a scroll view to it. If you share your designs and/or a prototype, I can give you more specific suggestions.
