### ISSUE TITLE
Could not load the "cancel" image

### ISSUE THREAD

**Issue by C-Wedge** [SwiftKickMobile/SwiftMessages#31]
Good day, everything had been working perfectly for a few weeks but after the recent Xcode update I keep getting the following error: Could not load the "cancel" image referenced from a nib in the bundle with identifier "org.cocoapods.SwiftMessages"
fatal error: unexpectedly found nil while unwrapping an Optional value

If I supplement the cancel image with another and make all the relevant changes, the error simply persists with the new image too.

Any recent issues you're aware of in this regard? This is not in production, simply run within the Simulator. Cheers

**Comment by C-Wedge** [comment]
Ok, found the issue. After the update, it seems that images.xcassets under Resources was not assigned to SwiftMessages within Target Membership anymore. As soon as I specified that, the App ran as per normal. Cheers

**Comment by wtmoose** [comment]
Good to hear you fixed it. Are you modifying the SwiftMessages library directly? Rather than doing that, I'd recommend copying the nib file into your project and making your customizations there. SwiftMessages looks for nib files in the main bundle first.

**Comment by C-Wedge** [comment]
Ok great, will do. Thanks
