### ISSUE TITLE
6.0.3 Pod

### ISSUE THREAD

**Issue by JakeRL** [SwiftKickMobile/SwiftMessages#312]
It looks like this project was updated for Swift 5 and the Podspec was updated to 6.0.3 but the highest version I'm able to update to in my project is 6.0.2. Are you guys planning on pushing up the newest podspec version?

**Comment by wtmoose** [comment]
Yes when 6.0.3 is released in the next couple of weeks.

**Comment by JakeRL** [comment]
Got it. Thanks for the update.


On May 6, 2019 at 5:20:25 PM, Timothy Moose (notifications@github.com)
wrote:

Yes when 6.0.3 is released in the next couple of weeks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SwiftKickMobile/SwiftMessages/issues/312#issuecomment-489804265>,
or mute the thread

**Comment by wtmoose** [comment]
7.0.0 is released
