### ISSUE TITLE
Fix warnings Swift 5.0

### ISSUE THREAD

**Issue by delbyze** [SwiftKickMobile/SwiftMessages#315]
Please, can you fix warnings for Swift 5.0 ?

<img width="858" alt="Capture d’écran 2019-05-16 à 14 08 29" src="https://user-images.githubusercontent.com/38207269/57852716-3069ce00-77e4-11e9-8b34-14f808ef5f2b.png">

**Comment by wtmoose** [comment]
Closing as duplicate
