### ISSUE TITLE
Hide algorithm

### ISSUE THREAD

**Issue by Yurssoft** [SwiftKickMobile/SwiftMessages#32]
SwiftMessages implements Identifiable like this:

```Swift
open var id: String {
        return "MessageView:title=\(titleLabel?.text), body=\(bodyLabel?.text)"
    }
```

For my usage when user taps on refresh button and internet connection isn't present user needs to know if refresh succesful.
Refresh working very fast, and previous message haven't been removed yet from the queue.
When new message (the same, about internet connection) is generated it is deleted from queue because id property is generated from title and body.

The question is how to add two messages to queue with the same title and body?

My thought is maybe make id property settable?

**Comment by wtmoose** [comment]
I could add an option on `SwiftMessages.Config` to make ignoring duplicates configurable. But why not dismiss the existing message immediately before showing the new one using `SwiftMessages.hide(id:)`?

**Comment by Yurssoft** [comment]
Yes, I have tried it, and as I said:
I have one message "Cannot refresh". User taps try again. Another message created with the same title and body "Cannot refresh". Show method is called. Show method checks for messages with same ids and removes it. Message 1 with title isn't removed yet as animations occur. Message 2 will be never shown as has been deleted. 

In another words when I have checked for network 2 times and created two messages with "Cannot refresh" second messaged will not be shown as 
```Swift
    func enqueue(presenter: Presenter) {
        if let id = presenter.id {
            if current?.id == id { return } //Here we will have two same ids
            if queue.filter({ $0.id == id }).count > 0 { return }
        }
        queue.append(presenter)
        dequeueNext()
    }
```
(SwiftMessages.swift (line 318))

[Gif](http://giphy.com/gifs/26hisbRb5JDkIbwOY)

Thoughts?

**Comment by wtmoose** [comment]
Try updating to 3.0.3 and adding this line somewhere:

    SwiftMessages.defaultConfig.ignoreDuplicates = false

**Comment by Yurssoft** [comment]
Thanks for looking into this
Maybe I am wrong, but  
```Swift
SwiftMessages.defaultConfig.ignoreDuplicates = false
```
didn't work.
Only when I added it to presenter it did work

```Swift
var messageConfig = SwiftMessages.Config()
messageConfig.ignoreDuplicates = false
SwiftMessages.show(config: messageConfig, view: message)
```
It seems that presenter somehow takes value only from local config.
Thanks you very much for taking actions so fast! I am impressed 👍
Have a great day :)

**Comment by wtmoose** [comment]
The default config is used when you call `show()` without a `config` argument:

    public func show(view: UIView) {
        show(config: defaultConfig, view: view)
    }

Glad you got it working, though.

**Comment by Yurssoft** [comment]
Makes sense, thanks :)
