### ISSUE TITLE
Crash on custom config.

### ISSUE THREAD

**Issue by tuppaware** [SwiftKickMobile/SwiftMessages#321]
Seems to be related to particular version. 
Project is set at swift 4.0 because of other dependencies. 
But trying to use SwiftMessages 5,6,7 causes crashes when I create a custom config ?
If there a version I can use that will support < swift 4 ?

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/releases/tag/4.0.0
