### ISSUE TITLE
CustomNib forever not working

### ISSUE THREAD

**Issue by lcuiandlc** [SwiftKickMobile/SwiftMessages#322]
static func demoCustomNib() {
        let view: TacoDialogView = try! SwiftMessages.viewFromNib()
        view.configureDropShadow()
        view.getTacosAction = { _ in SwiftMessages.hide() }
        view.cancelAction = { SwiftMessages.hide() }
        var config = SwiftMessages.defaultConfig
        config.presentationContext = .window(windowLevel: UIWindow.Level.statusBar)
        config.duration = .forever
        config.presentationStyle = .bottom
        config.dimMode = .gray(interactive: true)
        SwiftMessages.show(config: config, view: view)
    }

  config.duration = .forever    not working.

**Comment by wtmoose** [comment]
Put a breakpoint in `SwiftMessages.internalHide(id:)` to find out what is causing the message to hide. This question comes up occasionally and it always turns out that people are accidentally calling `hide` somewhere.
