### ISSUE TITLE
xCode 11 & Swift 5 warnings

### ISSUE THREAD

**Issue by Idomo** [SwiftKickMobile/SwiftMessages#323]
After updating to xCode 11 & Swift 5, I'm getting those warnings:
`Coercion of implicitly unwrappable value of type 'SideMenuTransition?' to 'Any' does not unwrap optional`

I'm really not sure why is that, 'cause the value is from type of `SideMenuTransition!` and not `SideMenuTransition?` as the warning says.

Looks like casting all of those targets to `Any` silenced the warnings, but I guess there is a better solution.

![image](https://user-images.githubusercontent.com/26777129/59600565-3700a380-910a-11e9-991c-8d7d40436801.png)

**Comment by wtmoose** [comment]
I’ll take a look at Xcode 11 soonish, so I’ll leave this ticket open as a placeholder.

**Comment by Idomo** [comment]
@wtmoose Great, you may also look for analyzer warnings/errors (Shift + Cmd + B)

**Comment by giofid** [comment]
@Idomo, @wtmoose Is this issue related to `SwiftMessages`?  It seems to concern the [SideMenu](https://github.com/jonkykong/SideMenu) library, instead.

**Comment by wtmoose** [comment]
@giofid LOL, yeah
