### ISSUE TITLE
Incorrect Comment for `KeyboardTrackingView.isPaused`

### ISSUE THREAD

**Issue by chamitha** [SwiftKickMobile/SwiftMessages#324]
The comment for the `isPaused` property of the `KeyboardTrackingView.swift` is incorrect. It must read

Setting `isPaused = false` in `viewWillAppear` and `isPaused = true` in `viewWillDisappear` usually works

**Comment by ricsantos** [comment]
Looks like this was fixed in 0b8e7b4
