### ISSUE TITLE
Custom view border color

### ISSUE THREAD

**Issue by appleshine** [SwiftKickMobile/SwiftMessages#326]
Hello, not sure if this is a silly question but how can I set the border color for my custom message view?

I have tried layer.borderUIColor and layer.borderColor but both doesn't work. I did set my layer.borderWidth to 2.

I have also tried setting 
```
view.borderColor = UIColor.red
view.layer.borderColor = UIColor.red.cgColor
```

But it all doesn't work :( Dont know what am I doing wrong

**Comment by wtmoose** [comment]
You gotta set a border width

**Comment by appleshine** [comment]
As said above I did set the layer.borderWidth to 2

**Comment by appleshine** [comment]
I fixed the problem by using IBDesignable instead. Thanks though :)

**Comment by martynovskij** [comment]
> You gotta set a border width

It is not works.

**Comment by martynovskij** [comment]
I fixed the problem by changing backgroundView.layer (not view.layer):
`
view.backgroundView.layer.borderWidth = 3.0
view.backgroundView.layer.borderColor = UIColor.white.cgColor
`
