### ISSUE TITLE
bulid fail

### ISSUE THREAD

**Issue by nizenyang** [SwiftKickMobile/SwiftMessages#329]
![image](https://user-images.githubusercontent.com/8390188/61678384-3d032900-ad35-11e9-9460-75a6c9f44e78.png)
please update for xcode version 10.3

**Comment by suraphanL** [comment]
@nizenyang  Rebooting my mac solved it.

**Comment by nizenyang** [comment]
> @nizenyang Rebooting my mac solved it.

thank you very much
