### ISSUE TITLE
how to set shadow?

### ISSUE THREAD

**Issue by azureplus** [SwiftKickMobile/SwiftMessages#334]
open func configureDropShadow() {
        layer.shadowColor = UIColor.black.cgColor
        layer.shadowOffset = CGSize(width: 0.0, height: 2.0)
        layer.shadowRadius = 6.0
        layer.shadowOpacity = 0.4
        layer.masksToBounds = false
        updateShadowPath()
    }

    /// A convenience function to turn off drop shadow
    open func configureNoDropShadow() {
        layer.shadowOpacity = 0
    }

    private func updateShadowPath() {
}

private should change to public

**Comment by wtmoose** [comment]
Have you seen #318? Otherwise, why do you need access to `updateShadowPath`?

**Comment by azureplus** [comment]
@wtmoose  thanks
