### ISSUE TITLE
Value of type 'UIWindow' has no member 'windowScene'; did you mean 'windowLevel'?

### ISSUE THREAD

**Issue by ch-muhammad-adil** [SwiftKickMobile/SwiftMessages#342]
I have upgraded my application's swift version from 4 to 5. Everything is working fine if i remove this library. Here are some errors which is being generated from SwiftMessages source files i am not sure what is the main reason as i have tried many ways around the internet like cleaning, installing again everything. I will really appreciate if you respond me as soon as possible because this app is in production and i have to release the build as soon as possible after these upgrades. 

`Use of undeclared type 'UIWindowScene' `
<img width="735" alt="Screenshot 2019-09-20 at 10 07 08 PM" src="https://user-images.githubusercontent.com/8264639/65345158-0477b280-dbf3-11e9-9a62-e02f4ca10a6f.png">

<img width="996" alt="Screenshot 2019-09-20 at 10 01 26 PM" src="https://user-images.githubusercontent.com/8264639/65345067-cc706f80-dbf2-11e9-83ad-fa6c79301afc.png">

<img width="273" alt="Screenshot 2019-09-20 at 10 01 40 PM" src="https://user-images.githubusercontent.com/8264639/65345065-cc706f80-dbf2-11e9-8127-d38bbacaa580.png">

please let me know if more details are required.

**Comment by wtmoose** [comment]
What version of Xcode are you on?

**Comment by ch-muhammad-adil** [comment]
I am using xCode Version 10.3

**Comment by ch-muhammad-adil** [comment]
what xCode version is required to resolve this issue ?

**Comment by wtmoose** [comment]
Xcode 11. You can downgrade SwiftMessages to 7.0.0 for Xcode 10
