### ISSUE TITLE
iOS 13 issue

### ISSUE THREAD

**Issue by petrykDima** [SwiftKickMobile/SwiftMessages#346]
It isn't showing on iOS 13. In iOS 12 code works great 

`
let view = MessageView.viewFromNib(layout: .statusLine)
        view.configureTheme(.error)
        view.configureContent(title: "Warning", body: withStatus, iconText: "")
        (view.backgroundView as? CornerRoundingView)?.backgroundColor = UIColor.darkRedCustom
        SwiftMessages.show(view: view)
`

**Comment by wtmoose** [comment]
Are you using a `SceneManager`? If so, you need to update to 7.0.1.

**Comment by dr-coton** [comment]
I have the same problem. 
version : 7.0.1

**Comment by wtmoose** [comment]
@dr-coton does the demo app work for you?

**Comment by wtmoose** [comment]
Be sure to clean your workspace before building if you’re upgrading to 7.0.1

**Comment by dr-coton** [comment]
Oh.. Thanks..
This Issue fixed after "clean build"

**Comment by wtmoose** [comment]
No reply from OP. Closing.
