### ISSUE TITLE
Xcode 11 - SwiftMessagesSegue dismiss on contentview interaction

### ISSUE THREAD

**Issue by MiguelNegri** [SwiftKickMobile/SwiftMessages#347]
After updating to Xcode 11 there seems to be a problem when calling a UIViewController using class that inherits SwiftMessagesSegue. 
        
Setting dimMode.interactive = true will dismiss the controller with with any type of interaction.
Exemples: Taping the view, scrolling 
        
Setting dimMode.interactive = false works fine, but forces the need of a button to dismiss

Sample 
[SwiftMessagesInteractive.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/3643855/SwiftMessagesInteractive.zip)

Versions Used:
- Xcode 11
- Simulator iPhone 11 Pro Max
- SwiftMessages version 7.0.1

**Comment by wtmoose** [comment]
Thanks for attaching a sample app. However, I can't reproduce the problem you're describing. In the attached video, you can see me tap the red button then scroll the text view. Any suggestions how I can reproduce it?

/Users/tim/Downloads/RPReplay_Final1569505872.MP4

**Comment by MiguelNegri** [comment]
Thanks for the reply
Went to reproduce the the problem and now is working fine
Probably some random bug after update in simulator.

Closing this issue
