### ISSUE TITLE
Use of undeclared type 'UIWindowScene'

### ISSUE THREAD

**Issue by naissa12** [SwiftKickMobile/SwiftMessages#351]
When I try to build my Xcode application, I get the error `Use of undeclared type 'UIWindowScene'` on line 44 of WindowViewController.

I'm using Xcode V10.2 IOS V 10.2

Can someone please help?

**Comment by wtmoose** [comment]
Upgrade to Xcode 11 or downgrade to SwiftMessages 7.0.0.
