### ISSUE TITLE
Accessibility for View Controllers Presented Via SwiftMessagesSegue

### ISSUE THREAD

**Issue by patmalt** [SwiftKickMobile/SwiftMessages#352]
`SwiftMessagesSegue`'s `messageView` is a `BaseView`, and since `BaseView` does not conform to `AccessibleMessage`, presented view controllers will not be accessible via Accessibility Inspector or Voice Over.

I implemented a subclass of `BaseView` that does conform to `AccessibleMessage`, and set it to the `messageView` property of `SwiftMessagesSegue`. This should work in most cases...

Expect where the presented view controller is wrapped inside of a `UINavigationController`.

During the `install` phase of `Presenter`, the `UINavigationController`'s rootViewController is not added to the `messageView`'s view hierarchy yet, and the elements are also not exposed.

Any thoughts or suggestions?

**Comment by wtmoose** [comment]
I’m not sure I’d use `AccessibleMessage` with view controllers at all due to their complexity. `AccessibleMessage` was meant to help improve voice over for simple views, such as reading the title + body out as a single unit. Was there a specific reason you wanted to use `AccessibleMessage`?

**Comment by patmalt** [comment]
Yes, so we can use Voice Over on view controllers we present with `SwiftMessagesSegue`

**Comment by wtmoose** [comment]
Hmm. I think ideally you’d get the view controller’s default voice over behavior. I’ll need to look into it.

**Comment by patmalt** [comment]
I do not believe this to be true

**Comment by dtashkandi** [comment]
@patmalt can you please share your subclass of BaseView?

**Comment by dtashkandi** [comment]
@patmalt thanks!

**Comment by wtmoose** [comment]
@patmalt @dtashkandi I pushed a fix for this to the head of `master` if you want to try it out and let me know. 

Previously, if a view that didn't adopt `AccessibleMessage` was ignored by Voice Over. With meh fix, these views are not ignored by Voice Over and are responsible for their own accessibility. I think this is the ideal behavior for view controllers. I don't recommend putting view controllers behind the `AccessibleMessage` protocol, but you can do that if you want to (as you've done above).

**Comment by patmalt** [comment]
This fix worked for me! Thanks

**Comment by wtmoose** [comment]
Great. Will close when I release the change.

**Comment by wtmoose** [comment]
Included in 8.0.0 release
