### ISSUE TITLE
changing the hight of presented view 

### ISSUE THREAD

**Issue by embassem** [SwiftKickMobile/SwiftMessages#353]
I'd like to change the height when navigating.
I'm presenting navigation Controller with VC1  as root  with  as a bottom Message with the height of 350
when some action in VC1 happened it will push VC2 witch should  change the height to 500 
if push VC3  height is 400
if pop to VC1 height is 350 again 
and so on
is this behavior applicable?

**Comment by wtmoose** [comment]
SwiftMessages isn’t going to automatically perform animated height changes for you, but you should be able to do your own animations. Navigation controllers don’t naturally size to fit the content of their child view controllers. So you’ll have to explicitly set and animate the `UINavigationController`‘s height.0
