### ISSUE TITLE
[name conflict] SwiftUI has 'Identifiable' protocol now

### ISSUE THREAD

**Issue by pateljay43** [SwiftKickMobile/SwiftMessages#361]
Check the Apple's Identifiable protocol: https://developer.apple.com/documentation/swift/identifiable

**Comment by wtmoose** [comment]
I'm aware. Are you having a specific problem?

**Comment by pateljay43** [comment]
I was about to start using your library but this is something I have to test and play with to find out is this is a blocker issue or not.

**Comment by pateljay43** [comment]
I don't use SwiftUI in my project. hence I cannot confirm this name conflict caused an issue or not. But in either case, I think there should be a way to use proper `Identifiable` protocol by prefixing with module name directly.

Hence I will close this issue.

**Comment by wtmoose** [comment]
Yes, I agree this ticket should be closed if there's not a concrete issue.
