### ISSUE TITLE
Swift Package Manager installation option

### ISSUE THREAD

**Issue by saormart** [SwiftKickMobile/SwiftMessages#362]
Is it possible to make it compatible with Swift Package Manager ?
Thanks!

**Comment by wtmoose** [comment]
I don’t think so. My understanding is that resource bundles aren’t supported yet.

**Comment by davbeck** [comment]
Looks like resources have been added to Swift 5.3 (not released yet).

Beyond that, having converted several projects to SPM, I can tell you that the biggest challenge converting from Cocoapods is handling subspaces. CP combines all subspecs into a single framework/module. SPM supports multiple products, but they each will have their own module.

**Comment by wtmoose** [comment]
@davbeck that sounds promising. Thanks for the heads up!

**Comment by knothed** [comment]
Have a look at [this](https://github.com/SwiftKickMobile/SwiftMessages/pull/395) – it is a temporary solution until Swift 5.3 comes out.

**Comment by wtmoose** [comment]
Preliminary support added in 8.0.2
