### ISSUE TITLE
Assets.car

### ISSUE THREAD

**Issue by seniorAyman** [SwiftKickMobile/SwiftMessages#364]
RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.SwiftMessages'
I am getting this error when using this code with Xcode 11.1 and swift 5 and iOS 12

let messageView: MessageView = MessageView.viewFromNib(layout: .cardView)
messageView.configureTheme(.error)
messageView.titleLabel?.text = "test"
messageView.bodyLabel?.text = "body mddcdc"
messageView.button?.setTitle("ok", for: .normal)
SwiftMessages.show(view: messageView)

**Comment by wtmoose** [comment]
Got a stack trace? SwiftMessages doesn’t use asset catalogs due to occasional crash reports, so I don’t know how this error would occur.

**Comment by seniorAyman** [comment]
thread #1, queue = 'com.apple.main-thread', stop reason = step over
  * frame #0: 0x0000000103e1d1cd testingpods`notificationsViewController.viewDidLoad(self=0x00007f8454f5c6c0) at notificationsViewController.swift:57:26
    frame #1: 0x0000000103e1ddbb testingpods`@objc notificationsViewController.viewDidLoad() at <compiler-generated>:0
    frame #2: 0x00007fff46f03d96 UIKitCore`-[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
    frame #3: 0x00007fff46f08cef UIKitCore`-[UIViewController loadViewIfRequired] + 1084
    frame #4: 0x00007fff46f0910c UIKitCore`-[UIViewController view] + 27
    frame #5: 0x00007fff46e58fb1 UIKitCore`-[UINavigationController _startCustomTransition:] + 1039
    frame #6: 0x00007fff46e6e3d0 UIKitCore`-[UINavigationController _startDeferredTransitionIfNeeded:] + 698
    frame #7: 0x00007fff46e6f7e5 UIKitCore`-[UINavigationController __viewWillLayoutSubviews] + 150
    frame #8: 0x00007fff46e51127 UIKitCore`-[UILayoutContainerView layoutSubviews] + 217
    frame #9: 0x00007fff47a52ad5 UIKitCore`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
    frame #10: 0x00007fff2b06e91d QuartzCore`-[CALayer layoutSublayers] + 255
    frame #11: 0x00007fff2b073323 QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 517
    frame #12: 0x00007fff2b07fa7c QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 80
    frame #13: 0x00007fff2afc6e54 QuartzCore`CA::Context::commit_transaction(CA::Transaction*, double) + 324
    frame #14: 0x00007fff2affc32f QuartzCore`CA::Transaction::commit() + 643
    frame #15: 0x00007fff475a23bf UIKitCore`_afterCACommitHandler + 160
    frame #16: 0x00007fff23b0c667 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    frame #17: 0x00007fff23b070fe CoreFoundation`__CFRunLoopDoObservers + 430
    frame #18: 0x00007fff23b0777a CoreFoundation`__CFRunLoopRun + 1514
    frame #19: 0x00007fff23b06e66 CoreFoundation`CFRunLoopRunSpecific + 438
    frame #20: 0x00007fff38346bb0 GraphicsServices`GSEventRunModal + 65
    frame #21: 0x00007fff47578dd0 UIKitCore`UIApplicationMain + 1621
    frame #22: 0x0000000103e33fab testingpods`main at AppDelegate.swift:12:7
    frame #23: 0x00007fff516ecd29 libdyld.dylib`start + 1

**Comment by seniorAyman** [comment]
it was a bug in Xcode
I just update it and now working fine
regards
