### ISSUE TITLE
The drop - down is out of position

### ISSUE THREAD

**Issue by nizenyang** [SwiftKickMobile/SwiftMessages#370]
![image](https://user-images.githubusercontent.com/8390188/71606503-4a59f480-2bac-11ea-895d-ebb144fe927d.png)
Hi, how come when my view pops up from the top, it's at -5 instead of 0
![image](https://user-images.githubusercontent.com/8390188/71606526-855c2800-2bac-11ea-889b-a4c4168a820d.png)

**Comment by wtmoose** [comment]
Because it is a spring animation and offsetting the Y position by 5 prevents a gap between the edge of the view and the top of the screen being visible during the bounce. There are ways to turn that off, but it is probably simpler to pad the top of your view by 5pt.

**Comment by nizenyang** [comment]
> Because it is a spring animation and offsetting the Y position by 5 prevents a gap between the edge of the view and the top of the screen being visible during the bounce. There are ways to turn that off, but it is probably simpler to pad the top of your view by 5pt.

I can understand that there will be offsets for the animation effect, but why doesn't the position return to the original normal position at the end of the animation? I think the end user might want to return to the original position at the end of the animation

**Comment by wtmoose** [comment]
b > a > 0

![IMG_0098](https://user-images.githubusercontent.com/2529176/71609215-662dae00-2b4c-11ea-8721-457439a6b8d8.jpeg)

Why do you think the end user cares if there is unseen top padding on your view?

**Comment by nizenyang** [comment]
> b > a > 0
> 
> ![IMG_0098](https://user-images.githubusercontent.com/2529176/71609215-662dae00-2b4c-11ea-8721-457439a6b8d8.jpeg)
> 
> Why do you think the end user cares if there is unseen top padding on your view?

I see what you mean. Thank you for answering my questions
