### ISSUE TITLE
Text is wrapping when still we have sufficient space to display full text.

### ISSUE THREAD

**Issue by ashishonmobile** [SwiftKickMobile/SwiftMessages#371]
<img width="280" alt="Screenshot 2020-01-04 00 58 32" src="https://user-images.githubusercontent.com/8134811/71744521-897a9500-2e8d-11ea-9c99-93f5094f76b1.png">

Is there anyone who has an idea why the text is getting wrapped.

**Comment by wtmoose** [comment]
Looks fine in the Demo app running on the smallest possible simulator (iPhone SE). So you need to give more info.

![Simulator Screen Shot - iPhone SE - 2020-01-03 at 13 40 26](https://user-images.githubusercontent.com/2529176/71745022-9e740b80-2e2e-11ea-9458-641a78fdb108.png)

**Comment by ashishonmobile** [comment]
@wtmoose Thanks for your reply I also too run the demo app. and It is working fine.

But I do not know why it is not working in my application.

Regards,
Ashish

**Comment by wtmoose** [comment]
OK. Reopen if you're able to provide any more useful info.
