### ISSUE TITLE
Disable background tap to dismiss

### ISSUE THREAD

**Issue by sleekuser** [SwiftKickMobile/SwiftMessages#374]
Is there a way to disable dismiss behavior on background tap while using SwiftMessagesSegue? Setting up `interactiveHide = false` only disables pan gesture. Thank you!!

**Comment by wtmoose** [comment]
`dimMode = .gray(interactive: false)`

**Comment by sleekuser** [comment]
@wtmoose Awesome!! Such a quick reply, thanks
