### ISSUE TITLE
Display only the body

### ISSUE THREAD

**Issue by infinigent-solutions** [SwiftKickMobile/SwiftMessages#377]
Here's my code:
```
class func showErrorMessage(message: String) {

	if !isStringEmpty(aString: message) {

		let messageView = MessageView.viewFromNib(layout: MessageView.Layout.cardView)
		messageView.configureTheme(Theme.error)
		messageView.configureContent(body: message)
                messageView.iconLabel?.isHidden = true
		messageView.iconImageView?.isHidden = true
		messageView.titleLabel?.isHidden = true
		messageView.button?.isHidden = true

		var config = SwiftMessages.Config()
		config.presentationStyle = SwiftMessages.PresentationStyle.bottom
		config.presentationContext = SwiftMessages.PresentationContext.window(windowLevel: UIWindow.Level.normal)
		config.duration = SwiftMessages.Duration.automatic
		config.dimMode = SwiftMessages.DimMode.none

		SwiftMessages.show(config: config, view: messageView)

	}

}
```

This is how it looks like:
![SwiftMessages](https://user-images.githubusercontent.com/40767033/74107713-e528f400-4b98-11ea-8b9b-4d7c90d83e00.png)

Please help to make the text appear in full width

**Comment by wtmoose** [comment]
Can you reproduce it in the demo app? I reproduced your configuration in the demo app and it looks fine. So I'd need more info from your end, such as a sample project that I can try.

![IMG_0658](https://user-images.githubusercontent.com/2529176/74107824-87b18a80-4b39-11ea-8616-2862e1fa96fb.PNG)

Also curious about this statement?

````swift
!isStringEmpty(aString: message) {
}
````

Isn't the normal way to do this?

````swift
guard !message.isEmpty else { return }
````
````

**Comment by infinigent-solutions** [comment]
@wtmoose The code in the demo works, however, can you please tell me where am I going wrong in my code as I'm using the latest pods for this

**Comment by wtmoose** [comment]
Here's a sample project containing your code and the layout looks correct.

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/4192737/SwiftMessagesTest.zip)

You'll need to give me a way to reproduce your problem, preferably by attaching a sample project.
