### ISSUE TITLE
Build error on iOS 13 and SWIFTMESSAGES_APP_EXTENSIONS enabled case

### ISSUE THREAD

**Issue by joohae-kim** [SwiftKickMobile/SwiftMessages#378]
I got `'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.` error on Presenter:install()

```
guard let containerView = presentationContext.viewValue() else { return }
if let windowViewController = presentationContext.viewControllerValue() as? WindowViewController {
    if #available(iOS 13, *) {
        let scene = UIApplication.shared.keyWindow?.windowScene       // <- HERE!
        windowViewController.install(becomeKey: becomeKeyWindow, scene: scene)
    } else {
        windowViewController.install(becomeKey: becomeKeyWindow)
    }
}
```

**Comment by wtmoose** [comment]
Thanks for bringing this up!

**Comment by wtmoose** [comment]
Sorry for not addressing this in a timely manner. I don't do iMessage extensions, so I had to dig in a little bit. It seems like you're trying to present your message in its own window. I don't think you can do that. You should be using:

````swift
config.presentationContext = .viewController(...)
````

or

````swift
config.presentationContext = .view(...)
````

I wasn't able to reproduce your error though in the iMessageExtensionDemo sample app. Let me know if you still need help with this and I'll see what I can do.
