### ISSUE TITLE
Extending MessageView / Custom Xib - customization doesn't seem to work

### ISSUE THREAD

**Issue by willnix86** [SwiftKickMobile/SwiftMessages#379]
Following the instructions in the docs, I created a copy of the 'Card View' xib, then removed the image/label etc, and changed it's height and width to 510, then added a Collection View as it's single element.

I wired up the outlets etc into a subclass of MessageView (and set up the CollectionView as needed) but when I run the code, all I get is a blank view the same height/width as the original Card View.

I know the collection view is trying to do it's thing, as I will see things printed to the console inside the various CV datasource 'numberOfSections' and 'numberOfItems' functions (but not the 'cellForItemAt' or flow layout functions).

I'd have thought, at the least, the custom view would load at 510 height and width...?

**Comment by wtmoose** [comment]
Can you attach your nib?

**Comment by willnix86** [comment]
I actually think I've got it working - needed to add height/width constraints to the Corner rounding view.

It's now just breaking because it's failing to register my custom cv cell, but that's my issue not yours :-)

Closing the issue now!
