### ISSUE TITLE
Can I get a signal when message view is hiding?

### ISSUE THREAD

**Issue by mkjwa** [SwiftKickMobile/SwiftMessages#380]
Is it possible to get a signal for hiding a message view?

I need to get a signal after hiding message view. Message View is showing by setting duration.
I want to show popup after message view is hidden, but can't get a signal.

**Comment by mkjwa** [comment]
I found a configuration. SwiftMessages is a very awful solution.


    ```
    config.eventListeners.append() { event in
            if case .didHide = event {
      
            }
        }
```

**Comment by wtmoose** [comment]
Awful?
