### ISSUE TITLE
Show content from safe area

### ISSUE THREAD

**Issue by StackHelp** [SwiftKickMobile/SwiftMessages#383]
Right now I got the content like below using custom nib. From bottom it doesn't count for safe area space.
![Screenshot 2020-03-27 at 4 35 29 PM](https://user-images.githubusercontent.com/41230403/77750156-53dae780-7049-11ea-8c01-cd2c2b1ec9ff.png)

I want it to cover space from safe area lke below image
![Simulator Screen Shot - iPhone 11 - 2020-03-23 at 12 09 44](https://user-images.githubusercontent.com/41230403/77750172-59383200-7049-11ea-95b5-ede574b3a247.png)

Here is my code

```
        let view: UndoPostView = try! SwiftMessages.viewFromNib()
        var config = SwiftMessages.defaultConfig
        config.presentationContext = .window(windowLevel: UIWindow.Level.statusBar)
        config.presentationStyle = .bottom
        config.duration = .seconds(seconds: 4)
        SwiftMessages.show(config: config, view: view)

```

**Comment by wtmoose** [comment]
Attach your nib file please

**Comment by StackHelp** [comment]
Here it is https://we.tl/t-zQcBJGxEPK

**Comment by StackHelp** [comment]
@wtmoose Hi I got it to work by changed bottom constraint to safe area instead it was attached with superview. Thanks for your time.
