### ISSUE TITLE
Crash when i use SwiftMessages.defaultConfig

### ISSUE THREAD

**Issue by hemendraggohel** [SwiftKickMobile/SwiftMessages#384]
Working fine with below code.  
          let view = MessageView.viewFromNib(layout: .cardView)
            // Theme message elements with the warning style.
            view.configureTheme(.error)
            view.configureDropShadow()
            view.configureContent(title: "Error", body: "Title")
            view.button?.isHidden = true
            // Show the message.
            SwiftMessages.show(view: view)

When i add 

SwiftMessages.defaultConfig.presentationStyle = .bottom

then it is crashing with latest OS 13.3.1.

**Comment by wtmoose** [comment]
That seems unlikely. Whats is the stack trace?

**Comment by mojidabckuu** [comment]
@wtmoose happening happening to me. This line causing the crash
```swift
let arrayOfViews = resolvedBundle.loadNibNamed(name, owner: filesOwner, options: nil) ?? []
```
exception is
```
[MessagesView 0x7f9199c4ef50> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key statusBarOffset.
```

**Comment by mojidabckuu** [comment]
Ok, figured out. In my case it was too big update jump and seems `statusBarOffset` is the legacy.
