### ISSUE TITLE
No code signing error

### ISSUE THREAD

**Issue by vivek4292** [SwiftKickMobile/SwiftMessages#386]
I've added SwiftMessage manually to my project bundle. I'm able to run it on a simulator only. It's not letting install on real devices. 
<img width="516" alt="Screenshot 2020-04-14 at 4 59 11 PM" src="https://user-images.githubusercontent.com/34335017/79220383-82422a80-7e71-11ea-860e-f15909968139.png">

Build log attached below
<img width="898" alt="Screenshot 2020-04-14 at 5 44 44 PM" src="https://user-images.githubusercontent.com/34335017/79224249-642bf880-7e78-11ea-88e0-39691c0ad49f.png">

Xcode 11.3.1

**Comment by wtmoose** [comment]
I wasn't able to reproduce this. Sample project attached.

[Test.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/5092998/Test.zip)

**Comment by armandsLa** [comment]
I also received this error after upgrading to Xcode 14. Inspecting Pods project I found two instances of `SwiftMessages` under targets. Removing and re-adding `SwiftMessages` to pods solved this issue.
