### ISSUE TITLE
Can you support swift package manager?

### ISSUE THREAD

**Issue by CainLuo** [SwiftKickMobile/SwiftMessages#387]
Can you support swift package manager?

**Comment by wtmoose** [comment]
Dupe of #330 

Support for resources isn't coming until Swift 5.3.

https://forums.swift.org/t/se-0271-package-manager-resources/30730/74

**Comment by knothed** [comment]
@CainLuo See here for a working solution: https://github.com/SwiftKickMobile/SwiftMessages/pull/395
