### ISSUE TITLE
crash on iOS 10 when built using Swift 2.2 - Xcode 7.3.1

### ISSUE THREAD

**Issue by zhiyanshao** [SwiftKickMobile/SwiftMessages#39]
Here is the stack. The screen was frozen for a while and then crashed. I am using .TabView

#0. Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1853da014 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1854a2450 pthread_kill + 112
2  libsystem_c.dylib              0x18534e3e0 abort + 140
3  libsystem_malloc.dylib         0x18541ea38 _nano_vet_and_size_of_live + 330
4  libsystem_malloc.dylib         0x18541fdb8 nano_free + 220
5  CoreFoundation                 0x1863b9e8c _CFRelease + 1264
6  UIKit                          0x18c2ae340 -[UIBezierPath _initWithCGMutablePath:] + 64
7  UIKit                          0x18c51f334 +[UIBezierPath _continuousRoundedRectBezierPath:withRoundedCorners:cornerRadii:segments:smoothPillShapes:] + 2036
8  UIKit                          0x18c2ae9f4 +[UIBezierPath _continuousRoundedRectBezierPath:withRoundedCorners:cornerRadius:segments:] + 212
9  UIKit                          0x18c2ae584 +[UIBezierPath _roundedRectBezierPath:withRoundedCorners:cornerRadius:segments:legacyCorners:] + 352
10 SwiftMessages                  0x103f7942c _TFC13SwiftMessages8BaseView14layoutSubviewsfT_T_ + 284
11 SwiftMessages                  0x103f794e4 _TToFC13SwiftMessages8BaseView14layoutSubviewsfT_T_ + 28
12 UIKit                          0x18c262220 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1196
13 QuartzCore                     0x189722188 -[CALayer layoutSublayers] + 148
14 QuartzCore                     0x189716e64 CA::Layer::layout_if_needed(CA::Transaction*) + 292
15 UIKit                          0x18c276c90 -[UIView(Hierarchy) layoutBelowIfNeeded] + 1020
16 SwiftMessages                  0x103f821a8 _TFC13SwiftMessages9Presenter7installfT_T_ + 3596
17 SwiftMessages                  0x103f80c68 _TFC13SwiftMessages9Presenter4showfzT10completionFT9completedSb_T__T_ + 672
18 SwiftMessages                  0x103f8bd94 _TFFC13SwiftMessages13SwiftMessages11dequeueNextFT_T_U_FT_T_ + 156
19 libdispatch.dylib              0x185295200 _dispatch_call_block_and_release + 24
20 libdispatch.dylib              0x1852951c0 _dispatch_client_callout + 16
21 libdispatch.dylib              0x185299d6c _dispatch_main_queue_callback_4CF + 1000
22 CoreFoundation                 0x1863b7f2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
23 CoreFoundation                 0x1863b5b18 __CFRunLoopRun + 1660
24 CoreFoundation                 0x1862e4048 CFRunLoopRunSpecific + 444
25 GraphicsServices               0x187d6a198 GSEventRunModal + 180
26 UIKit                          0x18c2d02fc -[UIApplication _run] + 684
27 UIKit                          0x18c2cb034 UIApplicationMain + 208

**Comment by wtmoose** [comment]
This seems like an iOS 10 bug https://forums.developer.apple.com/thread/63546.

Have you tried a build with Xcode 8 & Swift 2.3? Not sure there's much I can do to help you with this obsolete configuration.

**Comment by zhiyanshao** [comment]
@wtmoose , after seeing RoundedCorners in the stack, I changed to .MessageView and the crash went away. I haven't upgrade to xcode 8 yet and will do it soon. Awesome library BTW. Thanks!
