### ISSUE TITLE
multi window issue

### ISSUE THREAD

**Issue by L1cardo** [SwiftKickMobile/SwiftMessages#392]
I have known that someone have mentioned the multi window issue here #366 
I dont know if SwiftMessages supports multi window, but I seem to have some issues.

![image](https://user-images.githubusercontent.com/33802186/80973156-97e3b800-8e51-11ea-84ac-9b98eacfa6fc.png)

I found codes saying something about `windowScene` but what is weird is that these code never show up after I installed the SwiftMessages

![image](https://user-images.githubusercontent.com/33802186/80974134-eb0a3a80-8e52-11ea-9a70-aee856902b91.png)

project target: iOS 13
xcode verison: 11.4.1 (11E503a)
SwiftMessages version : 7.0.1

**Comment by L1cardo** [comment]
Is there a sample code to solve this?  
Thanks

**Comment by wtmoose** [comment]
Try the head of `master`. I resolved multi-window issues a while back but haven't released them.

**Comment by L1cardo** [comment]
> Try the head of `master`. I resolved multi-window issues a while back but haven't released them.

Works fine！！！ Thanks！

**Comment by wtmoose** [comment]
Closing since this duplicates #366
