### ISSUE TITLE
Small memory leak

### ISSUE THREAD

**Issue by RSickenberg** [SwiftKickMobile/SwiftMessages#394]
Hello, I found a small memory leak. I let you the Instrument screenshot.

I'm on the latest 7.0.1 version.
Regards

![image](https://user-images.githubusercontent.com/16922548/84370595-c125ff80-abd8-11ea-8d6f-fad43c4e955b.png)

**Comment by wtmoose** [comment]
I couldn't reproduce using the Demo app. Rather than running instruments, I'm showing and hiding several different message and checking the memory graph debugger to verify there are no SwiftMessages component in memory.

Please provide repro steps if you still think thee's an issue.
