### ISSUE TITLE
TabView.xib - Deployment Warning

### ISSUE THREAD

**Issue by undeaDD** [SwiftKickMobile/SwiftMessages#396]
**Xcode Warning:**
Pods/SwiftMessages/SwiftMessages/Resources/TabView.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]

**Current Setup:**
Xcode: 11.5
Deployment target: iOS 13

**Comment by ChristianVinterly** [comment]
<img width="259" alt="Screenshot 2020-08-05 at 14 53 05" src="https://user-images.githubusercontent.com/12391750/89416065-04aa6f00-d72d-11ea-9834-8040add4e4fe.png">

It is set to 9.1

**Comment by wtmoose** [comment]
The deployment target of the SwiftMessages framework should be 9.0 and `TabView.xib` should be configured to build for 9.1 and later.

Is your SwiftMessages configuration different?

**Comment by undeaDD** [comment]
sry for the silence on my part :D 
solved it already some one day after i opened this issue

i was overriding the deployment target via podfile:
`config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'`

changed it back manually for the swiftmessages pod ^^
