### ISSUE TITLE
[Testing]: Testing Breaks with 'UIView.init(coder:) must be used from main thread only'

### ISSUE THREAD

**Issue by willnix86** [SwiftKickMobile/SwiftMessages#397]
Although I can build my app just fine, when trying to run XCTests, it fails with the following error inside the BaseView.swift file:

'Thread 3: UIView.init(coder:) must be used from main thread only'

**Comment by wtmoose** [comment]
I feel like I’m stating the obvious, anything that invokes UIKit code needs to be done on the main queue. You should be able to look at the call stack to find out why you’re not on the main queue.

**Comment by wtmoose** [comment]
No response. Closing

**Comment by willnix86** [comment]
Sorry @wtmoose - it was idiocy on my part, meant to follow up. Thank you!
