### ISSUE TITLE
No Add EventListener Sample

### ISSUE THREAD

**Issue by vogttho** [SwiftKickMobile/SwiftMessages#40]
Would be great if you could explain how to add EventListeners. Best practice to listen for onHide or didHide MessageView.

**Comment by wtmoose** [comment]
The `SwiftMessages.Config.eventListeners` property is an array that you are free to configure any way that suits you. I added a particular example to the readme:

````swift
// Specify one or more event listeners to respond to show and hide events.
config.eventListeners.append() { event in
    if case .didHide = event { print("yep") }
}
````

As far as best practices, event listeners are an optional feature that you would use if there is something specific you need to happen during the message's presentation lifecycle that isn't already provided by SwiftMessages. So, it really depends on what you're trying to accomplish.

Hope that helps.
