### ISSUE TITLE
Just a comment on this project

### ISSUE THREAD

**Issue by ejuden** [SwiftKickMobile/SwiftMessages#406]
I have been writing professional software for over 25 years (not mobile) and I will have to say, this project is very well architected and written.

So flexible and so easy to use, saves so much time in software development for displaying of messages.

Thank you!

**Comment by wtmoose** [comment]
Thanks, I appreciate the kind words. But did you close the ticket because you changed your mind?

**Comment by ejuden** [comment]
No, closed it to keep the open ticket count down.  😉

On Aug 6, 2020, at 10:55 AM, Timothy Moose <notifications@github.com> wrote:

﻿

Thanks, I appreciate the kind words. But did you close the ticket because
you changed your mind?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/SwiftKickMobile/SwiftMessages/issues/406#issuecomment-670015626>,
or unsubscribe
