### ISSUE TITLE
This file is set to build for a version older than the deployment target. Functionality may be limited. [9]

### ISSUE THREAD

**Issue by jonathanfoster** [SwiftKickMobile/SwiftMessages#412]
After updating to Xcode 12, I get a build warning that says "This file is set to build for a version older than the deployment target. Functionality may be limited. [9]". My deployment target is set to iOS 13 and the SwiftMessages XIBs are set to build for iOS 9.1 and Later. The warning went away after changing each of the XIBs to build for Deployment Target (12.0).

**Comment by wtmoose** [comment]
Should be fixed in 8.0.3
