### ISSUE TITLE
Error with Xcode 12.0

### ISSUE THREAD

**Issue by AMSH92** [SwiftKickMobile/SwiftMessages#414]
I have installed SwiftMessages through podfile, when I try to build my project I get `UNCATEGORIZED`.
Everything is working just fine with Xcode 11.7

**Comment by wtmoose** [comment]
>  I get `UNCATEGORIZED`

I don't know what this means. Can you elaborate?

**Comment by AMSH92** [comment]
When I try to build the project - I get this error. 
Please see attachment
![Screen Shot 2020-09-19 at 6 14 02 PM](https://user-images.githubusercontent.com/19398043/93670416-e792eb00-faa3-11ea-8f6f-2bcea58cf13f.png)
![Screen Shot 2020-09-19 at 6 14 13 PM](https://user-images.githubusercontent.com/19398043/93670419-ed88cc00-faa3-11ea-8d6d-629135918f94.png)

**Comment by AMSH92** [comment]
When I try to build the project I get this error. 
![Screen Shot 2020-09-19 at 6 16 09 PM](https://user-images.githubusercontent.com/19398043/93670459-33459480-faa4-11ea-8d4a-6fa9e9649283.png)

**Comment by wtmoose** [comment]
There's not enough context here. What is the connection with SwiftMessages? Is this a compile error in a SwiftMessages file?

**Comment by AMSH92** [comment]
The problem is not with SwiftMessages only but also with many famous libraries. I downgraded to Xcode 11.7 and all libraries are working just fine.

**Comment by AMSH92** [comment]
I really do not know what happened but SwiftMessages is no longer facing the same error as the rest
Take these images as an example: 
![Screen Shot 2020-09-19 at 6 21 20 PM](https://user-images.githubusercontent.com/19398043/93670565-ee6e2d80-faa4-11ea-873d-4492b4e89213.png)

![Screen Shot 2020-09-19 at 6 20 42 PM](https://user-images.githubusercontent.com/19398043/93670548-d5657c80-faa4-11ea-9a6d-4db6e88599de.png)
