### ISSUE TITLE
SPM issue: Could not load NIB in bundle

### ISSUE THREAD

**Issue by Yoloabdo** [SwiftKickMobile/SwiftMessages#415]
I've tried to install the package with SPM and got this error 

```** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle <> (loaded)' with name 'CardView''```

I'm not sure what's wrong here but I think integrating SPM has something to do with it, any thoughts?

**Comment by wtmoose** [comment]
The answer depends on if you're using Xcode 11 or 12. See #395. Does this help?

**Comment by Yoloabdo** [comment]
Awesome! Thank you very much. It can be added it to the readme file to make it easier for anyone maybe?

**Comment by wtmoose** [comment]
Well, it won't be an issue when I release the Xcode 12 support shortly. So I probably won't reference #395 in the readme.

**Comment by jerometonnelier** [comment]
hi @wtmoose ;-)
Quick question too : I'm trying to make a wrapper around SwiftMessages and therefore, I created a Swift Package that has SM as a dependency. However, I'm not able to load the MessageView or any NIB from SM. Ido you think it's a xcode12/SPM issue that will be addressed shortly or is it something else ?
Thanks.
