### ISSUE TITLE
not able to set cornerRadius

### ISSUE THREAD

**Issue by annathomasQB** [SwiftKickMobile/SwiftMessages#417]
Hi,
First of all, superb library! 👍 

I'm using custom xib to show the swift messages. 
By looking in the Readme, I'm trying to set the cornerRadius of the view, but it throws the error "Ambiguous use of cornerRadius".

So I tried setting _**view.layer.cornerRadius**_. But it doesn't change anything to the final view. I tried really large values to see any difference in cornerRadius but nothing. 

Can you help me out ? 

What I tried : 
          

  ```
if let view = alertView.backgroundView as? CornerRoundingView {
                view.cornerRadius = 150    // setting a huge value just to see if any visible change 
            }


```
The above code throws the error.

<img width="793" alt="Screenshot 2020-09-21 at 4 10 41 PM" src="https://user-images.githubusercontent.com/2297073/93758067-64999e00-fc25-11ea-8257-c14500d8a129.png">

What doesn't throw error (but sadly doesn't work as well) 
```

           if let view = alertView.backgroundView as? CornerRoundingView {
                view.layer.cornerRadius = 150
            }

```

**Comment by annathomasQB** [comment]
Hi

Was able to resolve this by changing the corner Radius in the xib file for background view.. :) 

So cheers!! :) 
Closing this issue.

**Comment by wtmoose** [comment]
Hmm. I don't know where that error comes from. I guess its something specific to your project. If you expand the error, I think it will point out where the ambiguous property definitions are.

`CornerRoundingView` was introduced for continuous rounded corners before Apple supported it directly through the `layer.cornerCurve` property. `CornerRoundingView` isn't strictly needed anymore.

Anyway, glad you got it fixed.

**Comment by annathomasQB** [comment]
oh, thanks for that info! 👍

**Comment by cliftonlabrum** [comment]
@wtmoose I see this same error. Is `cornerRadius` supposed to be a changeable property? 

![image](https://user-images.githubusercontent.com/2513753/95387712-fbad5980-08a5-11eb-996f-ab27c8b1a39f.png)

**Comment by wtmoose** [comment]
@cliftonlabrum yes

**Comment by nichita-stefanita** [comment]
Have the same issue.
@cliftonlabrum were you able to solve it?

**Comment by cliftonlabrum** [comment]
No, I never found a fix.

**Comment by nichita-stefanita** [comment]
@wtmoose any idea why this error is happening and how to solve it ? Maybe there is a workaround or another way to disable/modify cornerRadius ? Would apreciate some help here

**Comment by wtmoose** [comment]
@nichita-stefanita no idea whatsoever. It's not normal. Send me a sample project and I'll take a look.
