### ISSUE TITLE
SPM Xcode 12 support

### ISSUE THREAD

**Issue by andrey-zelenin** [SwiftKickMobile/SwiftMessages#419]

**Comment by wtmoose** [comment]
`work/xcode12`

**Comment by pyby** [comment]
The SPM support with Xcode 12 works as expected on this branch in our projects.
How can we help to the next steps?
Thank you @wtmoose for this work.

**Comment by andrey-zelenin** [comment]
Checked. Cool
@wtmoose thanks

**Comment by wtmoose** [comment]
8.0.3
