### ISSUE TITLE
How to adjust height SwiftMessagesSegue with UITableView content size?

### ISSUE THREAD

**Issue by lutluthfi** [SwiftKickMobile/SwiftMessages#422]
The case is start from fetching data from CoreData and displayed it onto UITableView. But I need the height of view controller is adjusting to UITableView content size. Could you give me the sample code or any answer how to do that?

**Comment by wtmoose** [comment]
I'm not sure I understand your end goal, but it doesn't seem specifically related to SwiftMessages. Maybe StackOverflow would be a better forum for this?

**Comment by lutluthfi** [comment]
My goal is after view controller being presented with SwiftMessagesSegue, the height of view controller could be changed according to the content size table view

**Comment by wtmoose** [comment]
Put a height constraint on the table view

**Comment by lutluthfi** [comment]
Cool, I think we should define the height of `messageView` variable in `SwiftMessagesSegue`. Because I try to add more `UITableViewCell` in demo project is not working. Thanks, so if I want to limit the height, I have to limit the height constraint of `UITableView` too?

**Comment by wtmoose** [comment]
The table view in the demo is embedded in a navigation controller. That’s different because navigation controller has it’s own sizing behavior. You can put a height constraint on `messageView` if you want

**Comment by wtmoose** [comment]
Also, check the APIs. The message view has a property for setting the height of the background view `backgroundHeight`

**Comment by lutluthfi** [comment]
That's mean the approach won't work if I am using `UINavigaitonController`? Yes, I was use `backgroundHeight` to set the height before
