### ISSUE TITLE
ios 13 messageview showing under navigationbar but want it on top of the screen

### ISSUE THREAD

**Issue by Nathan2017** [SwiftKickMobile/SwiftMessages#425]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-13 at 03 28 03](https://user-images.githubusercontent.com/25632519/95783482-80fc9800-0d04-11eb-8394-ff131f4a80f6.png)
![Screen Shot 2020-10-13 at 1 52 12 AM](https://user-images.githubusercontent.com/25632519/95783514-9245a480-0d04-11eb-84d2-43e32a8409ee.png)
I am using version 8 and simulator ios 14 but the message appear under the navigationBar. Is there anyway to show the message on the top of the screen.

**Comment by wtmoose** [comment]
`successConfig.presentationContext = .window(...)`
