### ISSUE TITLE
Missing copy/paste menu in UITextField/UIWebView

### ISSUE THREAD

**Issue by canhth** [SwiftKickMobile/SwiftMessages#429]
### Description
- When using custom `SwiftMessages.Config` with `dimMode != .none`. The method `makeKeyAndVisible` is being called inside `WindowViewController`.
- The clipboard (copy/paste) options when select text in TextField/Webview can not be displayed. 
I'm not quite sure the reason why clipboard could not display, maybe another UIWindow make Key and Visible, then dismissed. So the OS confused and doesn't know which Window the clipboard should show.

### Screenshot
![clipboard](https://user-images.githubusercontent.com/7752679/97255202-b3e57680-1842-11eb-967d-1c1d355aae37.gif)
### References
https://stackoverflow.com/questions/6414540/missing-copy-paste-menu-in-uitextfield-uiwebview/7576544
### Solution & PR
 https://github.com/SwiftKickMobile/SwiftMessages/pull/430
### Demo
- Branch having issue: https://github.com/canhth/SwiftMessages/tree/demo/multiple-windows
- Fixed version: https://github.com/canhth/SwiftMessages/tree/demo/multiple-windows-fixed

**Comment by wtmoose** [comment]
Where is the text field?

**Comment by canhth** [comment]
Hi @wtmoose ,

I've updated the Description. Including demo, video, and solution.
How to reproduce it (Please check out my demo fork):
```
- Add rootViewController programmatically (don't forget to call `window.makeKeyAndVisible`).
- Use another third party that also active another UIWindow. (_I'm using DoraemonKit for example _)
- Show SwiftMessage view with `dimMode != .none`.
- Now, there is no more clipboard options (copy/paste) for your selected text.
```
Please consider the PR that I made. That's just for enabling users can force disable `becomeKeyWindow` in SwiftMessages.Config.

Thanks

**Comment by wtmoose** [comment]
Thanks for clarifying. The change in the PR is fine, but it seems like more of a workaround than a solution. The case where the message’s window should become the key window, for example if the message has a text field, would still have the issue wouldn’t it?

**Comment by wtmoose** [comment]
Would it make sense to have SwiftMessages restore the previous key window on dismissal?

**Comment by canhth** [comment]
Yes, you're right. This is just a workaround.
I've tried reactive my `Appdelegate's window` in `eventListeners .didHide`. But that can not fix the issue.

After spent more time debugging. I've found an issue in iOS 13, we set `window?.windowScene = scene` but when `uninstall` the window, I think we forgot to remove the `windowScene` reference.

The correct `uninstall function` should be:
```
func uninstall() {
        if #available(iOS 13, *) {
            window?.windowScene = nil
        }
        window?.isHidden = true
        window = nil
}
```

I prefer to have this fix and `disable becomeKeyWindow` as well. I'll update my PR, and if you agree with this, could you please help to release the new version ASAP?

I'm pretty sure this is the root cause of the missing clipboard issue. Cheers.

**Comment by haitacnj** [comment]
Your fix make **keyWindow** nil when call show popup second time
```
if let rootViewController = UIApplication.shared.keyWindow?.rootViewController {    //  keyWindow nil 
   let viewController = rootViewController.sm_selectPresentationContextTopDown(config)
   return .viewController(Weak(value: viewController))
} else {
   throw SwiftMessagesError.noRootViewController
}
```

**Comment by canhth** [comment]
Hi @haitacnj,

Created the fix in this PR: https://github.com/SwiftKickMobile/SwiftMessages/pull/438
But if you want a workaround, just disable `becomKeyActive` in Configuration:
```
        var config = SwiftMessages.Config()
        config.presentationStyle = .center
        // Disable this loading toast window become KeyWindow,
        // to fix the issue clipboard (copy/paste) can not displayed.
        config.becomeKeyWindow = false
```

If you have a better idea of how to fix my problem without breaking anything, let's have further discussion.

**Comment by wtmoose** [comment]
I've lost track of the status on this one. Can this be closed now?

**Comment by canhth** [comment]
We can close this. I can not reproduce @haitacnj's issue with Xcode 12.
