### ISSUE TITLE
Present Message View right above keyboard

### ISSUE THREAD

**Issue by happiehappie** [SwiftKickMobile/SwiftMessages#43]
Not sure if this is allowed at this point, but has anyone tried presenting MessageView right above the keyboard? Right now my MessageView overlaps with the keyboard.

**Comment by wtmoose** [comment]
How about using `presentationContext=.view(...)` where the view is an `inputAccessoryView`? Does that make sense?

**Comment by wtmoose** [comment]
Seems like this can be closed. Any more questions?
