### ISSUE TITLE
TableView does not scrolling inside Custom View Xib

### ISSUE THREAD

**Issue by vikashgomechanic** [SwiftKickMobile/SwiftMessages#432]
I have created ab xib of UIView and Used a UITableView Inside It.
But my tableView Is not scrolling any more and if once I tap on it, View gets dismissed. Please help!!

I'm presenting the Custom View Like This

```
        let sheet = PriceDetailPopupView.instantiateFromNib() as PriceDetailPopupView
        self.showPopUpView(view: sheet, shouldEnableKeyboard: false, type: .center)
```

```
    func showPopUpView(view: UIView, shouldEnableKeyboard: Bool, type:SwiftMessages.PresentationStyle = .bottom) {
        var config = SwiftMessages.Config()
        config.presentationStyle = type
        config.duration = .forever
        config.presentationContext = .window(windowLevel: .normal)//.view(self.view)
        config.dimMode = .gray(interactive: true)
        if shouldEnableKeyboard {
            config.keyboardTrackingView = KeyboardTrackingView()
        }
        SwiftMessages.show(config: config, view: view)
    }
```

<img width="1792" alt="Screenshot 2020-10-30 at 4 15 41 PM" src="https://user-images.githubusercontent.com/69067564/97696185-34b6a380-1acb-11eb-8845-647b80002de7.png">
![Simulator Screen Shot - iPhone 11 Pro - 2020-10-30 at 16 13 27](https://user-images.githubusercontent.com/69067564/97696203-3c764800-1acb-11eb-867b-312bfb5e18d6.png)

**Comment by wtmoose** [comment]
Can you attach your nib file?

**Comment by wtmoose** [comment]
Closing since there hasn't been any followup in weeks.
