### ISSUE TITLE
Attributed text to the body message

### ISSUE THREAD

**Issue by bekzodrakhmatof** [SwiftKickMobile/SwiftMessages#434]
Hi Team,

Thanks for the amazing work!
Is it possible to add attributed text to the card view as in screenshot?

![test](https://user-images.githubusercontent.com/23249828/98189973-64e1c480-1f59-11eb-8e1f-8d7a388b49aa.png)

**Comment by wtmoose** [comment]
Of course. The labels are exposed as public properties. You can do whatever you want with them

**Comment by bekzodrakhmatof** [comment]
Thank you
