### ISSUE TITLE
The new SwiftMessage Custom View didn't show after hiding the old one in Version 8.0.4

### ISSUE THREAD

**Issue by MoElnaggar14** [SwiftKickMobile/SwiftMessages#444]
I don't know what's the changes in the latest version. 

it's working fine in Version 8.0.3 or lower.

**Comment by wtmoose** [comment]
Could you share some details so I can try to reproduce your problem? If you could attach a sample project, that would be great.

**Comment by MoElnaggar14** [comment]
I'm trying to hide a custom MessageView and show a new one 


```
              UIView.animate(withDuration: 0.01) {
                   // hide the old view
                    SwiftMessages.hide()
                } completion: { _ in
                    // i already declared the config and view
                    SwiftMessages.show(config: config, view: view)
                }

```

**Comment by wtmoose** [comment]
Curios why you're showing inside of an animation block? Not sure what that's intended to accomplish.

But could you try 8.0.5? I haven't reproduced your issue, but 8.0.4 introduced a bug that was affecting folks in different ways.

**Comment by MoElnaggar14** [comment]
it's not working without the animation block, I don't know why. 

I'll try with 8.0.5 and back to you

**Comment by wtmoose** [comment]
If it isn't working (though I'm not exactly sure what "it" means), something is horribly wrong. Take a look at the demo app.

**Comment by MoElnaggar14** [comment]
Okay, I'll take a look.  Thanks for your quick response. 
I just updated and tested the latest version and everything looks good 🎉 . 

I'll close the issue.
