### ISSUE TITLE
Use separated controller ('aka' segue) in a stand alone window instead of presenting it on a source controller.

### ISSUE THREAD

**Issue by MojtabaHs** [SwiftKickMobile/SwiftMessages#447]
Hey, Since we should use segues to have a standalone view controller inside the swift message, we  always need a source view controller to pass it as the source of this function:

```
        BottomCardSheetSegue(identifier: id, source: source, destination: controller).perform()
```

Imagine we have a controller that should  be on top of the entire window (like the sheets that iOS is using)

![68747470733a2f2f692e737461636b2e696d6775722e636f6d2f6d4b5a32502e6a7067](https://user-images.githubusercontent.com/15649873/103152477-9a5a9f80-479d-11eb-8c9e-28ebf4ed9032.jpeg)

This kind of message should not be coupled with the source view controller underneath them.

So how can we present a controller in a separate window like the presentation of the basic views of the Swift messages?  Is it possible now?

**Comment by wtmoose** [comment]
Hi. I hadn't thought of doing that before, but it was relatively straightforward. Could you install the head of `master` and try the following and let me know if it works for you?

````swift
let sourceVC = WindowViewController()
let segue = SwiftMessagesSegue(identifier: nil, source: windowVC, destination: destinationVC)
segue.perform()
````

You can optionally specify window level and window scene by providing an instance of `SwiftMessages.Config` to the window view controller's initializer where the desired values are specified in the `SwiftMessages.Config.presentationContext` property.

**Comment by MojtabaHs** [comment]
Works like a charm. This method should be mentioned in the documentation. I've done that in [this PR](https://github.com/SwiftKickMobile/SwiftMessages/pull/448)

**Comment by wtmoose** [comment]
9.0.0
