### ISSUE TITLE
How to make the controller content ignore the safe area?

### ISSUE THREAD

**Issue by MojtabaHs** [SwiftKickMobile/SwiftMessages#449]
I know we can ignore the safe area inset **since v8.0.4**. but the content still cares about the safe area:

<img width="403" alt="Screen Shot 2020-12-27 at 11 58 23" src="https://user-images.githubusercontent.com/15649873/103166792-d5f77700-483a-11eb-9e6a-1eb71ca30c3d.png">

Note that little inset below item 3? That is exactly the bottom safe area and it is visible **only if** the container passed the minimum inset (and not respecting the safe area)

So how can I ignore the safe area for the content too?

**Comment by wtmoose** [comment]
`tableView.contentInsetAdjustmentBehavior = .never`

**Comment by MojtabaHs** [comment]
No luck @wtmoose. I've tested that before, also for the navigation controller, also for a simple view controller, all with no luck
It is not the `tableView`'s behavior.

You can see the inset even if you add a simple ViewController.

<img width="405" alt="Screen Shot 2020-12-27 at 20 39 57" src="https://user-images.githubusercontent.com/15649873/103176010-b59fda80-4883-11eb-803c-1dfcad9606ba.png">

**Comment by wtmoose** [comment]
Seems to work for me:

![Fooo](https://user-images.githubusercontent.com/2529176/103176357-a47cac80-4836-11eb-9e85-77d400b75b96.png)


I had to turn off "Under top bars" on the view controller since turning off automatic insets removes the top inset as well.

In the demo app, go to View Controller | Bottom Card

[SwiftMessages-safearea.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/5744868/SwiftMessages-safearea.zip)

**Comment by wtmoose** [comment]
Here's an example with a simple view controller. Just don't constrain content to the safe area guides. This seems trivial, so maybe I'm not understanding your use case?

![foooooo](https://user-images.githubusercontent.com/2529176/103176588-a34c7f00-4838-11eb-9f55-9dc211bfcd0a.png)

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/5744897/SwiftMessagesTest.zip)

**Comment by MojtabaHs** [comment]
Strange! it is working on the example you sent but not on the clone of the master.

Can you please share a commit so I can see what are you changing exactly that I'm missing?

**Comment by wtmoose** [comment]
There's no commit. You can copy the files into your project folder on top of the head of `master` and you'll see the diffs.
