### ISSUE TITLE
invalid custom path

### ISSUE THREAD

**Issue by iKorich** [SwiftKickMobile/SwiftMessages#454]
Hey,

I can't add again v9.0 via SPM,
made Xcode > File > Swift Packages > Resolve Package Versions

and get error:
`invalid custom path 'SwiftMessages' for target 'SwiftMessages'
`

Can't add or downgrade a version

**Comment by wtmoose** [comment]
I wasn't able to reproduce. Here's a sample project with SwiftMessages 9 using SPM:

[SMSPMTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/5967345/SMSPMTest.zip)

You'll probably find better SPM experts by posting on StackOverflow

**Comment by iKorich** [comment]
hey @wtmoose ,

that is project works for me, 
but in main project with 25 dependencies - doesn't

ok, will try reconfigure my project
