### ISSUE TITLE
App going to background while presenting a message leaves "current" set incorrectly  

### ISSUE THREAD

**Issue by rspreen** [SwiftKickMobile/SwiftMessages#46]
**How it looks**:  an app using SwiftMessages gets sent to the background while a SwiftMessage (that will be auto-hidden) is actively being presented; when the app returns, no more SwiftMessages ever appear.

**What's happening**: while SwiftMessages has a "current" Presenter being shown (i.e. SwiftMessages.current != nil), there is an autoHide block queued.  When the app is sent to the background, the autoHide block can fire after the app is inactive/going to background.  

The final step in "hideCompleted" is the block that is called back from the UIView animation that hides the view.  This block requires that the "completed" boolean (which comes from the UIView animation) must be true; if it is not, it returns early (due to the guard statement).  Unfortunately, when the app is going inactive/background, the UIView animation will indeed return with completed = false.  Thus, that guard statement prevents the "current" variable from being cleared to nil.  

At this point, no more messages can be shown, because dequeueNext requires "current" to be nil, and there is no way to clear that "stuck" presenter.

 **My suggestions**:  (Note: I'm relatively new to SwiftMessages, so I could be wrong!)  The simplest possibility is to remove the guard statement in "hideCompleted" that requires the "completed" boolean to be true.  I don't know any other situation in which "completed" could return false where you wouldn't want to clear out the current presenter.   An alternative (though more complicated) would be to provide a synchronous "cancel" method that can be run on demand when the app is going to the background, that would cancel the previously queued autoHide block.

**Comment**: I work around this (and you could say this is the required proper usage) by calling "hideAll" while going inactive, but I am not convinced this will guarantee that the UIView animation will complete with a "completed = true" result, so I believe it would still be safer to remove that guard statement.

Thank you for a great library, by the way!

**Comment by wtmoose** [comment]
Thanks for bringing this up! What I had in mind with the completion flag is the scenario where the user could interactively interrupt dismissal. But since that isn't currently supported, the fix I've done is to always succeed on hiding. If you don't mind, please check out the head of master and let me know if it works for you.

**Comment by rspreen** [comment]
I checked it and it works great - that does the trick for me.  Thanks!

**Comment by wtmoose** [comment]
This fix is now in 3.1.2. Cheers
