### ISSUE TITLE
9.0.0 without the Layout.leadingMessage and so on

### ISSUE THREAD

**Issue by ShenYj** [SwiftKickMobile/SwiftMessages#463]
I don't found the `leadingMessage` in SwiftMessagesSegue class, I wanna use this function directly in the project.

**Comment by wtmoose** [comment]
Sorry, I accidentally committed unreleased changes to the `master` branch. So the readme file you see contains unreleased information. I'll fix that.

**Comment by wtmoose** [comment]
`master` branch restored to correct state. You can use the `work/10.0.0` branch if you want early access to new features.

**Comment by ShenYj** [comment]
> `master` branch restored to correct state. You can use the `work/10.0.0` branch if you want early access to new features.

thx, this is a powerful lib
