### ISSUE TITLE
Messages freeze UI when dismissing by user interaction

### ISSUE THREAD

**Issue by MahmoudAbunaji** [SwiftKickMobile/SwiftMessages#464]
The message is freezing the UI in iOS 14.4.1 sometimes when show the message , Im catch the  issue using freezeObserver

**Comment by wtmoose** [comment]
Pause the app when it is frozen and send me a stack trace.

**Comment by MahmoudAbunaji** [comment]
@wtmoose Nothing logged in the output window

**Comment by MahmoudAbunaji** [comment]
@wtmoose The issue starting  from release 9.0.0, In the older versions 8.0.5 its working fine

**Comment by wtmoose** [comment]
@MahmoudAbunaji I'm not asking you what is in the output window. I'm asking you to pause the app and send the stack trace.

**Comment by wtmoose** [comment]
Closing due to no response
