### ISSUE TITLE
When I use custom .xib I can't interact with the main viewController

### ISSUE THREAD

**Issue by yunustek** [SwiftKickMobile/SwiftMessages#469]
I want to show the SwiftMessages I created with Xib on the screen and interact with the main screen behind. How can I do that?

```
           let view = PushToastMessageView.instanceFromNib()
            
            let topVc = getTopViewController()
            let animator = LTTopBottomAnimation(style: .top)
            animator.hideDelay = 2
            config.presentationStyle = .custom(animator: animator)
            
            config.dimMode = .none
            config.interactiveHide = false
            config.duration = .forever
            config.interactiveHide = false
            config.presentationContext = .automatic
            config.preferredStatusBarStyle = topVc?.preferredStatusBarStyle
            config.keyboardTrackingView = KeyboardTrackingView()
            config.prefersStatusBarHidden = topVc?.prefersStatusBarHidden
            
            SwiftMessages.show(config: config, view: view)
```

**Comment by yunustek** [comment]
When I removed keyboardTrackingView it's worked!

**Comment by wtmoose** [comment]
Did you try disabling user interaction on the `KeyboardTrackingView`

**Comment by yunustek** [comment]
Yes but didn't solve it

**Comment by wtmoose** [comment]
Sorry, I haven't had time to look at this until now. I'm not able to reproduce your issue. What I tried is, using the attached test project that uses the code you provided:

1. Tap "Test"
2. See message view appear with active text field
3. Toggle switch on main view controller

According to your description, I should not be able to toggle the switch. If you can help me understand how to change my project to reproduce your issue, I can take another look.

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/6593464/SwiftMessagesTest.zip)

**Comment by wtmoose** [comment]
No response...closing
