### ISSUE TITLE
[Feature Request] Observing Pan Gestures from PresenterDelegate

### ISSUE THREAD

**Issue by leojkwan** [SwiftKickMobile/SwiftMessages#47]
Great library, well documented! Will there eventually be a way to listen in on pan gestures for dismissing the card views? I know SwiftMessages is the PresenterDelegate's delegate, but a callback on completion would be super helpful for analytics/toggling UserDefaults for shown messages :)

**Comment by wtmoose** [comment]
I think I've got you covered. See #40

**Comment by leojkwan** [comment]
👍  Awesome thank you!
