### ISSUE TITLE
Incompatible with application's interface style

### ISSUE THREAD

**Issue by Eric0625** [SwiftKickMobile/SwiftMessages#474]
XCode version: 12.5.1 (12E507)
Platform:  iOS 14.5
SwiftMessage version: 9.0.2
-----------------------------------------------------------------
Hi there.
It seems that the appearance of the SwiftMessage is following the system's colour style. It does not comply with the application's `overrideUserInterfaceStyle` attribute. Below is the code I used, it works for the rest of the app's interface except SwiftMessage views. Thanks.

            let keyWindow = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
            switch userPreferedStyle {
            case .auto:
                keyWindow?.overrideUserInterfaceStyle = .unspecified
            case .dark:
                keyWindow?.overrideUserInterfaceStyle = .dark
            case .light:
                keyWindow?.overrideUserInterfaceStyle = .light
            }

**Comment by wtmoose** [comment]
You can supply your own colors that adapt to interface style by calling:

````swift
MessageView.configureTheme(backgroundColor:foregroundColor:iconImage:iconText:)
````

**Comment by Eric0625** [comment]
> You can supply your own colors that adapt to interface style by calling:
> 
> ```swift
> MessageView.configureTheme(backgroundColor:foregroundColor:iconImage:iconText:)
> ```

Is there a way to manually change MessageView's display style just as it does when following the system settings? In that way, the display style will be unified.

**Comment by Eric0625** [comment]
I think I've found the attribute, just set `MessageView.overrideUserInterfaceStyle` to the desired style and it's done.

**Comment by Eric0625** [comment]
> You can supply your own colors that adapt to interface style by calling:
> 
> ```swift
> MessageView.configureTheme(backgroundColor:foregroundColor:iconImage:iconText:)
> ```

I think I've found it, just set `MessageView.overrideUserInterfaceStyle` to the desired style and it's done.

**Comment by wtmoose** [comment]
OK, sorry I misread what your problem was. Your message is probably being displayed in its own window and it isn't the key window.

There's a setting for this already – see `SwiftMessages.Config.overrideUserInterfaceStyle`. But what you did seems fine too.

**Comment by Eric0625** [comment]
Thanks
