### ISSUE TITLE
Xcode 13 beta 3 - SwiftPM - Build error: UIApplication.shared not available in iOS App Extension

### ISSUE THREAD

**Issue by klanchman** [SwiftKickMobile/SwiftMessages#475]
When building an app with SwiftMessages from Swift Package Manager in Xcode 13 beta 3 that _does not_ use app extensions, compiler errors related to API availability in app extensions are emitted.

### Reproduction Steps

- Create a new iOS project in Xcode 13 beta 3
- Add SwiftMessages on branch `work/9.0.4` using Swift Package Manager
- Build the app

Result: multiple errors on `UIApplication.shared` usage:

```
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
```

### Other Notes

This appears to be expected behavior in Xcode 13 beta 3 with Swift Package Manager, based on this [Apple Developer Forums thread](https://developer.apple.com/forums/thread/685103) and this [Swift forums post](https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11). The Apple engineer in the second link recommends dealing with this by marking declarations as unavailable to app extensions when they use APIs that are unavailable to app extensions.

***

**Update**: It looks like the Swift team is [reconsidering how this behaves](https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/32). I'll update this issue as we hear more from them.

**Comment by sofili** [comment]
having the same issues

**Comment by klanchman** [comment]
Apple reverted this change in Xcode 13 beta 5, these errors no longer occur.

**Comment by wtmoose** [comment]
Whew. Thanks for keeping tabs on this
