### ISSUE TITLE
How to disable the swipe down hiding for view shown with SwiftMessagesBottomTabSegue?

### ISSUE THREAD

**Issue by Bawenang** [SwiftKickMobile/SwiftMessages#476]
I'm using SwiftMessagesBottomTabSegue for showing my messages. I set the segue via the storyboard. Because the View Controller to be shown is only one class that has some `@IBInspectables` that can be filled from the Inspector. So I didn't use it as the demo did (ie. creating the segue programmatically). Because creating the segue programmatically will be a hassle when setting the values of the inspectable variables compared to setting it for the inspector itself. I've tried setting the `segue.interactiveHide = false` in the func `prepare(for:sender:)`. But it didn't work.

Now the problem is, in one of them, there is a scroll view and sometimes it got closed when I swiped on it. So my question is how do I disable that gesture?

Thanks.

**Comment by wtmoose** [comment]
Hard for me to give you an answer without seeing your code. Instead, take a look at this sample project.

My guess is its dismissing because you're tapping outside of the view controller. That behavior is controlled by the dim mode option:

````swift
segue.dimMode = .gray(interactive: false)
````

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/6894669/SwiftMessagesTest.zip)

**Comment by Bawenang** [comment]
> Hard for me to give you an answer without seeing your code. Instead, take a look at this sample project.
> 
> My guess is its dismissing because you're tapping outside of the view controller. That behavior is controlled by the dim mode option:
> 
> ```swift
> segue.dimMode = .gray(interactive: false)
> ```
> 
> [SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/6894669/SwiftMessagesTest.zip)

It was dismissed when I am scrolling the thumbnails in PDFThumbnailView. So it's actually not exactly a Scroll View. Anyway, I managed to fix this. I set the kind of the segue from PopOver to Custom. I used PopOver before because somehow the message is displayed behind the TabController. But when I use PopOver with up direction and TabController as the anchor. It worked and displayed in front of it. I think that TabController issue was an old bug because it doesn't happen again now. Even though I use Custom kind, it still got displayed in front of the Tab Controller.

Thanks.
