### ISSUE TITLE
Enum cases with associated values cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by vijayennomail** [SwiftKickMobile/SwiftMessages#485]
Hi,

after updating Xcode 13, this error occurs on project build

**Comment by developer-celusion** [comment]
Check this out

https://stackoverflow.com/questions/68753877/enum-cases-with-associated-values-cannot-be-marked-potentially-unavailable-with

**Comment by wtmoose** [comment]
Update to 9.0.4

https://github.com/SwiftKickMobile/SwiftMessages/releases/tag/9.0.4

**Comment by tantan39** [comment]
@wtmoose  Is there anyway to use `9.0.4` with CocoaPods?

**Comment by wtmoose** [comment]
9.0.4 is the latest version on Cocoapods

https://cocoapods.org/pods/SwiftMessages

Try typing `pod repo update` on the command line if you're not seeing it
