### ISSUE TITLE
Could not find module 'SwiftMessages' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by shadman93** [SwiftKickMobile/SwiftMessages#489]
Xcode version: 12.4
mac Os: BigSur 11.6 (Apple M1 chip)

I am not sure is it because I am trying to run in simulator(don't have an iPhone for now), or because of Apple M1 chip

![Screenshot 2021-12-01 at 10 32 46 AM](https://user-images.githubusercontent.com/81788801/144175167-6cf3fcd3-ccd1-4c29-b7a1-79d64f8838e2.png)

**Comment by shadman93** [comment]
Found a work around for this
- close Xcode
- open Finder 
- go to Application
- right click on Xcode -> select `get Info`
- select `open using Rosseta`
- open Xcode and build again

check the answer from ludvik.polak in [here](https://developer.apple.com/forums/thread/123614)

**Comment by skywalkerlw** [comment]
> Found a work around for this
> 
> * close Xcode
> * open Finder
> * go to Application
> * right click on Xcode -> select `get Info`
> * select `open using Rosseta`
> * open Xcode and build again
> 
> check the answer from ludvik.polak in [here](https://developer.apple.com/forums/thread/123614)

This will  slow down Xcode a bit since it's a Rosseta mode. Can we make that native support on Apple M1 chip?

**Comment by nastasiupta** [comment]
+1
