### ISSUE TITLE
[Question] How to know when user has dismissed MessageView by swipe or touch in backgroundView ?

### ISSUE THREAD

**Issue by ahmad-sonder** [SwiftKickMobile/SwiftMessages#490]
Apologies to opening it as an issue, since it is more of a question.

Is there a delegate method or callback to know when user has dismissed the MessageView and how?
Whether it was a tap in grey area or by swipe?
Many thanks 
Ahmad

**Comment by wtmoose** [comment]
Look for `eventListeners` in the readme
