### ISSUE TITLE
Can't show new messages repeatedly

### ISSUE THREAD

**Issue by mpmartimbianco** [SwiftKickMobile/SwiftMessages#494]
Hi, I'm having a problem with a new message I trying to show and it never appears.

I also tried to use SwiftMessages.hideAll() before call the .show()

I think it can be because I'm using a custom view with SwiftMessages.viewFromNib()? But I'm not sure

I don't know what I can do to solve this yet.

I will attach a project with a similar setup I have on my real project, to test it just click on buttons while a message is being displayed. On default config it will dismiss the actual message and show the new one, but not for my custom config.

[messagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/8603860/messagesTest.zip)

**Comment by fr33css** [comment]
I think you should add 

config.ignoreDuplicates = false

and 

SwiftMessages.pauseBetweenMessages = 0

**Comment by mpmartimbianco** [comment]
I will try it, thank you

**Comment by mpmartimbianco** [comment]
@fr33css my tests using that configs solved that behavior, thank you
