### ISSUE TITLE
KeyboardTrackingView does not seem to account for safe area

### ISSUE THREAD

**Issue by adamvnovak** [SwiftKickMobile/SwiftMessages#496]
On phones without the safe area, like iPhone 8, the setting config.keyboardTrackingView = KeyboardTrackingView() works as desired.

However, on phones with the safe area, like the 12, the message view is displayed too high above the keyboard.

<img width="378" alt="스크린샷 2022-05-27 오전 8 29 39" src="https://user-images.githubusercontent.com/42633268/170730997-4a47525b-9eac-472f-81e3-000761a73fed.png">
<img width="442" alt="스크린샷 2022-05-27 오전 8 32 14" src="https://user-images.githubusercontent.com/42633268/170731426-b1870ba9-ec6f-4459-8b91-89a2bf95d4c3.png">

**Comment by wtmoose** [comment]
Please reopen if you still need help with this.
