### ISSUE TITLE
Interacting with a SwiftMessage resigns the view controller as first responder

### ISSUE THREAD

**Issue by adamvnovak** [SwiftKickMobile/SwiftMessages#499]
I am keeping an inputAccessoryView always attached to the bottom of the viewController through a method described [here](https://stackoverflow.com/a/24855095/10467554). The viewController sets its inputAccessoryView and then becomes the first responder.

However, when a SwiftMessage displays, and the user interacts with it in any way, the inputAccessoryView resigns because the viewController is resigned as the first responder. [Here](https://drive.google.com/file/d/1VKx7h6zeIdQnNUE5yk8M7Lo8m2poDcpM/view?usp=sharing) is a video displaying the issue.

Why might user interaction with a SwiftMessage be forcing the viewController to resign as first responder? And how might this be prevented?

Specs:
ios15
Xcode 13.4
Swift 5

**Comment by wtmoose** [comment]
Have you tried setting `SwiftMessage.Config.becomeKeyWindow` to `false`?
