### ISSUE TITLE
Set Id

### ISSUE THREAD

**Issue by AmeliaBoli** [SwiftKickMobile/SwiftMessages#50]
Is there a way to set an id for a message? If not, is this a feature that you anticipate implementing?

The use case that I am looking for is hiding a specific message. For example, if I create a message with a `title` of "Please enter a valid email address" and an empty `body`, the `id` is 

> "MessageView:title=Optional(\"Please enter a valid email address\"), body=Optional(\"\")".

In order to get the id so that I could hide the message, I had to print the id to the console so that I could then add it to the code to hide a message.

Thanks in advance.

**Comment by wtmoose** [comment]
When you create the message view, can you not easily store the ID (or even a reference to the view)
in a variable somewhere and use that later for hiding?

**Comment by AmeliaBoli** [comment]
Yes. In fact a co-worker gave me a workaround similar to that for now. It just seems like it would be easier to simply set the ID in the first place.

**Comment by wtmoose** [comment]
I agree. Take a look at the head of master and let me know if it works for you.

**Comment by AmeliaBoli** [comment]
This is exactly what I was looking for. Thank you so much!
