### ISSUE TITLE
Button in CustomView Tap not work

### ISSUE THREAD

**Issue by ducbm051291** [SwiftKickMobile/SwiftMessages#500]
I create a custom view to show with SwiftMessages, it shows beautifully but I have a close button inside that I want to handle the touchUpInside event to dismiss the message myself but it doesn't work. I think it must be the PassthroughView and its hitTest function which block the button's interactive. Could you help me about this case? I tried inheritage the MessageView and set my close button to MessageView's button but doesn't work either.

**Comment by wtmoose** [comment]
It’s almost certainly a problem with your view. Generally there’s no issue with interacting with custom views. Please reopen if you still need help.
