### ISSUE TITLE
Could not load NIB in bundle

### ISSUE THREAD

**Issue by labteleco** [SwiftKickMobile/SwiftMessages#502]
XCode 14
SwiftMessages version 9.0.6

let view = MessageView.viewFromNib(...) cause a crash.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/167D6BBB-E7DE-4680-BF5D-80EC2AB3A239/Daisy.app/Frameworks/SwiftMessages.framework> (loaded)' with name 'StatusLine''
terminating with uncaught exception of type NSException

**Comment by wtmoose** [comment]
I need a sample app. Or at a minimum tell me how you installed SwiftMessages. I’m assuming you’ve moved on since this ticket is old. If you still need help, reopen and I’ll take a look.
