### ISSUE TITLE
Cannot find type 'WindowScene' in scope

### ISSUE THREAD

**Issue by LLIo6oH** [SwiftKickMobile/SwiftMessages#511]
Have a build error

`Cannot find type 'WindowScene' in scope`

XCode 14
min os v - iOS13

<img width="705" alt="Screenshot 2022-11-18 at 17 59 18" src="https://user-images.githubusercontent.com/15324698/202734544-dcd0f6ad-f82c-49e8-af73-dd7aa068788e.png">

**Comment by wtmoose** [comment]
That isn't normal. `WindowScene` was introduced in iOS 13 and that file imports `UIKit`. How are you installing SwiftMessages?

**Comment by wtmoose** [comment]
Closing. Reopen if you need further help.

**Comment by Sikandarkhan** [comment]
I am using Xcode 14.2 min ios version 13

I am getting this error . Please suggest

**Comment by wtmoose** [comment]
See my comments above

**Comment by Sikandarkhan** [comment]
Resolved.
