### ISSUE TITLE
Can you add a function to display priority based on weight?

### ISSUE THREAD

**Issue by AllLuckly** [SwiftKickMobile/SwiftMessages#523]
Can you add a function to display priority based on weight? For example, what I am showing now is a pop-up window with low priority. When another pop-up window with high priority arrives, if the user does not perform any operation, we will automatically hide the pop-up window with low weight, and then display the pop-up window with high priority. window, when the user finishes operating the high-priority pop-up window, the low-priority pop-up window will pop up.

**Comment by AllLuckly** [comment]
> 
Thank you for your reply, I have already written the relevant functions, are you willing to accept my pull requests?

**Comment by wtmoose** [comment]
Unlikely, but I’ll look at it

**Comment by Coder-Miao** [comment]
I think most scenarios need to set the priority of the box, which is throughout the entire app life cycle. I think future versions can add this configuration, which will gain more recognition and love from developers.

**Comment by Jacky-LinPeng** [comment]
I agree with Coder-Miao!

**Comment by Jacky-LinPeng** [comment]
> > 
> 
> Thank you for your reply, I have already written the relevant functions, are you willing to accept my pull requests?

已经实现优先级能力啦？开放出来共享不

**Comment by Jacky-LinPeng** [comment]
I agree with Coder-Miao!

**Comment by wtmoose** [comment]
10.0.1
