### ISSUE TITLE
No such module 'SwiftMessages'

### ISSUE THREAD

**Issue by tbswork1** [SwiftKickMobile/SwiftMessages#525]
I am using XCode 14.3.1 and SwiftMessages 9.0.6 as local swift package. But I get `No such module 'SwiftMessages'` at the import line. 

The local SwiftMessages was added in Target -> Build Phrases -> Link Binary with Libraries.

**Comment by wtmoose** [comment]
Send me a sample project, a recording of your package setup, or something I can work with, please

**Comment by tbswork1** [comment]
Found that I need to import as library not framework. Then it works.
