### ISSUE TITLE
Crash while clicking two times to hide the presenting controller

### ISSUE THREAD

**Issue by itcmarcinrabieko** [SwiftKickMobile/SwiftMessages#527]
Hi, we are facing a crash in the library. The unowned 'self' from the screen should be weak, otherwise, it will crash often for quick fingers.

![Zrzut ekranu 2023-09-12 o 13 23 17](https://github.com/SwiftKickMobile/SwiftMessages/assets/78590610/79f95c00-af88-4784-933a-35f6fb4f8ef8)

Can I please for a fix soon? It would be great and appreciated so much.

**Comment by wtmoose** [comment]
I removed the `unowned` reference along with a few other unreleased changes on the head of `master`. Could you verify?

**Comment by itcmarcinrabieko** [comment]
Yes, it looks like 9.0.7 version is ok. Thanks!
