### ISSUE TITLE
SwiftUI View ignoresSafeArea

### ISSUE THREAD

**Issue by xiaoxidong** [SwiftKickMobile/SwiftMessages#529]
For the bottom card most time need ignoresSafeArea, maybe a config for ignoresSafeArea?

**Comment by wtmoose** [comment]
Could you provide a screenshot that demonstrates the issue you're having?

**Comment by xiaoxidong** [comment]
![1](https://github.com/SwiftKickMobile/SwiftMessages/assets/3838258/69b2719a-9ae9-45e8-9361-f1a9ab455aac)
Just the SwiftUI demo project.

**Comment by wtmoose** [comment]
I'm assuming you want the background to extend to the edge of the screen, but you don't want your content within the safe area. You can do that with a mask. For example, I've modified the demo app to use a mask that rounds the bottom corners and ignores the top safe area:

````swift
var body: some View {
    VStack(alignment: .leading) {
        Text(message.title).font(.system(size: 20, weight: .bold))
        Text(message.body)
    }
    .multilineTextAlignment(.leading)
    .padding(30)
    .frame(maxWidth: .infinity)
    .background(.demoMessageBackground)
    .mask(
        UnevenRoundedRectangle(
            cornerRadii: .init(bottomLeading: 15, bottomTrailing: 15)
        )
        .edgesIgnoringSafeArea(.top)
    )
}
````

This produces the result below. Putting your content in the safe area would require overriding the safe area insets of `MessageHostingView`, which isn't currently supported. However, I'm adding something to make edge styling easier and may add support for that as well.

Does this resolve your issue?

![image](https://github.com/SwiftKickMobile/SwiftMessages/assets/2529176/bb3bfaa8-eff0-4ebf-86e2-b787ac33d9f1)

**Comment by xiaoxidong** [comment]
Great, Thank you so much.
