### ISSUE TITLE
wierd opengl warning

### ISSUE THREAD

**Issue by jaimeagudo** [SwiftKickMobile/SwiftMessages#53]
Thanks guys first of all. Anyone experienced something like this?

I experienced the same bug on Version 8.2 (8C38) on a Swift project, it makes the app crash on a real device but just warns on the simulator
 
`ERROR /BuildRoot/Library/Caches/com.apple.xbs/Sources/VectorKit_Sim/VectorKit-1230.32.8.29.9/GeoGL/GeoGL/GLCoreContext.cpp 1764: WARNING: Output of vertex shader 'v_gradient' not read by fragment shader  `
 
 
Just on one scene using a map but the issue dissapeared when I stopped displaying an info message with https://github.com/SwiftKickMobile/SwiftMessages
 
Just saying it could be an interaction between the mapkit and a 3rd party library
 
Hope it helps

https://forums.developer.apple.com/message/204771#204771

**Comment by wtmoose** [comment]
Thanks for pointing this out. I'm not authorized to view the message you linked to, though. But I'll be happy to take a look if you can provide a sample project or the steps to create one.

**Comment by jaimeagudo** [comment]
Sorry but I haven't much time atm to provide the sample project, some further details at https://stackoverflow.com/questions/39608231/warning-output-of-vertex-shader-v-gradient-not-read-by-fragment-shader

**Comment by wtmoose** [comment]
Seems pretty clear that the crash is due to #55. SwiftMessages is known to crash on jailbroken devices, but a workaround is provided in #9 for anyone who wishes to support jailbroken phones. The error message referenced above appears in my mapping app without SwiftMessages, so I don't think it's related.
