### ISSUE TITLE
How can I show multiple alert?

### ISSUE THREAD

**Issue by iJamesAdi9** [SwiftKickMobile/SwiftMessages#531]
How can I show multiple alert message like this app?
user tapped 1 times -> show 1
user tapped 2 times-> show 2

![CleanShot 2566-10-19 at 22 15 11@2x](https://github.com/SwiftKickMobile/SwiftMessages/assets/116384545/78dff57d-32cb-4b14-875e-56a3f1ac9de1)

**Comment by wtmoose** [comment]
That isn't supported. Sorry

**Comment by iJamesAdi9** [comment]
It's ok.
thank you :D
