### ISSUE TITLE
EventListeners not called ? 

### ISSUE THREAD

**Issue by jerometonnelier** [SwiftKickMobile/SwiftMessages#536]
Hi!

I use SwiftMessages from ages now, and I recently found that eventListeners are not called anymore (at least on my project).
I added them the way they should : 
```swift
conf.eventListener.append { [weak self] (event) in
            guard let self = self else { return }
            switch event {
            case .willHide: // do whatever I need
            case .willShow: // do whatever I need
            default: ()
            }
        }
// ...
SwiftMessages.show(config: conf, view: view)
```
I never enter the completion block now :-/
Anyone has this issue ? 

Thanks

**Comment by wtmoose** [comment]
It is working for me. I attached a test project that logs events to the console. Is there any chance that `self == nil` and you're exiting on the guard? If not, I'll need some help with reproducing.

[SwiftMessagesTest.zip](https://github.com/SwiftKickMobile/SwiftMessages/files/13539822/SwiftMessagesTest.zip)

**Comment by wtmoose** [comment]
No, that wouldn't have anything to do with it. My suggestion is put a break point in `Presenter.swift` in the function `func show(completion: @escaping AnimationCompletion) throws`. Step through it and see what's going on.

**Comment by jerometonnelier** [comment]
My bad, I do enter the eventListener, but for some reason, I can't put a breakpoint inside 🤔. If I put a simple print it works! I will close it, sorry for the inconvenience

**Comment by wtmoose** [comment]
No problem. Glad it’s working
