### ISSUE TITLE
Resize MessageView iconImageView

### ISSUE THREAD

**Issue by jjjeeerrr111** [SwiftKickMobile/SwiftMessages#54]
How can I set the iconImageView size?

         `let view = MessageView.viewFromNib(layout: .CardView)
            view.configureTheme(backgroundColor: Colors.searchResultBGColor, foregroundColor: UIColor.black)
            view.configureContent(title: senderDisplay, body: body)
            view.titleLabel?.textColor = Colors.appGreen
            view.titleLabel?.numberOfLines = 1
            view.bodyLabel?.numberOfLines = 2
            view.iconImageView?.isHidden = false
            view.iconImageView?.frame = CGRect(x: 0, y: 0, width: 30, height: 30)
            view.iconImageView?.layer.cornerRadius = 15
            view.iconImageView?.contentMode = .scaleAspectFill
            view.iconImageView?.clipsToBounds = true
            view.iconImageView?.kf.setImage(with: url)
            
            view.configureDropShadow()
            view.button?.isHidden = true
            
            // Hide when message view tapped
            view.tapHandler = { _ in
                
                print("tapped the messsage view")
                SwiftMessages.hide()
            }
            var config = SwiftMessages.Config()
            
            config.presentationStyle = .top
            // Display in a window at the specified window level: UIWindowLevelStatusBar
            // displays over the status bar while UIWindowLevelNormal displays under.
            config.presentationContext = .window(windowLevel: UIWindowLevelNormal)
            config.interactiveHide = true
            SwiftMessages.show(config: config, view: view)`

adjusting the frame.size.height/width properties dont work either. The image just resizes in the stack view.

**Comment by wtmoose** [comment]
By default, the size is determined by the image view's intrinsic content size. To override that, you need to add Auto Layout constraints to the image view. I've added a convenience function for this for iOS 9+:

````swift
view.constrainIconImageView(toSize: CGSize(width: 30, height: 30), contentMode: .scaleAspectFill)
````

Please try it out on the head of master and let me know if it works for you.

Also, it is worth mentioning that SwiftMessages was designed for you to easily modify the nib files or provide your own. You can simply drag-and-drop a copy of the nib file into your project from the Pods project (if you're using CocoaPods) and make whatever changes you need and it should just work.

**Comment by jjjeeerrr111** [comment]
@wtmoose This works! Thanks so much for making this awesome tool!

**Comment by edalford11** [comment]
This works but throws breaking constraint errors in the console.

**Comment by wtmoose** [comment]
@edalford11 could you try the head of `master`?
