### ISSUE TITLE
Why do you call this SwiftMessages?

### ISSUE THREAD

**Issue by rex-remind101** [SwiftKickMobile/SwiftMessages#550]
As far as I understand, this is not "messaging" in a robust sense, this is "notification banners". Am I wrong? If not, can you please update your documentation?

**Comment by wtmoose** [comment]
Semantics

**Comment by rex-remind101** [comment]
Confusion and wasted time understanding this library 👍

**Comment by rex-remind101** [comment]
I was confused with the purpose of this library, thinking it was a library for messaging or building a messaging app because the documentation starts off explaining "Message View"s. Documentation is semantics; I think it would be helpful if at least at the top it explained more clearly what the purpose of this library was so others don't get confused as well. My 2cents at least 🫡
