### ISSUE TITLE
SwiftMessages.hide() Call to main actor-isolated static method

### ISSUE THREAD

**Issue by Ramprasathselvam** [SwiftKickMobile/SwiftMessages#553]
In Xcode 16 iOS 18 Beta facing below issue.

Call to main actor-isolated static method 'hide(animated:)' in a synchronous nonisolated context

<img width="855" alt="Screenshot 2024-06-14 at 10 13 06 AM" src="https://github.com/SwiftKickMobile/SwiftMessages/assets/30049169/c2e19aef-5389-4210-a6b4-11baa87fe94f">

**Comment by wtmoose** [comment]
What’s the question?
