### ISSUE TITLE
Swift 6 support

### ISSUE THREAD

**Issue by artemelianov** [SwiftKickMobile/SwiftMessages#556]
Currently, I am migrating a project to Swift 6 and have found a warning at the `asMessageView` method: `Call to main actor-isolated initializer 'init(message:)' in a synchronous nonisolated context; this is an error in the Swift 6 language mode`.

Probably, we need to make the `asMessageView` method of `MessageViewConvertible` as `@MainActor`

**Comment by wtmoose** [comment]
I've been contemplating deprecating `MessageViewConvertible` in favor of the newer API that works more like the `sheet()` modifier where you supply a view builder. Do you have any particular reason to prefer the `MessageViewConvertible`?

````swift
.swiftMessage(message: $message) { message in
    MyMessageView(message)
}
````

**Comment by artemelianov** [comment]
Indeed, we can utilize the SwiftUI style. There is no compelling reason to use MessageViewConvertible
