### ISSUE TITLE
[BUG]: SwiftUI message views don't respond to touch input on Xcode 16b5

### ISSUE THREAD

**Issue by noahlit** [SwiftKickMobile/SwiftMessages#561]
## Description
Hello, I've noticed an issue on Xcode 16b5 which causes SwiftUI message views to not respond to touch input. This is not an issue on Xcode 15, and also only seems to affect Simulator and not physical device. Not sure if this is an Apple bug or an issue with SwiftMessages, but will continue to raise this issue just in case something needs to be updated in SwiftMessages.

### My affected environment
- Xcode 16b5
- Simulator (iPhone 15 Pro iOS 18.0)

### Reproducible example project
I have also attached a simple reproducible sample project with just a button to present a message. If you try to click the dismiss button on the presented message, it doesn't get dismissed, nor do any of the `print` calls log anything to console in the `Button` closure.
[SwiftMessagesBug.zip](https://github.com/user-attachments/files/16599048/SwiftMessagesBug.zip)

### Recording of the bug on simulator
https://github.com/user-attachments/assets/39b6f72a-b1c1-499c-840c-9ec507ca0646

### Recording of physical device working as expected
https://github.com/user-attachments/assets/4a765690-f279-4b54-a134-a676a21c7b27

**Comment by wtmoose** [comment]
Yeah, they changed something with the touch handling on iOS 18 for `UIHostingController`. However, it is already fixed on the head of `master`
