### ISSUE TITLE
No such file or directory: '.../SwiftMessages-Dynamic.framework/SwiftMessages-Dynamic'

### ISSUE THREAD

**Issue by davidkessler-ch** [SwiftKickMobile/SwiftMessages#562]
When I add this package (with SPM) my project no longer compiles or runs. I get this error:

No such file or directory: '/Users/[censored]/Library/Developer/Xcode/DerivedData/[censored]/Build/Products/Debug Development-iphoneos/PackageFrameworks/SwiftMessages-Dynamic.framework/SwiftMessages-Dynamic'

**Comment by wtmoose** [comment]
That isn’t normal, so you’re gonna need to provide more details. Send me a sample project that reproduces the error
