### ISSUE TITLE
how to present a custom view controller

### ISSUE THREAD

**Issue by hoangnam714** [SwiftKickMobile/SwiftMessages#566]
I have a view controller created with xib, I looked at your demo but it only applies to storyboard, is there any way to use it?

**Comment by wtmoose** [comment]
Yes. Please refer to the readme

**Comment by hoangnam714** [comment]
I mean a view controller created with xib, not a regular view xib. 
<img width="869" alt="Screenshot 2024-12-02 at 14 48 45" src="https://github.com/user-attachments/assets/2e0e7bf2-f555-4646-90b0-1a0efc6ea2de">

I want to present a uiviewcontroller like this, but my app doesn't use main storyboard, all my viewcontrollers use xib
<img width="330" alt="Screenshot 2024-12-02 at 14 49 46" src="https://github.com/user-attachments/assets/2885f08b-d666-4931-923e-92025d508b05">

**Comment by wtmoose** [comment]
Yes. As I said, this is covered in the readme

**Comment by wtmoose** [comment]
https://github.com/SwiftKickMobile/SwiftMessages/blob/master/ViewControllers.md#programatic
