### ISSUE TITLE
Message not showing some times

### ISSUE THREAD

**Issue by AshishSyncapp007** [SwiftKickMobile/SwiftMessages#58]
Hello

Bellow two issue which i have.
1. Some times message is not showing
2. Message hides my accessory view( Bottom tool bar)

**Comment by wtmoose** [comment]
Sounds like your not using the right presentation context.

**Comment by AshishSyncapp007** [comment]
Thanks for the prompt replay!!

Can you please guide me what wrong i am doing ?

**Comment by wtmoose** [comment]
I have no idea based on what you've said so far. You'll need to give me a detailed description of the problem including your code and preferably screenshots so I can get an idea of what's going on.

**Comment by wousser** [comment]
Maybe I can provide some context as I'm experiencing the same issue. I'm presenting a .MessageView at the bottom of the current viewcontroller
`config.presentationContext = .viewController(self)`
and
`config.duration = .forever`
This works on first load, but after navigating to another viewController, and going back to this one, the message is not shown anymore, and is not shown when calling 
`SwiftMessages.show(config: config, view: view)` again.

**Comment by wousser** [comment]
Just trying a bit more. Maybe it's not similar to the case above. The following happens: show a message with duration .forever on the current viewController. Navigate away and navigate back. 
Expected results would be that the message is still there. But no message is shown. If trying to show the same message again the call is ignored.

**Comment by wtmoose** [comment]
@wousser moved your issue to #64

**Comment by wtmoose** [comment]
Closed. No response from poster.

**Comment by AshishSyncapp007** [comment]
@wtmoose Sorry for the delay and FYI issue has been resolve with the latest update 

Thanks for the support !! :)
