### ISSUE TITLE
There is no way to create SwiftMessages instance  as there is no public initializer

### ISSUE THREAD

**Issue by andrei-kuzma** [SwiftKickMobile/SwiftMessages#6]
Sometimes you need to separate queues for different messages and make default configuration for them. Currently you can't do that as there is only one instance of SwiftMessages with own queue.
For example I want to show StatusLine when user is offline but when it's shown I can't show other messages.

Just add this to SwiftMessages
public init() { }

**Comment by wtmoose** [comment]
Oops! Thanks for the bug report. Try v 1.1.3.
