### ISSUE TITLE
Dismiss only if tap is outside view

### ISSUE THREAD

**Issue by droidery** [SwiftKickMobile/SwiftMessages#60]
![test](https://cloud.githubusercontent.com/assets/25188027/22132801/60b03db6-df10-11e6-9044-48596e9c21e9.png)

How can I dismiss a message only when there's a tap outside of the view? (highlighted in red here)

`config.dimMode = .gray(interactive: true)` applies to the entire screen, in that, any tap (even if outside the dimmed area) causes the view to be dismissed.

**Comment by wtmoose** [comment]
If you're using `BaseView`, which is the superclass of `MessageView`, then you can intercept the tap by doing:

    view.tapHandler = { _ in }

Does that work?

**Comment by droidery** [comment]
Thanks that works great.
