### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ShaneQi** [SwiftKickMobile/SwiftMessages#61]
When initialing and showing multiple MessageView. Even all message views are dismissed, they are not released from the memory.

iOS version: 10.2
SwiftMessage version: 3.1.3 & 3.0.3
Xcode version: 8.2

<img width="219" alt="screen shot 2017-01-20 at 13 27 56" src="https://cloud.githubusercontent.com/assets/7324708/22166203/bfd04e72-df14-11e6-8bf9-caaf47fce5cf.png">

**Comment by wtmoose** [comment]
@ShaneQi Thanks for pointing this out! I did a little digging and I'm seeing MessageViews retained even if I don't show them. I'll let you know when I get to the bottom of it.

**Comment by ShaneQi** [comment]
Sounds good!

**Comment by wtmoose** [comment]
Check out 3.1.5.

**Comment by ShaneQi** [comment]
Thanks for the fix.
