### ISSUE TITLE
MessageView deinit not called until new MessageView shown

### ISSUE THREAD

**Issue by droidery** [SwiftKickMobile/SwiftMessages#68]
**Correct timely deinit call**
With pan-to-hide (`interactiveHide`) on a MessageView, `deinit` is called as soon as the MessageView hides when panning. This is what should always be happening.

**Incorrect delayed deinit calls**
When hiding a MessageView  by tapping the dimmed background with `dimMode`, `deinit` is not called until another MessageView appears.

Additionally, when using `SwiftMessages.hide()`, the MessageView does not call `deinit` until another MessageView appears using `SwiftMessages.show(_, _)`.

This causes memory usage to spike persistently until another MessageView appears and the old MessageView can be deallocated.

**Reproduction steps**
1. In the demo open `TacoDialogView.swift`, add `deinit { print("deinit TacoDialogView") }`, to check if the object is marked for de-allocation
2. Run the demo app and open the `TacoDialogView`
3. Tap the background view. `deinit` not called.
4. Tap the Forget It button. `deinit` not called.
5. Drag down the `TacoDialogView`. `deinit` is called as expected.
 
**Videos**
Here's a video of the problem where the `TacoDialogView` needs another MessageView shown before `TacoDialogView` calls `deinit` (step 3): https://vid.me/vKwv
Here is a video of a successful `deinit` call as soon as the MessageView hides (step 5): https://vid.me/aHFK

I think this is the cause of a strange memory leak in my app.

**Comment by droidery** [comment]
Interestingly, I can get the `TacoDialogView` to `deinit` by creating any type of SwiftMessage, for example by creating a status bar SwiftMessage, the `TacoDialogView` will `deinit`.

**Comment by wtmoose** [comment]
When you say "creating" do you mean instantiating? Showing?

**Comment by droidery** [comment]
@wtmoose Sorry, I meant showing with `SwiftMessages.show()` causes the old `TacoDialogView` to `deinit`.

**Comment by wtmoose** [comment]
Fixed in 3.2.0
