### ISSUE TITLE
Error - Could not load the "errorIcon"....

### ISSUE THREAD

**Issue by ivanharmat** [SwiftKickMobile/SwiftMessages#7]
I get this error - **Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "(null)"**
**fatal error: unexpectedly found nil while unwrapping an Optional value**

I installed the package with cocoapods.

```swift
let error = MessageView.viewFromNib(layout: .TabView)
error.configureTheme(.Error)
error.configureContent(title: "Error", body: "Something is horribly wrong!")
error.button?.setTitle("Stop", forState: .Normal)
SwiftMessages.show(view: error)
```

**Comment by wtmoose** [comment]
Did you copy TabView.nib into your project? If so, I think the placeholder image in the nib file isn't being found because it's not in the main bundle. Could you try clearing the image field from the `UIImageView` in the nib?

**Comment by ivanharmat** [comment]
I didn't copy TabView.nib to my project. I'll try to do that.

**Comment by wtmoose** [comment]
I wasn't necessarily recommending that you do that. Just trying to troubleshoot the issue. My new best guess is that your version of Cocoapods is out-of-date and the old version doesn't expose resources correctly. Try updating Cocoapods.

**Comment by ivanharmat** [comment]
My Cocoapods version was out-of-date, so I updated to the latest and reinstall all pods.
Now I get a new error. 
**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: ..... with name 'TabView'**

I deleted the TabView file now.

**Comment by wtmoose** [comment]
There isn't anything wrong with the code you posted above and I haven't heard of anyone else having this problem, so it seems there may be something unusual in your project. Please check/do the following and try again. Hopefully this will clear things up.

1. `pod --version` returns 1.0.1.
2. `TabView.nib` has been deleted from your project.
3. `pod update` to make sure pods are properly configured.
4. Clean your build folder using Product | ⌥ + Clean Build Folder from the menu.

**Comment by ivanharmat** [comment]
Thank you for your help, I'll have to figure it out on my own now.

**Comment by ivanharmat** [comment]
I tried to install it to one of my other projects and it works just fine.
Thanks again for your help.

**Comment by wtmoose** [comment]
👍
