### ISSUE TITLE
Change color of default themes

### ISSUE THREAD

**Issue by fruitcoder** [SwiftKickMobile/SwiftMessages#74]
Is there any way I can change the background color of the success theme?

**Comment by wtmoose** [comment]
Sure.

````swift
view.backgroundView.bakgroundColor = ...
````

**Comment by fruitcoder** [comment]
I thought there was more to be done when I use a themed style. Perfect, thanks ;)

**Comment by mgurnani** [comment]
There's a typo in "bakgroundColor".. :)

Thanks for an excellent library !!

**Comment by cwestMobile** [comment]
I am trying to set the view.background color when showing a message and it isn't changing the background color. Can you confirm this still works today w/ Swift 5?

**Comment by wtmoose** [comment]
@cwestMobile see my comment above.

**Comment by cwestMobile** [comment]
@wtmoose Can you look at the code below and see if I'm setting that property in the correct place?

let view = MessageView.viewFromNib(layout: .cardView)
view.configureTheme(.warning)
view.backgroundColor = UIColor.blue
view.configureDropShadow()
let iconText = ["🤔", "😳", "🙄", "😶"].randomElement()!
view.configureContent(title: "Warning", body: "Consider yourself warned.", iconText: iconText)
view.layoutMarginAdditions = UIEdgeInsets(top: 20, left: 20, bottom: 20, right: 20)
(view.backgroundView as? CornerRoundingView)?.cornerRadius = 10
SwiftMessages.show(view: view)

**Comment by wtmoose** [comment]
You are not. It doesn’t seem like you read my comment above.
