### ISSUE TITLE
How to do something on .didHide for a specific message?

### ISSUE THREAD

**Issue by AmeliaBoli** [SwiftKickMobile/SwiftMessages#76]
Hi.

I am trying to present a new view controller after a Swift Message has finished hiding. I know that I can add an `EventListener` to the `Config()`, but how do I handle just one specific messages's hiding? I attempted to add a closure to the `eventListener` array so that I could specifically delete it as soon as the message was finished hiding, but then I'm referring to the closure itself within the closure.

Any help would be appreciated. Thank you.

My terrible hack so far:

    var config = SwiftMessages.Config()
    var presentVCOnHide: (SwiftMessages.Event) -> Void = { event in
         if case .didHide = event {
             // present next vc
             config.eventListeners.remove(at: config.eventListeners.index(where: { $0 === presentVCOnHide }))
        }
    let message = MessageView.errorMessageView(title: "Something Went Wrong", body: "")
        SwiftMessages.show(view: message)
    }

**Comment by wtmoose** [comment]
There is no need to remove the listener as long as you don't reuse the config:

````swift
var config = SwiftMessages.defaultConfig // make a copy of the default config
config.eventListeners.append { event in
    if case .didHide = event {
        //...do something
    }
}
let message = ...
SwiftMessages.show(config: config, view: message) // use the config once
````

**Comment by wtmoose** [comment]
Can I close this one?
