### ISSUE TITLE
String interpolation warning in xcode 8.3

### ISSUE THREAD

**Issue by kiwo12345** [SwiftKickMobile/SwiftMessages#80]

**Comment by wtmoose** [comment]
This is already fixed on head of master

**Comment by kiwo12345** [comment]
@wtmoose its also giving me warnings coz of `M_PI` -fix: `CGFloat.pi`
Does your new release contain a fix for that as well?

**Comment by wtmoose** [comment]
SwiftMessages doesn't reference `M_PI`
