### ISSUE TITLE
Can't present multiple messages across navigation view controllers

### ISSUE THREAD

**Issue by markst** [SwiftKickMobile/SwiftMessages#82]
I'd like to present multiple messages for each view controller in a navigation stack.
But `SwiftMessages` will only allow me to do so if I dismiss the existing message.

**Comment by markst** [comment]
It seem the way to do this to create my own instance of `SwiftMessages` rather than use the global instance?

**Comment by wtmoose** [comment]
Hi. Do you want to display multiple messages simultaneously or queu multiple messages to be displayed serially?

**Comment by markst** [comment]
@wtmoose I'd like to display one message per view controller each part of navigation controller.

**Comment by wtmoose** [comment]
I'm sorry, but your last reply only repeats what your original post said. And I really don't get it. I'm happy to help if you can help me understand what you're trying to do by elaborating.

**Comment by suadbay** [comment]
Hi,
I am trying to display multiple messages simultaneously (one from top, one from bottom)
Is there anyway to manage this?
