### ISSUE TITLE
UITextField or UITextView auto resign first responder

### ISSUE THREAD

**Issue by asaduzzaman-shuvro** [SwiftKickMobile/SwiftMessages#83]
When message view appear then UITextField or UITextView auto resign first responder for window lever presentation context and when disappear message view then UITextField or UITextView auto become first responder. How could i prevent this?

**Comment by wtmoose** [comment]
Does the solution in #45 not work for you?

**Comment by asaduzzaman-shuvro** [comment]
thanks. it works for me.
