### ISSUE TITLE
Reduce the width of Message and positioning manually

### ISSUE THREAD

**Issue by DinakaranS** [SwiftKickMobile/SwiftMessages#84]
Hi, 

How can i position the message view and reduce the width. I don't want to show full width message, i want the message to be shown on the top right corner with 250 width.

**Comment by wtmoose** [comment]
The easiest thing is to copy one of the bundled .nib files into your project and modify it to fit your design. The message view itself is constrained to the full width of the superview. But you can give it a clear background do any layout you want inside it.

For example, if you want a look like `cardView`, copy `CardView.xib` into your project and modify the constraints on `backgroundView`: remove the right constraint and add a 250pt width constraint.

Does that help?

**Comment by DinakaranS** [comment]
Thank you Wtmoose.
