### ISSUE TITLE
change height of default message

### ISSUE THREAD

**Issue by dimohamdy** [SwiftKickMobile/SwiftMessages#85]
How i can change the height of the view 
```
        let view = MessageView.viewFromNib(layout: .CardView)
        view.preferredHeight =  10

```
I use preferredHeight but it not work with me

**Comment by wtmoose** [comment]
The `preferredHeight` property affects the `intrinsicContentSize` calculation:

````swift
    open override var intrinsicContentSize: CGSize {
        if let preferredHeight = preferredHeight {
            return CGSize(width: UIViewNoIntrinsicMetric, height: preferredHeight)
        }
        return super.intrinsicContentSize
    }
````

If you set a value that conflicts with the Auto Layout constraints, the constraints win. In that case, what you need to do is copy the nib file (CardView.nib) into your project and modify the constraints to suit your needs.

Does that help?

**Comment by dimohamdy** [comment]
@wtmoose  Thank you
