### ISSUE TITLE
Display severals theme of Message in same time

### ISSUE THREAD

**Issue by grifas** [SwiftKickMobile/SwiftMessages#91]
Hi,

It is possible to show two types of MessageView in same time ? By example, I have one with the StatusLine layout with duration forever and display others with default configuration.

Thank you,

**Comment by wtmoose** [comment]
From the readme:

Multiple instances of `SwiftMessages` can be used to show more than one message at a time. Note that the static `SwiftMessages.show()` and other static APIs on `SwiftMessage` are just convenience wrappers around the shared instance `SwiftMessages.sharedInstance`):

````swift
let otherMessages = SwiftMessages()
SwiftMessages.show(...)
otherMessages.show(...)
````

**Comment by grifas** [comment]
I tried to use others instances but it doesn't work. I tried this code in viewDidAppear, the message doesn't appear :/ 

```
let view = MessageView.viewFromNib(layout: .MessageView)
view.configureContent(
			title: "hello",
			body: "ola",
			iconImage: nil,
			iconText: nil,
			buttonImage: nil,
			buttonTitle: nil,
			buttonTapHandler: { button in
				SwiftMessages.hide()
		})
		
view.configureTheme(.success)
		
var config = SwiftMessages.Config()
		
config.presentationContext = .window(windowLevel: UIWindowLevelStatusBar)
config.duration = .seconds(seconds: 5)
		
SwiftMessages().show(config: config, view: view)
```

**Comment by wtmoose** [comment]
Your code sample doesn't use multiple `SwiftMessages` instances

**Comment by grifas** [comment]
Ok my code sample doesn't use multiple SwiftMessages instances but is it normal that displays nothing ?

Sorry but I don't understand how I can display more than one message at the same time.

Have I to firstly call the shared instance for the first message and create an other instance for the second one ? In this case, why ?

**Comment by wtmoose** [comment]
Yes.

**Comment by grifas** [comment]
Can you explain me why ?

**Comment by grifas** [comment]
Up

Please can you provide an example ?

Thank you

**Comment by wtmoose** [comment]
Please consider posting this to StackOverflow
