### ISSUE TITLE
Why tapHandler does not fire then I click backgroundView?

### ISSUE THREAD

**Issue by bizibizi** [SwiftKickMobile/SwiftMessages#92]
I use

    config.dimMode = .Color(color: UIColor.blackColor().colorWithAlphaComponent(0.7), interactive: true)
        config.interactiveHide = true

I mean not alert background, but transparent background below the alert

**Comment by bizibizi** [comment]
Or how can I catch the event of clicking background? not an alert, bottom part of window

**Comment by wtmoose** [comment]
You'd need to upgrade to 3.1 or greater and use event listeners.

**Comment by bizibizi** [comment]
well, any way for 2.1? can I add tapGesture somewhere?

**Comment by bizibizi** [comment]
please help

**Comment by wtmoose** [comment]
I don't think so.

The 2.1 codebase is no longer maintained, so my suggestion is to modify it directly and add your own hooks. I would probably make the `Presenter` class public and make the tap handler a public property.

**Comment by bizibizi** [comment]
crap. yes, will be great if you can make it pubic and  I will update it by myself

**Comment by bizibizi** [comment]
let me know, I am using '~> 1.1.4'

**Comment by wtmoose** [comment]
I'm suggesting that *you* modify the codebase to suit your needs. I don't maintain old versions.
