### ISSUE TITLE
Getting current message 

### ISSUE THREAD

**Issue by Akhu** [SwiftKickMobile/SwiftMessages#94]
Hi ! 

There is a way to get current message displayed in queue ? I did saw a "current" var in SwiftMessages but no way to access it. 

I currently need to take an action when a specific message is displayed, hidden or ignored. 
(by the way there is a way to get if user tapped on dim to ignore the message?)

Thanks again for your wonderful library !

**Comment by wtmoose** [comment]
Have you looked into `SwiftMessages.Config.eventListeners`?

**Comment by Akhu** [comment]
Hi thanks for the quick reply,

Yep this is exactly what I struggle with ^^

if I do : 
```swift
config.eventListeners.append() { event in
            //Can I have access to SwiftMessages current displayed / hidded / showed view here? 
            //what I am searching for is doing something like :
           if let myView  = event.currentMessage as? MyView { }//then doing my work on it when the event is triggered
          
        }
```

I also doesn't found an event for user dismissed action, but I can get around this one.

**Comment by wtmoose** [comment]
You can give each message it's own config + event listener and capture a reference to the message view in the event listener. Does that do what you need?

**Comment by Akhu** [comment]
Exactly what I need !
