### ISSUE TITLE
Could not load the "errorIcon" image referenced from a nib in the bundle with identifier

### ISSUE THREAD

**Issue by mink-lparrouy** [SwiftKickMobile/SwiftMessages#96]
Hello,

I installed your library to display messages to my users. It works fine until today, i have a problem because your library cannot find the errorIcon :

```
Could not load the "errorIcon" image referenced from a nib in the bundle with identifier "org.cocoapods.SwiftMessages"
fatal error: unexpectedly found nil while unwrapping an Optional value
```

Xcode 8.3.2, Swift 3, CocoaPods 2.1.0

Thank you for your response

**Comment by wtmoose** [comment]
Maybe the device is jailbroken? See #9

**Comment by mink-lparrouy** [comment]
I am running the application on the xcode simulator

**Comment by wtmoose** [comment]
This error isn't typical, so it would be helpful if you could provide more information. A good start would be to send the relevant code. But it could very well be some issue with the project configuration and packaging of the resources in the library, in which case the code probably won't be too useful and I may need you to help me reproduce it on my end.

A few suggestions:

* Delete your derived data and try again.
* Take a look at what changed between when it was working and when you started getting the error.

As a workaround, you can avoid using any resources from the SwiftMessages library. One simple fix should be to copy the image asset into your project and set it on the message view's `iconImageView` property directly. Calling the `MessageView's` `configure` methods is absolutely optional.

**Comment by mink-lparrouy** [comment]
This is my function :

```
func errorSwiftMessage(message: String) {
        let view = MessageView.viewFromNib(layout: .MessageView)
        view.button?.isHidden = true
        view.configureTheme(.error)
        view.configureDropShadow()
        //view.iconImageView?.image = UIImage(named: "errorIcon")
        view.configureContent(title: "Erreur", body: message)
        SwiftMessages.show(view: view)
    }
```

I try to delete derived data and even load the icon in the function but still the same.

**Comment by mink-lparrouy** [comment]
It's strange if I use my function in viewDidLoad it works. But I want to use it in a UITapGestureRecognizer. Unfortunatly I get the error

**Comment by mink-lparrouy** [comment]
Ok I copy the xib file of MessageView in my project and it works !

**Comment by dimohamdy** [comment]
any one solve this bug

**Comment by satishbabariya2** [comment]
Same bug here. did anyone solved it.

**Comment by kushal211** [comment]
@wtmoose I'm having the same issue with the image. I've used SwiftMessages to so many projects and never faced this issue but right now facing image not found issue with one of the projects. I'm using cocoapod version 1.3.1 

One more thing you said that you've moved out all the assets from assets folder and added them separately. I've tried installing it to new sample project but images are still under the assets and not able to get the image from the bundle. For now, I'm moving out the images to my bundle and changing above code in pod file.

**Comment by wtmoose** [comment]
>I've tried installing it to new sample project but images are still under the assets and not able to get the image from the bundle.

The fix isn't released yet. Did you install the head of the master branch?

**Comment by kushal211** [comment]
> Did you install the head of the master branch?
No, not from the head.

**Comment by wtmoose** [comment]
@kushal211 well there's your problem.

**Comment by kushal211** [comment]
@wtmoose  Thanks! I've installed it from Head and images are there and working fine.
