### ISSUE TITLE
xcode 9 Main thread checker

### ISSUE THREAD

**Issue by crossle** [SwiftKickMobile/SwiftMessages#97]
Main Thread Checker: UI API called on a background thread: -[UILabel text]
PID: 1575, TID: 120576, Thread name: (none), Queue name: it.swiftkick.SwiftMessages, QoS: 0

**Comment by wtmoose** [comment]
Do you have reproduction steps?

**Comment by crossle** [comment]
Use Demo project on xcode9 run on iOS 11, click show the swiftmessage

**Comment by wtmoose** [comment]
Thanks! Fixed in 3.3.4.
