### ISSUE TITLE
Swift 3.2, iOS 11 and Xcode 9 Beta compatibility

### ISSUE THREAD

**Issue by jgarciatt** [SwiftKickMobile/SwiftMessages#99]
Hello.

Im getting problems compiling my project in Xcode 9 Beta. I wonder if there's something that has to be done in order to make it work. I tried compiling using Carthage pointing out to the new Xcode but it does not seems to work. I still gets:

Module compiled with Swift 3.1 cannot be imported in Swift 4.0: /Path/To/Project/Carthage/Build/iOS/SwiftMessages.framework/Modules/SwiftMessages.swiftmodule/arm64.swiftmodule

Thank you.

**Comment by wtmoose** [comment]
Please check the swift4.0 branch and let me know if you have any issues. This branch should be considered beta until the Xcode 9 GA.
